function [t,VAR,Output] = cube
%===========================================================================
% File: cube.m created Nov 12 2025 by MotionGenesis 6.5.
% Portions copyright (c) 2009-2025 Motion Genesis LLC.  Rights reserved.
% MotionGenesis Student Licensee: Charlie Lambert. (until September 2028).
% This MotionGenesis Student license is granted the right to use this code
% only until September 2028, only for legal student-academic (non-professional) purposes,
% and limited to their coursework completion at their accredited school.
% All use of this code is specifically limited to this student licensee.
% No rights are extended for other purposes or to anyone but the licensee.
% This copyright notice must appear in all uses of this code.
%===========================================================================
% The software is provided "as is", without warranty of any kind, express or    
% implied, including but not limited to the warranties of merchantability or    
% fitness for a particular purpose. In no event shall the authors, contributors,
% or copyright holders be liable for any claim, damages or other liability,     
% whether in an action of contract, tort, or otherwise, arising from, out of, or
% in connection with the software or the use or other dealings in the software. 
%===========================================================================
eventDetectedByIntegratorTerminate1OrContinue0 = [];
qX=0; qY=0; qZ=0; qXDt=0; qYDt=0; qZDt=0; qXDDt=0; qYDDt=0; qZDDt=0;
phiDDt=0; thetaDDt=0;


%-------------------------------+--------------------------+-------------------+-----------------
% Quantity                      | Value                    | Units             | Description
%-------------------------------|--------------------------|-------------------|-----------------
CCMX                            =  0.072113;               % m                   Constant
CCMY                            =  0.071399;               % m                   Constant
CCMZ                            =  0.071467;               % m                   Constant
CIXX                            =  0.011496398;            % kg*m^2              Constant
CIXY                            = -0.004360713;            % kg*m^2              Constant
CIXZ                            =  0.004366281;            % kg*m^2              Constant
CIYY                            =  0.011603443;            % kg*m^2              Constant
CIYZ                            =  0.004314224;            % kg*m^2              Constant
CIZZ                            =  0.011600232;            % kg*m^2              Constant
g                               =  9.81;                   % m/s^2               Constant
mC                              =  0.84392696;             % kg                  Constant
mR                              =  0.04711499;             % kg                  Constant
RCMX                            =  0.076;                  % m                   Constant
RCMY                            =  0.076;                  % m                   Constant
RCMZ                            =  0.007789;               % m                   Constant
RXIXX                           =  0.000173232;            % kg*m^2              Constant
RXIXY                           =  8.33e-14;               % kg*m^2              Constant
RXIXZ                           = -3.587e-14;              % kg*m^2              Constant
RXIYY                           =  0.000086943;            % kg*m^2              Constant
RXIYZ                           = -0.000000127;            % kg*m^2              Constant
RXIZZ                           =  0.000087197;            % kg*m^2              Constant
RYIXX                           =  0.000087197;            % kg*m^2              Constant
RYIXY                           =  3.587e-14;              % kg*m^2              Constant
RYIXZ                           = -0.000000127;            % kg*m^2              Constant
RYIYY                           =  0.000173232;            % kg*m^2              Constant
RYIYZ                           = -8.33e-14;               % kg*m^2              Constant
RYIZZ                           =  0.000086943;            % kg*m^2              Constant
RZIXX                           =  0.000087197;            % kg*m^2              Constant
RZIXY                           =  0.000000127;            % kg*m^2              Constant
RZIXZ                           =  3.587e-14;              % kg*m^2              Constant
RZIYY                           =  0.000086943;            % kg*m^2              Constant
RZIYZ                           =  8.33e-14;               % kg*m^2              Constant
RZIZZ                           =  0.000173232;            % kg*m^2              Constant

phi                             =  0.0;                    % UNITS               Initial Value
theta                           =  0.0;                    % UNITS               Initial Value
phiDt                           =  0.0;                    % UNITS               Initial Value
thetaDt                         =  0.0;                    % UNITS               Initial Value

tInitial                        =  0.0;                    % second              Initial Time
tFinal                          =  10.0;                   % second              Final Time
tStep                           =  0.05;                   % second              Integration Step
printIntScreen                  =  1;                      % 0 or +integer       0 is NO screen output
printIntFile                    =  1;                      % 0 or +integer       0 is NO file   output
absError                        =  1.0E-05;                %                     Absolute Error
relError                        =  1.0E-08;                %                     Relative Error
%-------------------------------+--------------------------+-------------------+-----------------


VAR = SetMatrixFromNamedQuantities;
[t,VAR,Output] = IntegrateForwardOrBackward( tInitial, tFinal, tStep, absError, relError, VAR, printIntScreen, printIntFile );
OutputToScreenOrFile( [], 0, 0 );   % Close output files.


%===========================================================================
function sys = mdlDerivatives( t, VAR, uSimulink )
%===========================================================================
SetNamedQuantitiesFromMatrix( VAR );

% Quantities to be specified (not assigned in MotionGenesis).
qX = 0;
qY = 0;
qZ = 0;
qXDt = 0;
qYDt = 0;
qZDt = 0;
qXDDt = 0;
qYDDt = 0;
qZDDt = 0;

thetaDDt = -((RXIXY*sin(theta)*cos(phi+qX)+(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(sin(qZ)*cos(theta)+sin(theta)*cos(phi)*cos(qZ))-RXIXZ*sin(  ...
theta)*sin(phi+qX)-(CIXX+RXIXX+mR*RCMZ^2+2*mR*(RCMY^2+1.5*RCMX^2))*cos(theta)-(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(sin(qY)*cos(theta)+sin(  ...
phi)*sin(theta)*cos(qY))-(RYIXX*cos(qY)+RYIXZ*sin(qY))*(cos(qY)*cos(theta)-sin(phi)*sin(qY)*sin(theta))-(RZIXX*cos(qZ)-RZIXY*sin(  ...
qZ))*(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi))-sin(phi)*sin(theta)*(CIXZ+mR*RCMX*RCMY+mR*RCMX^2+mR*RCMY*RCMZ+RZIXZ*cos(qZ)-  ...
RZIYZ*sin(qZ))-sin(theta)*cos(phi)*(mR*RCMX*RCMY+mR*RCMX*RCMZ+mR*RCMY*RCMZ-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(g*((mC*CCMZ+mR*RCMX+  ...
mR*RCMY+mR*RCMZ)*cos(theta)-(mC*CCMY+mR*RCMY+2*mR*RCMX)*sin(phi)*sin(theta)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(theta)*cos(phi))+  ...
cos(phi+qX)*(2*RXIYZ*cos(phi+qX)*thetaDt*(phiDt+qXDt)+(phiDt+qXDt)*(RXIXY*(phiDt+qXDt)+2*RXIYY*sin(phi+qX)*thetaDt)+RXIXZ*qXDDt)+  ...
sin(qY)*cos(phi)*(RYIXX*sin(qY)*phiDt*qYDt+2*RYIXX*cos(phi)*cos(qY)*qYDt*thetaDt+2*RYIXZ*sin(qY)*cos(phi)*qYDt*thetaDt+4*RYIXZ*sin(  ...
phi)*cos(qY)*phiDt*thetaDt-4*RYIXZ*cos(qY)*phiDt*qYDt-2*RYIXY*cos(phi)*phiDt*thetaDt-2*RYIXX*sin(phi)*sin(qY)*phiDt*thetaDt-qYDt*(  ...
RYIYZ*qYDt+RYIZZ*sin(qY)*phiDt+2*RYIYZ*sin(phi)*thetaDt+2*RYIZZ*cos(phi)*cos(qY)*thetaDt)-RYIXY*qYDDt)-sin(phi+qX)*(2*RXIYZ*sin(phi+  ...
qX)*thetaDt*(phiDt+qXDt)+(phiDt+qXDt)*(RXIXZ*(phiDt+qXDt)+2*RXIZZ*cos(phi+qX)*thetaDt)-RXIXY*qXDDt)-cos(phi)*cos(qY)*(qYDt*(  ...
RYIXY*qYDt+RYIXX*cos(qY)*phiDt)+2*RYIXZ*cos(phi)*cos(qY)*qYDt*thetaDt-RYIZZ*cos(qY)*phiDt*qYDt-RYIYZ*qYDDt)-sin(phi)*cos(qZ)*(  ...
RZIYY*cos(qZ)*phiDt*qZDt+2*RZIXY*sin(qZ)*phiDt*qZDt+RZIYY*sin(phi)*sin(qZ)*qZDt*thetaDt-RZIXY*sin(phi)*cos(qZ)*qZDt*thetaDt-  ...
RZIYY*cos(phi)*cos(qZ)*phiDt*thetaDt-(qZDt+cos(phi)*thetaDt)*(RZIXZ*qZDt+RZIXX*cos(qZ)*phiDt+RZIXZ*cos(phi)*thetaDt+RZIXX*sin(phi)*  ...
sin(qZ)*thetaDt+RZIXY*sin(phi)*cos(qZ)*thetaDt)-RZIYZ*qZDDt)-sin(phi)*sin(qZ)*(RZIXX*sin(qZ)*phiDt*qZDt+RZIXY*sin(phi)*sin(qZ)*qZDt*  ...
thetaDt-2*RZIXY*cos(phi)*cos(qZ)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXX*sin(qZ)*cos(phi)*phiDt*thetaDt-(qZDt+cos(  ...
phi)*thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-2*RZIXY*cos(qZ)*phiDt-RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(  ...
phi)*cos(qZ)*thetaDt)-RZIXZ*qZDDt)-sin(phi)*(2*RYIXY*cos(phi)*cos(qY)*qYDt*thetaDt+cos(qY)*phiDt*(RYIXZ*cos(qY)*phiDt+RYIZZ*sin(qY)*  ...
phiDt+2*RYIYZ*sin(phi)*thetaDt+2*RYIZZ*cos(phi)*cos(qY)*thetaDt)-2*CIYY*cos(phi)*phiDt*thetaDt-2*RYIYY*cos(phi)*phiDt*thetaDt-2*  ...
RYIXY*sin(phi)*sin(qY)*phiDt*thetaDt-sin(qY)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*phiDt^2-phiDt*(RZIYZ*sin(qZ)*phiDt-CIXZ*phiDt-RZIZZ*qZDt-  ...
2*CIYZ*sin(phi)*thetaDt-2*CIZZ*cos(phi)*thetaDt-2*RZIZZ*cos(phi)*thetaDt-RZIXZ*cos(qZ)*phiDt-2*RZIXZ*sin(phi)*sin(qZ)*thetaDt-2*  ...
RZIYZ*sin(phi)*cos(qZ)*thetaDt-mR*RCMX*(RCMX*phiDt+4*RCMY*sin(phi)*thetaDt)-mR*(RCMY*RCMZ*phiDt-2*RCMX^2*cos(phi)*thetaDt)-mR*(RCMX*  ...
RCMY*phiDt+2*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi))*thetaDt))-RYIYY*qYDDt)-cos(phi)*(RZIXZ*sin(qZ)*phiDt*qZDt+RZIYZ*cos(qZ)*phiDt*qZDt+  ...
RZIYZ*sin(phi)*sin(qZ)*qZDt*thetaDt+(cos(qZ)*phiDt+sin(phi)*sin(qZ)*thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-RZIXY*cos(qZ)*phiDt-  ...
RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*cos(qZ)*thetaDt)+(sin(qZ)*phiDt-sin(phi)*cos(qZ)*thetaDt)*(  ...
RZIXY*sin(qZ)*phiDt-RZIXZ*qZDt-RZIXX*cos(qZ)*phiDt-RZIXZ*cos(phi)*thetaDt-RZIXX*sin(phi)*sin(qZ)*thetaDt-RZIXY*sin(phi)*cos(qZ)*  ...
thetaDt)-2*CIYZ*cos(phi)*phiDt*thetaDt-RZIXZ*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXZ*sin(qZ)*cos(phi)*phiDt*thetaDt-RZIYZ*cos(phi)*cos(  ...
qZ)*phiDt*thetaDt-phiDt*(CIXY*phiDt+RYIYY*qYDt+RYIXY*cos(qY)*phiDt+RYIYZ*sin(qY)*phiDt+2*RYIYZ*cos(phi)*cos(qY)*thetaDt-mR*RCMX*RCMY*  ...
phiDt-mR*RCMX*(RCMZ*phiDt-4*RCMY*cos(phi)*thetaDt)-mR*RCMZ*(RCMY*phiDt-2*RCMX*cos(phi)*thetaDt))-RZIZZ*qZDDt))+(RXIXY*sin(phi+qX)+  ...
RXIXZ*cos(phi+qX)+cos(phi)*cos(qY)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))+sin(phi)*sin(qZ)*(RZIXX*cos(qZ)-RZIXY*sin(qZ))+sin(phi)*cos(qZ)*(  ...
RZIXY*cos(qZ)-RZIYY*sin(qZ))+cos(phi)*(CIXZ+mR*RCMX*RCMY+mR*RCMX^2+mR*RCMY*RCMZ+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(qY)*cos(phi)*(  ...
RYIXX*cos(qY)+RYIXZ*sin(qY))-sin(phi)*(mR*RCMX*RCMY+mR*RCMX*RCMZ+mR*RCMY*RCMZ-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(g*((mC*CCMY+mR*  ...
RCMY+2*mR*RCMX)*cos(phi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi))+sin(theta)*thetaDt*(mR*RCMZ*(RCMX*sin(phi)-RCMY*cos(phi))*  ...
thetaDt-CIXX*phiDt-RXIXX*(phiDt+qXDt)-CIXY*sin(phi)*thetaDt-CIXZ*cos(phi)*thetaDt-RXIXY*sin(phi+qX)*thetaDt-RXIXZ*cos(phi+qX)*  ...
thetaDt-2*mR*(RCMY^2+1.5*RCMX^2)*phiDt-mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi))*thetaDt-mR*(RCMZ^2*phiDt+RCMY*(RCMX*cos(phi)-RCMZ*sin(  ...
phi))*thetaDt))+sin(theta)*cos(phi+qX)*(4*RXIYZ*sin(phi+qX)*thetaDt*(phiDt+qXDt)+(phiDt+qXDt)*(RXIXZ*(phiDt+qXDt)+RXIZZ*cos(phi+qX)*  ...
thetaDt)-RXIYY*cos(phi+qX)*thetaDt*(phiDt+qXDt)-RXIXY*qXDDt)+(sin(qZ)*cos(theta)+sin(theta)*cos(phi)*cos(qZ))*(RZIXY*sin(qZ)*  ...
phiDt*qZDt+RZIYY*cos(qZ)*phiDt*qZDt+RZIYZ*sin(phi)*phiDt*thetaDt+RZIYY*sin(phi)*sin(qZ)*qZDt*thetaDt+(qZDt+cos(phi)*thetaDt)*(  ...
RZIXY*sin(qZ)*phiDt-RZIXZ*qZDt-RZIXX*cos(qZ)*phiDt-RZIXZ*cos(phi)*thetaDt-RZIXX*sin(phi)*sin(qZ)*thetaDt-RZIXY*sin(phi)*cos(qZ)*  ...
thetaDt)-RZIXY*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXY*sin(qZ)*cos(phi)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ)*phiDt*thetaDt-RZIYZ*  ...
qZDDt)+sin(theta)*cos(phi)*(RYIXY*sin(qY)*phiDt*qYDt+RYIXY*cos(phi)*cos(qY)*qYDt*thetaDt+RYIYZ*sin(qY)*cos(phi)*qYDt*thetaDt+(sin(  ...
qY)*phiDt+cos(phi)*cos(qY)*thetaDt)*(RYIXX*sin(qY)*cos(phi)*thetaDt-RYIXY*qYDt-RYIXX*cos(qY)*phiDt-RYIXY*sin(phi)*thetaDt-RYIXZ*sin(  ...
qY)*phiDt-RYIXZ*cos(phi)*cos(qY)*thetaDt)-CIYY*cos(phi)*phiDt*thetaDt-RYIYY*cos(phi)*phiDt*thetaDt-RYIYZ*cos(qY)*phiDt*qYDt-(cos(  ...
qY)*phiDt-sin(qY)*cos(phi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi)*thetaDt-RYIYZ*qYDt-RYIXZ*cos(qY)*phiDt-RYIYZ*sin(phi)*thetaDt-RYIZZ*sin(  ...
qY)*phiDt-RYIZZ*cos(phi)*cos(qY)*thetaDt)-phiDt*(RZIYZ*sin(qZ)*phiDt-CIXZ*phiDt-RZIZZ*qZDt-mR*RCMX^2*phiDt-CIZZ*cos(phi)*thetaDt-  ...
RZIXZ*cos(qZ)*phiDt-RZIZZ*cos(phi)*thetaDt-mR*(RCMX*RCMY*phiDt+RCMZ^2*cos(phi)*thetaDt)-mR*(RCMY*RCMZ*phiDt-RCMX^2*cos(phi)*  ...
thetaDt))-RYIYY*qYDDt)-sin(theta)*sin(phi+qX)*(RXIZZ*sin(phi+qX)*thetaDt*(phiDt+qXDt)-(phiDt+qXDt)*(RXIXY*(phiDt+qXDt)+RXIYY*sin(  ...
phi+qX)*thetaDt)-RXIXZ*qXDDt)-(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(qY))*(RYIXZ*sin(qY)*phiDt*qYDt+RYIXZ*cos(phi)*cos(qY)*qYDt*  ...
thetaDt+RYIZZ*sin(phi)*cos(qY)*phiDt*thetaDt+RYIZZ*sin(qY)*cos(phi)*qYDt*thetaDt-RYIYZ*cos(phi)*phiDt*thetaDt-RYIZZ*cos(qY)*  ...
phiDt*qYDt-RYIXZ*sin(phi)*sin(qY)*phiDt*thetaDt-(qYDt+sin(phi)*thetaDt)*(RYIXX*sin(qY)*cos(phi)*thetaDt-RYIXY*qYDt-RYIXX*cos(qY)*  ...
phiDt-RYIXY*sin(phi)*thetaDt-RYIXZ*sin(qY)*phiDt-RYIXZ*cos(phi)*cos(qY)*thetaDt)-RYIYZ*qYDDt)-(cos(qY)*cos(theta)-sin(phi)*sin(qY)*  ...
sin(theta))*(RYIXX*sin(qY)*phiDt*qYDt+RYIXX*cos(phi)*cos(qY)*qYDt*thetaDt+RYIXZ*sin(phi)*cos(qY)*phiDt*thetaDt+RYIXZ*sin(qY)*cos(  ...
phi)*qYDt*thetaDt+(qYDt+sin(phi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi)*thetaDt-RYIYZ*qYDt-RYIXZ*cos(qY)*phiDt-RYIYZ*sin(phi)*thetaDt-  ...
RYIZZ*sin(qY)*phiDt-RYIZZ*cos(phi)*cos(qY)*thetaDt)-RYIXY*cos(phi)*phiDt*thetaDt-RYIXZ*cos(qY)*phiDt*qYDt-RYIXX*sin(phi)*sin(qY)*  ...
phiDt*thetaDt-RYIXY*qYDDt)-(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi))*(RZIXX*sin(qZ)*phiDt*qZDt+RZIXY*cos(qZ)*phiDt*qZDt+  ...
RZIXZ*sin(phi)*phiDt*thetaDt+RZIXY*sin(phi)*sin(qZ)*qZDt*thetaDt-RZIXX*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXX*sin(qZ)*cos(phi)*  ...
phiDt*thetaDt-RZIXY*cos(phi)*cos(qZ)*phiDt*thetaDt-(qZDt+cos(phi)*thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-RZIXY*cos(qZ)*phiDt-  ...
RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*cos(qZ)*thetaDt)-RZIXZ*qZDDt)-cos(theta)*(sin(phi)*thetaDt*(  ...
RZIYZ*sin(qZ)*phiDt-RZIZZ*qZDt-CIYZ*sin(phi)*thetaDt-CIZZ*cos(phi)*thetaDt-RZIXZ*cos(qZ)*phiDt-RZIZZ*cos(phi)*thetaDt-2*mR*RCMX*RCMY*  ...
sin(phi)*thetaDt-RZIXZ*sin(phi)*sin(qZ)*thetaDt-RZIYZ*sin(phi)*cos(qZ)*thetaDt-mR*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi))*thetaDt)-(sin(  ...
phi+qX)*(RXIYZ*sin(phi+qX)+RXIZZ*cos(phi+qX))-cos(phi+qX)*(RXIYY*sin(phi+qX)+RXIYZ*cos(phi+qX)))*thetaDt^2-cos(phi)*thetaDt*(  ...
RYIXY*sin(qY)*cos(phi)*thetaDt-RYIYY*qYDt-CIYY*sin(phi)*thetaDt-CIYZ*cos(phi)*thetaDt-RYIXY*cos(qY)*phiDt-RYIYY*sin(phi)*thetaDt-  ...
RYIYZ*sin(qY)*phiDt-2*mR*RCMX*RCMY*cos(phi)*thetaDt-mR*RCMX*RCMZ*cos(phi)*thetaDt-mR*RCMX^2*sin(phi)*thetaDt-RYIYZ*cos(phi)*cos(qY)*  ...
thetaDt)-RXIXX*qXDDt)-sin(phi)*sin(theta)*(CIZZ*sin(phi)*phiDt*thetaDt+RZIXZ*sin(qZ)*phiDt*qZDt+RZIYZ*cos(qZ)*phiDt*qZDt+RZIZZ*sin(  ...
phi)*phiDt*thetaDt+mR*RCMZ^2*sin(phi)*phiDt*thetaDt+RZIYZ*sin(phi)*sin(qZ)*qZDt*thetaDt+(cos(qZ)*phiDt+sin(phi)*sin(qZ)*thetaDt)*(  ...
RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-RZIXY*cos(qZ)*phiDt-RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*cos(qZ)*  ...
thetaDt)+(sin(qZ)*phiDt-sin(phi)*cos(qZ)*thetaDt)*(RZIXY*sin(qZ)*phiDt-RZIXZ*qZDt-RZIXX*cos(qZ)*phiDt-RZIXZ*cos(phi)*thetaDt-  ...
RZIXX*sin(phi)*sin(qZ)*thetaDt-RZIXY*sin(phi)*cos(qZ)*thetaDt)-4*CIYZ*cos(phi)*phiDt*thetaDt-2*RZIXZ*sin(qZ)*cos(phi)*phiDt*  ...
thetaDt-2*RZIYZ*cos(phi)*cos(qZ)*phiDt*thetaDt-RZIXZ*sin(phi)*cos(qZ)*qZDt*thetaDt-phiDt*(CIXY*phiDt+RYIYY*qYDt+CIYY*sin(phi)*  ...
thetaDt+RYIXY*cos(qY)*phiDt+RYIYY*sin(phi)*thetaDt+RYIYZ*sin(qY)*phiDt+2*RYIYZ*cos(phi)*cos(qY)*thetaDt-2*RYIXY*sin(qY)*cos(phi)*  ...
thetaDt-mR*RCMX*(RCMY*phiDt-RCMX*sin(phi)*thetaDt)-mR*RCMX*(RCMZ*phiDt-8*RCMY*cos(phi)*thetaDt)-mR*RCMZ*(RCMY*phiDt-4*RCMX*cos(phi)*  ...
thetaDt))-RZIZZ*qZDDt)))/((2*mR*RCMY^2+mR*(RCMX^2+RCMZ^2)+RXIYY*sin(phi+qX)^2+RYIZZ*cos(phi)^2*cos(qY)^2+RZIXX*sin(phi)^2*sin(qZ)^2+  ...
cos(phi+qX)*(RXIZZ*cos(phi+qX)+2*RXIYZ*sin(phi+qX))+cos(qZ)*sin(phi)^2*(RZIYY*cos(qZ)+2*RZIXY*sin(qZ))+sin(qY)*cos(phi)*(RYIXX*sin(  ...
qY)*cos(phi)-2*RYIXY*sin(phi)-2*RYIXZ*cos(phi)*cos(qY))+cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+mR*RCMX^2*cos(phi)+mR*RCMZ^2*cos(phi)+  ...
2*RZIXZ*sin(phi)*sin(qZ)+2*RZIYZ*sin(phi)*cos(qZ))+sin(phi)*(CIYY*sin(phi)+RYIYY*sin(phi)+2*CIYZ*cos(phi)+2*mR*RCMX*RCMZ*cos(phi)+  ...
2*mR*RCMX^2*sin(phi)+4*mR*RCMX*RCMY*cos(phi)+2*RYIYZ*cos(phi)*cos(qY)))*(RXIXY*sin(theta)*cos(phi+qX)+(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(  ...
sin(qZ)*cos(theta)+sin(theta)*cos(phi)*cos(qZ))-RXIXZ*sin(theta)*sin(phi+qX)-(CIXX+RXIXX+mR*RCMZ^2+2*mR*(RCMY^2+1.5*RCMX^2))*cos(  ...
theta)-(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(qY))-(RYIXX*cos(qY)+RYIXZ*sin(qY))*(cos(qY)*cos(  ...
theta)-sin(phi)*sin(qY)*sin(theta))-(RZIXX*cos(qZ)-RZIXY*sin(qZ))*(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi))-sin(phi)*sin(  ...
theta)*(CIXZ+mR*RCMX*RCMY+mR*RCMX^2+mR*RCMY*RCMZ+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(theta)*cos(phi)*(mR*RCMX*RCMY+mR*RCMX*RCMZ+mR*RCMY*  ...
RCMZ-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))+(RXIXY*sin(phi+qX)+RXIXZ*cos(phi+qX)+cos(phi)*cos(qY)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))+sin(phi)*  ...
sin(qZ)*(RZIXX*cos(qZ)-RZIXY*sin(qZ))+sin(phi)*cos(qZ)*(RZIXY*cos(qZ)-RZIYY*sin(qZ))+cos(phi)*(CIXZ+mR*RCMX*RCMY+mR*RCMX^2+mR*RCMY*  ...
RCMZ+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(qY)*cos(phi)*(RYIXX*cos(qY)+RYIXZ*sin(qY))-sin(phi)*(mR*RCMX*RCMY+mR*RCMX*RCMZ+mR*RCMY*RCMZ-  ...
CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(sin(theta)*sin(phi+qX)*(RXIYZ*sin(phi+qX)+RXIZZ*cos(phi+qX))+(cos(qZ)*cos(theta)-sin(qZ)*sin(  ...
theta)*cos(phi))*(RZIXZ*cos(phi)+RZIXX*sin(phi)*sin(qZ)+RZIXY*sin(phi)*cos(qZ))+sin(theta)*cos(phi)*(RYIXY*sin(qY)*cos(phi)-CIYY*  ...
sin(phi)-CIYZ*cos(phi)-RYIYY*sin(phi)-2*mR*RCMX*RCMY*cos(phi)-mR*RCMX*RCMZ*cos(phi)-RYIYZ*cos(phi)*cos(qY))+cos(theta)*(CIXY*sin(  ...
phi)+CIXZ*cos(phi)+RXIXY*sin(phi+qX)+RXIXZ*cos(phi+qX)+mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi))-  ...
mR*RCMZ*(RCMX*sin(phi)-RCMY*cos(phi)))-sin(theta)*cos(phi+qX)*(RXIYY*sin(phi+qX)+RXIYZ*cos(phi+qX))-(sin(qZ)*cos(theta)+sin(  ...
theta)*cos(phi)*cos(qZ))*(RZIYZ*cos(phi)+RZIXY*sin(phi)*sin(qZ)+RZIYY*sin(phi)*cos(qZ))-(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(  ...
qY))*(RYIXZ*sin(qY)*cos(phi)-RYIYZ*sin(phi)-RYIZZ*cos(phi)*cos(qY))-(cos(qY)*cos(theta)-sin(phi)*sin(qY)*sin(theta))*(RYIXX*sin(qY)*  ...
cos(phi)-RYIXY*sin(phi)-RYIXZ*cos(phi)*cos(qY))-sin(phi)*sin(theta)*(mR*RCMX^2*cos(phi)-CIYZ*sin(phi)-CIZZ*cos(phi)-RZIZZ*cos(phi)-  ...
2*mR*RCMX*RCMY*sin(phi)-RZIXZ*sin(phi)*sin(qZ)-RZIYZ*sin(phi)*cos(qZ)-mR*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi)))));
phiDDt = -((sin(theta)*sin(phi+qX)*(RXIYZ*sin(phi+qX)+RXIZZ*cos(phi+qX))+(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi))*(RZIXZ*  ...
cos(phi)+RZIXX*sin(phi)*sin(qZ)+RZIXY*sin(phi)*cos(qZ))+sin(theta)*cos(phi)*(RYIXY*sin(qY)*cos(phi)-CIYY*sin(phi)-CIYZ*cos(phi)-  ...
RYIYY*sin(phi)-2*mR*RCMX*RCMY*cos(phi)-mR*RCMX*RCMZ*cos(phi)-RYIYZ*cos(phi)*cos(qY))+cos(theta)*(CIXY*sin(phi)+CIXZ*cos(phi)+  ...
RXIXY*sin(phi+qX)+RXIXZ*cos(phi+qX)+mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi))-mR*RCMZ*(RCMX*sin(  ...
phi)-RCMY*cos(phi)))-sin(theta)*cos(phi+qX)*(RXIYY*sin(phi+qX)+RXIYZ*cos(phi+qX))-(sin(qZ)*cos(theta)+sin(theta)*cos(phi)*cos(qZ))*(  ...
RZIYZ*cos(phi)+RZIXY*sin(phi)*sin(qZ)+RZIYY*sin(phi)*cos(qZ))-(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(qY))*(RYIXZ*sin(qY)*cos(  ...
phi)-RYIYZ*sin(phi)-RYIZZ*cos(phi)*cos(qY))-(cos(qY)*cos(theta)-sin(phi)*sin(qY)*sin(theta))*(RYIXX*sin(qY)*cos(phi)-RYIXY*sin(phi)-  ...
RYIXZ*cos(phi)*cos(qY))-sin(phi)*sin(theta)*(mR*RCMX^2*cos(phi)-CIYZ*sin(phi)-CIZZ*cos(phi)-RZIZZ*cos(phi)-2*mR*RCMX*RCMY*sin(phi)-  ...
RZIXZ*sin(phi)*sin(qZ)-RZIYZ*sin(phi)*cos(qZ)-mR*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi))))*(g*((mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*cos(  ...
theta)-(mC*CCMY+mR*RCMY+2*mR*RCMX)*sin(phi)*sin(theta)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(theta)*cos(phi))+cos(phi+qX)*(2*  ...
RXIYZ*cos(phi+qX)*thetaDt*(phiDt+qXDt)+(phiDt+qXDt)*(RXIXY*(phiDt+qXDt)+2*RXIYY*sin(phi+qX)*thetaDt)+RXIXZ*qXDDt)+sin(qY)*cos(phi)*(  ...
RYIXX*sin(qY)*phiDt*qYDt+2*RYIXX*cos(phi)*cos(qY)*qYDt*thetaDt+2*RYIXZ*sin(qY)*cos(phi)*qYDt*thetaDt+4*RYIXZ*sin(phi)*cos(qY)*  ...
phiDt*thetaDt-4*RYIXZ*cos(qY)*phiDt*qYDt-2*RYIXY*cos(phi)*phiDt*thetaDt-2*RYIXX*sin(phi)*sin(qY)*phiDt*thetaDt-qYDt*(RYIYZ*qYDt+  ...
RYIZZ*sin(qY)*phiDt+2*RYIYZ*sin(phi)*thetaDt+2*RYIZZ*cos(phi)*cos(qY)*thetaDt)-RYIXY*qYDDt)-sin(phi+qX)*(2*RXIYZ*sin(phi+qX)*  ...
thetaDt*(phiDt+qXDt)+(phiDt+qXDt)*(RXIXZ*(phiDt+qXDt)+2*RXIZZ*cos(phi+qX)*thetaDt)-RXIXY*qXDDt)-cos(phi)*cos(qY)*(qYDt*(RYIXY*qYDt+  ...
RYIXX*cos(qY)*phiDt)+2*RYIXZ*cos(phi)*cos(qY)*qYDt*thetaDt-RYIZZ*cos(qY)*phiDt*qYDt-RYIYZ*qYDDt)-sin(phi)*cos(qZ)*(RZIYY*cos(qZ)*  ...
phiDt*qZDt+2*RZIXY*sin(qZ)*phiDt*qZDt+RZIYY*sin(phi)*sin(qZ)*qZDt*thetaDt-RZIXY*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIYY*cos(phi)*cos(  ...
qZ)*phiDt*thetaDt-(qZDt+cos(phi)*thetaDt)*(RZIXZ*qZDt+RZIXX*cos(qZ)*phiDt+RZIXZ*cos(phi)*thetaDt+RZIXX*sin(phi)*sin(qZ)*thetaDt+  ...
RZIXY*sin(phi)*cos(qZ)*thetaDt)-RZIYZ*qZDDt)-sin(phi)*sin(qZ)*(RZIXX*sin(qZ)*phiDt*qZDt+RZIXY*sin(phi)*sin(qZ)*qZDt*thetaDt-2*  ...
RZIXY*cos(phi)*cos(qZ)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXX*sin(qZ)*cos(phi)*phiDt*thetaDt-(qZDt+cos(phi)*  ...
thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-2*RZIXY*cos(qZ)*phiDt-RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*  ...
cos(qZ)*thetaDt)-RZIXZ*qZDDt)-sin(phi)*(2*RYIXY*cos(phi)*cos(qY)*qYDt*thetaDt+cos(qY)*phiDt*(RYIXZ*cos(qY)*phiDt+RYIZZ*sin(qY)*  ...
phiDt+2*RYIYZ*sin(phi)*thetaDt+2*RYIZZ*cos(phi)*cos(qY)*thetaDt)-2*CIYY*cos(phi)*phiDt*thetaDt-2*RYIYY*cos(phi)*phiDt*thetaDt-2*  ...
RYIXY*sin(phi)*sin(qY)*phiDt*thetaDt-sin(qY)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*phiDt^2-phiDt*(RZIYZ*sin(qZ)*phiDt-CIXZ*phiDt-RZIZZ*qZDt-  ...
2*CIYZ*sin(phi)*thetaDt-2*CIZZ*cos(phi)*thetaDt-2*RZIZZ*cos(phi)*thetaDt-RZIXZ*cos(qZ)*phiDt-2*RZIXZ*sin(phi)*sin(qZ)*thetaDt-2*  ...
RZIYZ*sin(phi)*cos(qZ)*thetaDt-mR*RCMX*(RCMX*phiDt+4*RCMY*sin(phi)*thetaDt)-mR*(RCMY*RCMZ*phiDt-2*RCMX^2*cos(phi)*thetaDt)-mR*(RCMX*  ...
RCMY*phiDt+2*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi))*thetaDt))-RYIYY*qYDDt)-cos(phi)*(RZIXZ*sin(qZ)*phiDt*qZDt+RZIYZ*cos(qZ)*phiDt*qZDt+  ...
RZIYZ*sin(phi)*sin(qZ)*qZDt*thetaDt+(cos(qZ)*phiDt+sin(phi)*sin(qZ)*thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-RZIXY*cos(qZ)*phiDt-  ...
RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*cos(qZ)*thetaDt)+(sin(qZ)*phiDt-sin(phi)*cos(qZ)*thetaDt)*(  ...
RZIXY*sin(qZ)*phiDt-RZIXZ*qZDt-RZIXX*cos(qZ)*phiDt-RZIXZ*cos(phi)*thetaDt-RZIXX*sin(phi)*sin(qZ)*thetaDt-RZIXY*sin(phi)*cos(qZ)*  ...
thetaDt)-2*CIYZ*cos(phi)*phiDt*thetaDt-RZIXZ*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXZ*sin(qZ)*cos(phi)*phiDt*thetaDt-RZIYZ*cos(phi)*cos(  ...
qZ)*phiDt*thetaDt-phiDt*(CIXY*phiDt+RYIYY*qYDt+RYIXY*cos(qY)*phiDt+RYIYZ*sin(qY)*phiDt+2*RYIYZ*cos(phi)*cos(qY)*thetaDt-mR*RCMX*RCMY*  ...
phiDt-mR*RCMX*(RCMZ*phiDt-4*RCMY*cos(phi)*thetaDt)-mR*RCMZ*(RCMY*phiDt-2*RCMX*cos(phi)*thetaDt))-RZIZZ*qZDDt))-(2*mR*RCMY^2+mR*(RCMX^2+RCMZ^2)+  ...
RXIYY*sin(phi+qX)^2+RYIZZ*cos(phi)^2*cos(qY)^2+RZIXX*sin(phi)^2*sin(qZ)^2+cos(phi+qX)*(RXIZZ*cos(phi+qX)+2*RXIYZ*sin(phi+qX))+cos(  ...
qZ)*sin(phi)^2*(RZIYY*cos(qZ)+2*RZIXY*sin(qZ))+sin(qY)*cos(phi)*(RYIXX*sin(qY)*cos(phi)-2*RYIXY*sin(phi)-2*RYIXZ*cos(phi)*cos(qY))+  ...
cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+mR*RCMX^2*cos(phi)+mR*RCMZ^2*cos(phi)+2*RZIXZ*sin(phi)*sin(qZ)+2*RZIYZ*sin(phi)*cos(qZ))+sin(  ...
phi)*(CIYY*sin(phi)+RYIYY*sin(phi)+2*CIYZ*cos(phi)+2*mR*RCMX*RCMZ*cos(phi)+2*mR*RCMX^2*sin(phi)+4*mR*RCMX*RCMY*cos(phi)+2*RYIYZ*cos(  ...
phi)*cos(qY)))*(g*((mC*CCMY+mR*RCMY+2*mR*RCMX)*cos(phi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi))+sin(theta)*thetaDt*(mR*RCMZ*(  ...
RCMX*sin(phi)-RCMY*cos(phi))*thetaDt-CIXX*phiDt-RXIXX*(phiDt+qXDt)-CIXY*sin(phi)*thetaDt-CIXZ*cos(phi)*thetaDt-RXIXY*sin(phi+qX)*  ...
thetaDt-RXIXZ*cos(phi+qX)*thetaDt-2*mR*(RCMY^2+1.5*RCMX^2)*phiDt-mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi))*thetaDt-mR*(RCMZ^2*phiDt+RCMY*(  ...
RCMX*cos(phi)-RCMZ*sin(phi))*thetaDt))+sin(theta)*cos(phi+qX)*(4*RXIYZ*sin(phi+qX)*thetaDt*(phiDt+qXDt)+(phiDt+qXDt)*(RXIXZ*(  ...
phiDt+qXDt)+RXIZZ*cos(phi+qX)*thetaDt)-RXIYY*cos(phi+qX)*thetaDt*(phiDt+qXDt)-RXIXY*qXDDt)+(sin(qZ)*cos(theta)+sin(theta)*cos(phi)*  ...
cos(qZ))*(RZIXY*sin(qZ)*phiDt*qZDt+RZIYY*cos(qZ)*phiDt*qZDt+RZIYZ*sin(phi)*phiDt*thetaDt+RZIYY*sin(phi)*sin(qZ)*qZDt*thetaDt+(qZDt+  ...
cos(phi)*thetaDt)*(RZIXY*sin(qZ)*phiDt-RZIXZ*qZDt-RZIXX*cos(qZ)*phiDt-RZIXZ*cos(phi)*thetaDt-RZIXX*sin(phi)*sin(qZ)*thetaDt-  ...
RZIXY*sin(phi)*cos(qZ)*thetaDt)-RZIXY*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXY*sin(qZ)*cos(phi)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ)*  ...
phiDt*thetaDt-RZIYZ*qZDDt)+sin(theta)*cos(phi)*(RYIXY*sin(qY)*phiDt*qYDt+RYIXY*cos(phi)*cos(qY)*qYDt*thetaDt+RYIYZ*sin(qY)*cos(phi)*  ...
qYDt*thetaDt+(sin(qY)*phiDt+cos(phi)*cos(qY)*thetaDt)*(RYIXX*sin(qY)*cos(phi)*thetaDt-RYIXY*qYDt-RYIXX*cos(qY)*phiDt-RYIXY*sin(phi)*  ...
thetaDt-RYIXZ*sin(qY)*phiDt-RYIXZ*cos(phi)*cos(qY)*thetaDt)-CIYY*cos(phi)*phiDt*thetaDt-RYIYY*cos(phi)*phiDt*thetaDt-RYIYZ*cos(qY)*  ...
phiDt*qYDt-(cos(qY)*phiDt-sin(qY)*cos(phi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi)*thetaDt-RYIYZ*qYDt-RYIXZ*cos(qY)*phiDt-RYIYZ*sin(phi)*  ...
thetaDt-RYIZZ*sin(qY)*phiDt-RYIZZ*cos(phi)*cos(qY)*thetaDt)-phiDt*(RZIYZ*sin(qZ)*phiDt-CIXZ*phiDt-RZIZZ*qZDt-mR*RCMX^2*phiDt-CIZZ*  ...
cos(phi)*thetaDt-RZIXZ*cos(qZ)*phiDt-RZIZZ*cos(phi)*thetaDt-mR*(RCMX*RCMY*phiDt+RCMZ^2*cos(phi)*thetaDt)-mR*(RCMY*RCMZ*phiDt-RCMX^2*  ...
cos(phi)*thetaDt))-RYIYY*qYDDt)-sin(theta)*sin(phi+qX)*(RXIZZ*sin(phi+qX)*thetaDt*(phiDt+qXDt)-(phiDt+qXDt)*(RXIXY*(phiDt+qXDt)+  ...
RXIYY*sin(phi+qX)*thetaDt)-RXIXZ*qXDDt)-(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(qY))*(RYIXZ*sin(qY)*phiDt*qYDt+RYIXZ*cos(phi)*  ...
cos(qY)*qYDt*thetaDt+RYIZZ*sin(phi)*cos(qY)*phiDt*thetaDt+RYIZZ*sin(qY)*cos(phi)*qYDt*thetaDt-RYIYZ*cos(phi)*phiDt*thetaDt-RYIZZ*  ...
cos(qY)*phiDt*qYDt-RYIXZ*sin(phi)*sin(qY)*phiDt*thetaDt-(qYDt+sin(phi)*thetaDt)*(RYIXX*sin(qY)*cos(phi)*thetaDt-RYIXY*qYDt-RYIXX*  ...
cos(qY)*phiDt-RYIXY*sin(phi)*thetaDt-RYIXZ*sin(qY)*phiDt-RYIXZ*cos(phi)*cos(qY)*thetaDt)-RYIYZ*qYDDt)-(cos(qY)*cos(theta)-sin(phi)*  ...
sin(qY)*sin(theta))*(RYIXX*sin(qY)*phiDt*qYDt+RYIXX*cos(phi)*cos(qY)*qYDt*thetaDt+RYIXZ*sin(phi)*cos(qY)*phiDt*thetaDt+RYIXZ*sin(  ...
qY)*cos(phi)*qYDt*thetaDt+(qYDt+sin(phi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi)*thetaDt-RYIYZ*qYDt-RYIXZ*cos(qY)*phiDt-RYIYZ*sin(phi)*  ...
thetaDt-RYIZZ*sin(qY)*phiDt-RYIZZ*cos(phi)*cos(qY)*thetaDt)-RYIXY*cos(phi)*phiDt*thetaDt-RYIXZ*cos(qY)*phiDt*qYDt-RYIXX*sin(phi)*  ...
sin(qY)*phiDt*thetaDt-RYIXY*qYDDt)-(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi))*(RZIXX*sin(qZ)*phiDt*qZDt+RZIXY*cos(qZ)*  ...
phiDt*qZDt+RZIXZ*sin(phi)*phiDt*thetaDt+RZIXY*sin(phi)*sin(qZ)*qZDt*thetaDt-RZIXX*sin(phi)*cos(qZ)*qZDt*thetaDt-RZIXX*sin(qZ)*cos(  ...
phi)*phiDt*thetaDt-RZIXY*cos(phi)*cos(qZ)*phiDt*thetaDt-(qZDt+cos(phi)*thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-RZIXY*cos(qZ)*  ...
phiDt-RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*cos(qZ)*thetaDt)-RZIXZ*qZDDt)-cos(theta)*(sin(phi)*  ...
thetaDt*(RZIYZ*sin(qZ)*phiDt-RZIZZ*qZDt-CIYZ*sin(phi)*thetaDt-CIZZ*cos(phi)*thetaDt-RZIXZ*cos(qZ)*phiDt-RZIZZ*cos(phi)*thetaDt-2*  ...
mR*RCMX*RCMY*sin(phi)*thetaDt-RZIXZ*sin(phi)*sin(qZ)*thetaDt-RZIYZ*sin(phi)*cos(qZ)*thetaDt-mR*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi))*  ...
thetaDt)-(sin(phi+qX)*(RXIYZ*sin(phi+qX)+RXIZZ*cos(phi+qX))-cos(phi+qX)*(RXIYY*sin(phi+qX)+RXIYZ*cos(phi+qX)))*thetaDt^2-cos(phi)*  ...
thetaDt*(RYIXY*sin(qY)*cos(phi)*thetaDt-RYIYY*qYDt-CIYY*sin(phi)*thetaDt-CIYZ*cos(phi)*thetaDt-RYIXY*cos(qY)*phiDt-RYIYY*sin(phi)*  ...
thetaDt-RYIYZ*sin(qY)*phiDt-2*mR*RCMX*RCMY*cos(phi)*thetaDt-mR*RCMX*RCMZ*cos(phi)*thetaDt-mR*RCMX^2*sin(phi)*thetaDt-RYIYZ*cos(phi)*  ...
cos(qY)*thetaDt)-RXIXX*qXDDt)-sin(phi)*sin(theta)*(CIZZ*sin(phi)*phiDt*thetaDt+RZIXZ*sin(qZ)*phiDt*qZDt+RZIYZ*cos(qZ)*phiDt*qZDt+  ...
RZIZZ*sin(phi)*phiDt*thetaDt+mR*RCMZ^2*sin(phi)*phiDt*thetaDt+RZIYZ*sin(phi)*sin(qZ)*qZDt*thetaDt+(cos(qZ)*phiDt+sin(phi)*sin(qZ)*  ...
thetaDt)*(RZIYY*sin(qZ)*phiDt-RZIYZ*qZDt-RZIXY*cos(qZ)*phiDt-RZIYZ*cos(phi)*thetaDt-RZIXY*sin(phi)*sin(qZ)*thetaDt-RZIYY*sin(phi)*  ...
cos(qZ)*thetaDt)+(sin(qZ)*phiDt-sin(phi)*cos(qZ)*thetaDt)*(RZIXY*sin(qZ)*phiDt-RZIXZ*qZDt-RZIXX*cos(qZ)*phiDt-RZIXZ*cos(phi)*  ...
thetaDt-RZIXX*sin(phi)*sin(qZ)*thetaDt-RZIXY*sin(phi)*cos(qZ)*thetaDt)-4*CIYZ*cos(phi)*phiDt*thetaDt-2*RZIXZ*sin(qZ)*cos(phi)*  ...
phiDt*thetaDt-2*RZIYZ*cos(phi)*cos(qZ)*phiDt*thetaDt-RZIXZ*sin(phi)*cos(qZ)*qZDt*thetaDt-phiDt*(CIXY*phiDt+RYIYY*qYDt+CIYY*sin(phi)*  ...
thetaDt+RYIXY*cos(qY)*phiDt+RYIYY*sin(phi)*thetaDt+RYIYZ*sin(qY)*phiDt+2*RYIYZ*cos(phi)*cos(qY)*thetaDt-2*RYIXY*sin(qY)*cos(phi)*  ...
thetaDt-mR*RCMX*(RCMY*phiDt-RCMX*sin(phi)*thetaDt)-mR*RCMX*(RCMZ*phiDt-8*RCMY*cos(phi)*thetaDt)-mR*RCMZ*(RCMY*phiDt-4*RCMX*cos(phi)*  ...
thetaDt))-RZIZZ*qZDDt)))/((2*mR*RCMY^2+mR*(RCMX^2+RCMZ^2)+RXIYY*sin(phi+qX)^2+RYIZZ*cos(phi)^2*cos(qY)^2+RZIXX*sin(phi)^2*sin(qZ)^2+  ...
cos(phi+qX)*(RXIZZ*cos(phi+qX)+2*RXIYZ*sin(phi+qX))+cos(qZ)*sin(phi)^2*(RZIYY*cos(qZ)+2*RZIXY*sin(qZ))+sin(qY)*cos(phi)*(RYIXX*sin(  ...
qY)*cos(phi)-2*RYIXY*sin(phi)-2*RYIXZ*cos(phi)*cos(qY))+cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+mR*RCMX^2*cos(phi)+mR*RCMZ^2*cos(phi)+  ...
2*RZIXZ*sin(phi)*sin(qZ)+2*RZIYZ*sin(phi)*cos(qZ))+sin(phi)*(CIYY*sin(phi)+RYIYY*sin(phi)+2*CIYZ*cos(phi)+2*mR*RCMX*RCMZ*cos(phi)+  ...
2*mR*RCMX^2*sin(phi)+4*mR*RCMX*RCMY*cos(phi)+2*RYIYZ*cos(phi)*cos(qY)))*(RXIXY*sin(theta)*cos(phi+qX)+(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(  ...
sin(qZ)*cos(theta)+sin(theta)*cos(phi)*cos(qZ))-RXIXZ*sin(theta)*sin(phi+qX)-(CIXX+RXIXX+mR*RCMZ^2+2*mR*(RCMY^2+1.5*RCMX^2))*cos(  ...
theta)-(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(qY))-(RYIXX*cos(qY)+RYIXZ*sin(qY))*(cos(qY)*cos(  ...
theta)-sin(phi)*sin(qY)*sin(theta))-(RZIXX*cos(qZ)-RZIXY*sin(qZ))*(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi))-sin(phi)*sin(  ...
theta)*(CIXZ+mR*RCMX*RCMY+mR*RCMX^2+mR*RCMY*RCMZ+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(theta)*cos(phi)*(mR*RCMX*RCMY+mR*RCMX*RCMZ+mR*RCMY*  ...
RCMZ-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))+(RXIXY*sin(phi+qX)+RXIXZ*cos(phi+qX)+cos(phi)*cos(qY)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))+sin(phi)*  ...
sin(qZ)*(RZIXX*cos(qZ)-RZIXY*sin(qZ))+sin(phi)*cos(qZ)*(RZIXY*cos(qZ)-RZIYY*sin(qZ))+cos(phi)*(CIXZ+mR*RCMX*RCMY+mR*RCMX^2+mR*RCMY*  ...
RCMZ+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(qY)*cos(phi)*(RYIXX*cos(qY)+RYIXZ*sin(qY))-sin(phi)*(mR*RCMX*RCMY+mR*RCMX*RCMZ+mR*RCMY*RCMZ-  ...
CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(sin(theta)*sin(phi+qX)*(RXIYZ*sin(phi+qX)+RXIZZ*cos(phi+qX))+(cos(qZ)*cos(theta)-sin(qZ)*sin(  ...
theta)*cos(phi))*(RZIXZ*cos(phi)+RZIXX*sin(phi)*sin(qZ)+RZIXY*sin(phi)*cos(qZ))+sin(theta)*cos(phi)*(RYIXY*sin(qY)*cos(phi)-CIYY*  ...
sin(phi)-CIYZ*cos(phi)-RYIYY*sin(phi)-2*mR*RCMX*RCMY*cos(phi)-mR*RCMX*RCMZ*cos(phi)-RYIYZ*cos(phi)*cos(qY))+cos(theta)*(CIXY*sin(  ...
phi)+CIXZ*cos(phi)+RXIXY*sin(phi+qX)+RXIXZ*cos(phi+qX)+mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi))-  ...
mR*RCMZ*(RCMX*sin(phi)-RCMY*cos(phi)))-sin(theta)*cos(phi+qX)*(RXIYY*sin(phi+qX)+RXIYZ*cos(phi+qX))-(sin(qZ)*cos(theta)+sin(  ...
theta)*cos(phi)*cos(qZ))*(RZIYZ*cos(phi)+RZIXY*sin(phi)*sin(qZ)+RZIYY*sin(phi)*cos(qZ))-(sin(qY)*cos(theta)+sin(phi)*sin(theta)*cos(  ...
qY))*(RYIXZ*sin(qY)*cos(phi)-RYIYZ*sin(phi)-RYIZZ*cos(phi)*cos(qY))-(cos(qY)*cos(theta)-sin(phi)*sin(qY)*sin(theta))*(RYIXX*sin(qY)*  ...
cos(phi)-RYIXY*sin(phi)-RYIXZ*cos(phi)*cos(qY))-sin(phi)*sin(theta)*(mR*RCMX^2*cos(phi)-CIYZ*sin(phi)-CIZZ*cos(phi)-RZIZZ*cos(phi)-  ...
2*mR*RCMX*RCMY*sin(phi)-RZIXZ*sin(phi)*sin(qZ)-RZIYZ*sin(phi)*cos(qZ)-mR*RCMZ*(RCMX*sin(phi)+RCMZ*cos(phi)))));

sys = transpose( SetMatrixOfDerivativesPriorToIntegrationStep );
end



%===========================================================================
function VAR = SetMatrixFromNamedQuantities
%===========================================================================
VAR = zeros( 1, 4 );
VAR(1) = phi;
VAR(2) = theta;
VAR(3) = phiDt;
VAR(4) = thetaDt;
end


%===========================================================================
function SetNamedQuantitiesFromMatrix( VAR )
%===========================================================================
phi = VAR(1);
theta = VAR(2);
phiDt = VAR(3);
thetaDt = VAR(4);
end


%===========================================================================
function VARp = SetMatrixOfDerivativesPriorToIntegrationStep
%===========================================================================
VARp = zeros( 1, 4 );
VARp(1) = phiDt;
VARp(2) = thetaDt;
VARp(3) = phiDDt;
VARp(4) = thetaDDt;
end



%===========================================================================
function Output = mdlOutputs( t, VAR, uSimulink )
%===========================================================================
Output = zeros( 1, 5 );
Output(1) = t;
Output(2) = phi;
Output(3) = theta;
Output(4) = phiDt;
Output(5) = thetaDt;
end


%===========================================================================
function OutputToScreenOrFile( Output, shouldPrintToScreen, shouldPrintToFile )
%===========================================================================
persistent FileIdentifier hasHeaderInformationBeenWritten;

if( isempty(Output) ),
   if( ~isempty(FileIdentifier) ),
      fclose( FileIdentifier(1) );
      clear FileIdentifier;
      fprintf( 1, '\n Output is in the file cube.1\n' );
      fprintf( 1, '\n Note: To automate plotting, issue the command OutputPlot in MotionGenesis.\n' );
      fprintf( 1, '\n To load and plot columns 1 and 2 with a solid line and columns 1 and 3 with a dashed line, enter:\n' );
      fprintf( 1, '    someName = load( ''cube.1'' );\n' );
      fprintf( 1, '    plot( someName(:,1), someName(:,2), ''-'', someName(:,1), someName(:,3), ''--'' )\n\n' );
   end
   clear hasHeaderInformationBeenWritten;
   return;
end

if( isempty(hasHeaderInformationBeenWritten) ),
   if( shouldPrintToScreen ),
      fprintf( 1,                '%%       t             phi           theta          phi''          theta''\n' );
      fprintf( 1,                '%%   (second)        (UNITS)        (UNITS)        (UNITS)        (UNITS)\n\n' );
   end
   if( shouldPrintToFile && isempty(FileIdentifier) ),
      FileIdentifier(1) = fopen('cube.1', 'wt');   if( FileIdentifier(1) == -1 ), error('Error: unable to open file cube.1'); end
      fprintf(FileIdentifier(1), '%% FILE: cube.1\n%%\n' );
      fprintf(FileIdentifier(1), '%%       t             phi           theta          phi''          theta''\n' );
      fprintf(FileIdentifier(1), '%%   (second)        (UNITS)        (UNITS)        (UNITS)        (UNITS)\n\n' );
   end
   hasHeaderInformationBeenWritten = 1;
end

if( shouldPrintToScreen ), WriteNumericalData( 1,                 Output(1:5) );  end
if( shouldPrintToFile ),   WriteNumericalData( FileIdentifier(1), Output(1:5) );  end
end


%===========================================================================
function WriteNumericalData( fileIdentifier, Output )
%===========================================================================
numberOfOutputQuantities = length( Output );
if( numberOfOutputQuantities > 0 ),
   for( i = 1 : numberOfOutputQuantities ),
      fprintf( fileIdentifier, ' %- 14.6E', Output(i) );
   end
   fprintf( fileIdentifier, '\n' );
end
end



%===========================================================================
function [functionsToEvaluateForEvent, eventTerminatesIntegration1Otherwise0ToContinue, eventDirection_AscendingIs1_CrossingIs0_DescendingIsNegative1] = EventDetection( t, VAR, uSimulink )
%===========================================================================
% Detects when designated functions are zero or cross zero with positive or negative slope.
% Step 1: Uncomment call to mdlDerivatives and mdlOutputs.
% Step 2: Change functionsToEvaluateForEvent,                      e.g., change  []  to  [t - 5.67]  to stop at t = 5.67.
% Step 3: Change eventTerminatesIntegration1Otherwise0ToContinue,  e.g., change  []  to  [1]  to stop integrating.
% Step 4: Change eventDirection_AscendingIs1_CrossingIs0_DescendingIsNegative1,  e.g., change  []  to  [1].
% Step 5: Possibly modify function EventDetectedByIntegrator (if eventTerminatesIntegration1Otherwise0ToContinue is 0).
%---------------------------------------------------------------------------
% mdlDerivatives( t, VAR, uSimulink );        % UNCOMMENT FOR EVENT HANDLING
% mdlOutputs(     t, VAR, uSimulink );        % UNCOMMENT FOR EVENT HANDLING
functionsToEvaluateForEvent = [];
eventTerminatesIntegration1Otherwise0ToContinue = [];
eventDirection_AscendingIs1_CrossingIs0_DescendingIsNegative1 = [];
eventDetectedByIntegratorTerminate1OrContinue0 = eventTerminatesIntegration1Otherwise0ToContinue;
end


%===========================================================================
function [isIntegrationFinished, VAR] = EventDetectedByIntegrator( t, VAR, nIndexOfEvents )
%===========================================================================
isIntegrationFinished = eventDetectedByIntegratorTerminate1OrContinue0( nIndexOfEvents );
if( ~isIntegrationFinished ),
   SetNamedQuantitiesFromMatrix( VAR );
%  Put code here to modify how integration continues.
   VAR = SetMatrixFromNamedQuantities;
end
end



%===========================================================================
function [t,VAR,Output] = IntegrateForwardOrBackward( tInitial, tFinal, tStep, absError, relError, VAR, printIntScreen, printIntFile )
%===========================================================================
OdeMatlabOptions = odeset( 'RelTol',relError, 'AbsTol',absError, 'MaxStep',tStep, 'Events',@EventDetection );
t = tInitial;                 epsilonT = 0.001*tStep;                   tFinalMinusEpsilonT = tFinal - epsilonT;
printCounterScreen = 0;       integrateForward = tFinal >= tInitial;    tAtEndOfIntegrationStep = t + tStep;
printCounterFile   = 0;       isIntegrationFinished = 0;
mdlDerivatives( t, VAR, 0 );
while 1,
   if( (integrateForward && t >= tFinalMinusEpsilonT) || (~integrateForward && t <= tFinalMinusEpsilonT) ), isIntegrationFinished = 1;  end
   shouldPrintToScreen = printIntScreen && ( isIntegrationFinished || printCounterScreen <= 0.01 );
   shouldPrintToFile   = printIntFile   && ( isIntegrationFinished || printCounterFile   <= 0.01 );
   if( isIntegrationFinished || shouldPrintToScreen || shouldPrintToFile ),
      Output = mdlOutputs( t, VAR, 0 );
      OutputToScreenOrFile( Output, shouldPrintToScreen, shouldPrintToFile );
      if( isIntegrationFinished ), break;  end
      if( shouldPrintToScreen ), printCounterScreen = printIntScreen;  end
      if( shouldPrintToFile ),   printCounterFile   = printIntFile;    end
   end
   [TimeOdeArray, VarOdeArray, timeEventOccurredInIntegrationStep, nStatesArraysAtEvent, nIndexOfEvents] = ode45( @mdlDerivatives, [t tAtEndOfIntegrationStep], VAR, OdeMatlabOptions, 0 );
   if( isempty(timeEventOccurredInIntegrationStep) ),
      lastIndex = length( TimeOdeArray );
      t = TimeOdeArray( lastIndex );
      VAR = VarOdeArray( lastIndex, : );
      printCounterScreen = printCounterScreen - 1;
      printCounterFile   = printCounterFile   - 1;
      if( abs(tAtEndOfIntegrationStep - t) >= abs(epsilonT) ), warning('numerical integration failed'); break;  end
      tAtEndOfIntegrationStep = t + tStep;
      if( (integrateForward && tAtEndOfIntegrationStep > tFinal) || (~integrateForward && tAtEndOfIntegrationStep < tFinal) ) tAtEndOfIntegrationStep = tFinal;  end
   else
      t = timeEventOccurredInIntegrationStep( 1 );    % time  at firstEvent = 1 during this integration step.
      VAR = nStatesArraysAtEvent( 1, : );             % state at firstEvent = 1 during this integration step.
      printCounterScreen = 0;
      printCounterFile   = 0;
      [isIntegrationFinished, VAR] = EventDetectedByIntegrator( t, VAR, nIndexOfEvents(1) );
   end
end
end


%=============================
end    % End of function cube
%=============================
