function [t,VAR,Output] = cube
%===========================================================================
% File: cube.m created Nov 12 2025 by MotionGenesis 6.5.
% Portions copyright (c) 2009-2025 Motion Genesis LLC.  Rights reserved.
% MotionGenesis Student Licensee: Charlie Lambert. (until September 2028).
% This MotionGenesis Student license is granted the right to use this code
% only until September 2028, only for legal student-academic (non-professional) purposes,
% and limited to their coursework completion at their accredited school.
% All use of this code is specifically limited to this student licensee.
% No rights are extended for other purposes or to anyone but the licensee.
% This copyright notice must appear in all uses of this code.
%===========================================================================
% The software is provided "as is", without warranty of any kind, express or    
% implied, including but not limited to the warranties of merchantability or    
% fitness for a particular purpose. In no event shall the authors, contributors,
% or copyright holders be liable for any claim, damages or other liability,     
% whether in an action of contract, tort, or otherwise, arising from, out of, or
% in connection with the software or the use or other dealings in the software. 
%===========================================================================
eventDetectedByIntegratorTerminate1OrContinue0 = [];
qX=0; qY=0; qZ=0; qXDt=0; qYDt=0; qZDt=0; qXDDt=0; qYDDt=0; qZDDt=0;
phiDDt=0; thetaDDt=0;


%-------------------------------+--------------------------+-------------------+-----------------
% Quantity                      | Value                    | Units             | Description
%-------------------------------|--------------------------|-------------------|-----------------
CCMX                            =  0.072113;               % m                   Constant
CCMY                            =  0.071399;               % m                   Constant
CCMZ                            =  0.071467;               % m                   Constant
CIXX                            =  0.011496398;            % kg*m^2              Constant
CIXY                            = -0.004360713;            % kg*m^2              Constant
CIXZ                            =  0.004366281;            % kg*m^2              Constant
CIYY                            =  0.011603443;            % kg*m^2              Constant
CIYZ                            =  0.004314224;            % kg*m^2              Constant
CIZZ                            =  0.011600232;            % kg*m^2              Constant
g                               =  9.81;                   % m/s^2               Constant
mC                              =  0.84392696;             % kg                  Constant
mR                              =  0.04711499;             % kg                  Constant
RCMX                            =  0.076;                  % m                   Constant
RCMY                            =  0.076;                  % m                   Constant
RCMZ                            =  0.007789;               % m                   Constant
RXIXX                           =  0.000173232;            % kg*m^2              Constant
RXIYY                           =  0.000086943;            % kg*m^2              Constant
RXIYZ                           = -0.000000127;            % kg*m^2              Constant
RXIZZ                           =  0.000087197;            % kg*m^2              Constant
RYIXX                           =  0.000087197;            % kg*m^2              Constant
RYIXZ                           = -0.000000127;            % kg*m^2              Constant
RYIYY                           =  0.000173232;            % kg*m^2              Constant
RYIZZ                           =  0.000086943;            % kg*m^2              Constant
RZIXX                           =  0.000087197;            % kg*m^2              Constant
RZIXY                           =  0.000000127;            % kg*m^2              Constant
RZIYY                           =  0.000086943;            % kg*m^2              Constant
RZIZZ                           =  0.000173232;            % kg*m^2              Constant

phi                             =  0.0;                    % UNITS               Initial Value
theta                           =  0.0;                    % UNITS               Initial Value
phiDt                           =  0.0;                    % UNITS               Initial Value
thetaDt                         =  0.0;                    % UNITS               Initial Value

tInitial                        =  0.0;                    % second              Initial Time
tFinal                          =  10.0;                   % second              Final Time
tStep                           =  0.05;                   % second              Integration Step
printIntScreen                  =  1;                      % 0 or +integer       0 is NO screen output
printIntFile                    =  1;                      % 0 or +integer       0 is NO file   output
absError                        =  1.0E-05;                %                     Absolute Error
relError                        =  1.0E-08;                %                     Relative Error
%-------------------------------+--------------------------+-------------------+-----------------


VAR = SetMatrixFromNamedQuantities;
[t,VAR,Output] = IntegrateForwardOrBackward( tInitial, tFinal, tStep, absError, relError, VAR, printIntScreen, printIntFile );
OutputToScreenOrFile( [], 0, 0 );   % Close output files.


%===========================================================================
function sys = mdlDerivatives( t, VAR, uSimulink )
%===========================================================================
SetNamedQuantitiesFromMatrix( VAR );

% Quantities to be specified (not assigned in MotionGenesis).
qX = 0;
qY = 0;
qZ = 0;
qXDt = 0;
qYDt = 0;
qZDt = 0;
qXDDt = 0;
qYDDt = 0;
qZDDt = 0;

thetaDDt = -((cos(theta)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))+sin(phi)*cos(theta)*(CIXY*cos(  ...
theta)-CIYY*sin(theta)-RYIYY*sin(theta)-mR*RCMX*RCMY*cos(theta)-mR*RCMX*RCMZ*cos(theta)-mR*RCMY*RCMZ*cos(theta))+cos(phi)*(CIXZ*cos(  ...
theta)+mR*RCMX^2*cos(theta)+mR*RCMX*(RCMY*cos(theta)-RCMZ*sin(theta))-CIYZ*sin(theta)-mR*RCMY*(2*RCMX*sin(theta)-RCMZ*cos(theta)))-  ...
sin(theta)*(RXIYY*cos(qX)-RXIYZ*sin(qX))*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))-cos(theta)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(  ...
sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))-sin(theta)*(RXIYZ*cos(qX)-RXIZZ*sin(qX))*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(  ...
theta))-sin(phi)*sin(theta)*(CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-mR*RCMX*RCMY*sin(theta)-mR*RCMX*RCMZ*sin(theta)-mR*  ...
RCMY*RCMZ*sin(theta))-sin(phi)*sin(qZ+theta)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-  ...
RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))-sin(phi)*cos(qZ+theta)*(RZIYY*(sin(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(  ...
phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))*(  ...
g*((mC*CCMY+mR*RCMY+2*mR*RCMX)*cos(phi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi)*cos(theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(  ...
phi)*sin(theta))+sin(qX)*sin(theta)*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(theta)*  ...
cos(qX)*phiDt*qXDt+RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*  ...
cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(  ...
phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-(qXDt+cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+  ...
sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+sin(theta)*cos(qX)*(RXIYY*cos(  ...
qX)*cos(theta)*phiDt*thetaDt+RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*  ...
thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(theta)*  ...
phiDt*thetaDt-RXIYZ*sin(theta)*cos(qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*  ...
cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*  ...
thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+cos(qY)*cos(theta)*(RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-  ...
RYIXX*sin(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(theta)*phiDt*thetaDt-RYIXX*thetaDt*(  ...
cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(  ...
phi)*cos(qY)*phiDt)-RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(  ...
theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXZ*cos(qY)*cos(  ...
theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))*thetaDt))+(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-  ...
cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*sin(phi)*  ...
sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(  ...
phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+  ...
cos(phi)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+  ...
theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))+sin(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*thetaDt+CIYZ*  ...
sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+mR*RCMX*  ...
thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(  ...
qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*  ...
thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*cos(theta)*  ...
phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-RCMZ*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+sin(phi)*sin(  ...
qY)*sin(theta))*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*  ...
sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*cos(theta)*  ...
phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+RXIXX*sin(phi)*  ...
sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(3*RCMX*sin(  ...
theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(  ...
phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*thetaDt+sin(  ...
phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*phiDt-  ...
sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(qY)*cos(theta)*(RYIXZ*sin(qY)*cos(theta)*phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*  ...
phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*  ...
sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)+RYIZZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*  ...
cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*  ...
cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(  ...
theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*  ...
thetaDt))-(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIXY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+  ...
thetaDt)+RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*  ...
qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(  ...
phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-RZIXX*cos(phi)*sin(qZ+theta)*phiDt*  ...
thetaDt-RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-(qZDt+cos(phi)*thetaDt)*(  ...
RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*thetaDt-  ...
RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(  ...
1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*  ...
phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(  ...
theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))))-cos(theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+  ...
RXIXX*sin(theta)*phiDt*thetaDt+CIXY*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*phiDt-RCMX*(3*RCMX*sin(phi)*cos(  ...
theta)*thetaDt+RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*phiDt-RCMZ*(RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(sin(phi)+3*sin(  ...
theta))*phiDt-RCMY*(RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(  ...
theta)*cos(phi)*phiDt)))-CIXX*sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*cos(theta)*thetaDt^2-  ...
RXIXX*sin(theta)*cos(phi)*phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)*(RXIYY*  ...
sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*  ...
cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt)*(  ...
RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(  ...
cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(  ...
phi)*(RCMX*sin(theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(  ...
theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*  ...
thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*  ...
sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-RXIXX*qXDDt))+(cos(theta)*(2*CIXY*sin(theta)-CIXX*  ...
cos(theta)-RXIXX*cos(theta)-2*mR*RCMX*RCMY*sin(theta)-2*mR*RCMX*RCMZ*sin(theta)-2*mR*RCMY*RCMZ*sin(theta))+sin(theta)^2*(RYIXX*cos(  ...
qY)^2+sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-CIYY-RYIYY-RXIZZ*sin(qX)^2-cos(qX)*(RXIYY*cos(qX)-2*RXIYZ*sin(qX)))-3*mR*RCMX^2-2*mR*RCMY^2-  ...
mR*RCMZ^2-RYIXX*cos(qY)^2-sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))^2-(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*  ...
cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(  ...
qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-2*RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))*((  ...
cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(  ...
theta)*cos(qX)*phiDt*qXDt+RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*  ...
cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*  ...
phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*  ...
phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(  ...
sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))-g*((mC*CCMX+  ...
mR*RCMX+mR*RCMY+mR*RCMZ)*sin(theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*cos(theta))-(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(  ...
RYIXZ*sin(qY)*cos(theta)*phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(  ...
cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(  ...
phi)*cos(qY)*phiDt)+RYIZZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(  ...
theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(  ...
theta)*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(  ...
theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt))-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(  ...
RXIYY*cos(qX)*cos(theta)*phiDt*thetaDt+RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*  ...
cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(  ...
theta)*phiDt*thetaDt-RXIYZ*sin(theta)*cos(qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*  ...
phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(  ...
theta)*thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(  ...
theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*(  ...
RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(  ...
theta)*phiDt*thetaDt-RYIXX*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*  ...
cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)-RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*  ...
cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*  ...
thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*  ...
thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt))-sin(phi)*cos(qZ+theta)*(RZIYY*sin(phi)*sin(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(  ...
theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(  ...
phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+cos(phi)*  ...
thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*  ...
thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-sin(phi)*sin(qZ+theta)*(RZIXY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+  ...
RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*  ...
qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-RZIXX*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-  ...
RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-(qZDt+cos(phi)*thetaDt)*(RZIYY*(sin(  ...
theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(  ...
theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*thetaDt-RZIYY*sin(phi)*cos(  ...
qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(  ...
theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*phiDt*(sin(theta)*  ...
cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*  ...
thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*  ...
qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*  ...
qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-  ...
sin(phi)*cos(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*thetaDt+CIYZ*sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*  ...
phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+mR*RCMX*thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*  ...
phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(  ...
theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*  ...
phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*  ...
sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*cos(theta)*phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*  ...
phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt)*(RYIXX*cos(  ...
qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(  ...
phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*cos(theta)*phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(  ...
theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+RXIXX*sin(phi)*sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(  ...
phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(3*RCMX*sin(theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(  ...
RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*  ...
sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*  ...
sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*thetaDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*  ...
sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(phi)*sin(  ...
theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+RXIXX*sin(theta)*phiDt*thetaDt+CIXY*  ...
sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*phiDt-RCMX*(3*RCMX*sin(phi)*cos(theta)*thetaDt+RCMZ*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*phiDt-RCMZ*(RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(sin(phi)+3*sin(theta))*phiDt-RCMY*(RCMX*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt)))-CIXX*  ...
sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*cos(theta)*thetaDt^2-RXIXX*sin(theta)*cos(phi)*  ...
phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-  ...
RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(  ...
qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt)*(RXIYZ*sin(theta)*cos(  ...
qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(  ...
phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(phi)*(RCMX*sin(  ...
theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(theta)*  ...
thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*  ...
thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*  ...
sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-RXIXX*qXDDt)-cos(phi)*(CIXZ*sin(theta)*phiDt*  ...
thetaDt+CIYZ*cos(theta)*phiDt*thetaDt+CIZZ*sin(phi)*phiDt*thetaDt+RZIZZ*sin(phi)*phiDt*thetaDt+CIYZ*sin(phi)*sin(theta)*thetaDt^2+  ...
mR*thetaDt*(2*RCMY^2*sin(phi)*phiDt+RCMX^2*(sin(theta)*phiDt+2*sin(phi)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*  ...
phiDt))+mR*RCMY*thetaDt*(2*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)+RCMZ*(sin(theta)*phiDt-sin(  ...
phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt))+mR*thetaDt*(RCMX*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(  ...
theta)*cos(phi)*phiDt)+RCMZ*(2*RCMZ*sin(phi)*phiDt+RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMX*RCMZ*(cos(theta)*phiDt+sin(phi)*  ...
sin(theta)*thetaDt)-RYIYY*qYDt-CIXY*cos(theta)*phiDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(  ...
theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)*thetaDt-RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt))-mR*RCMX*(2*RCMY*cos(phi)*thetaDt-RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-3*RCMX*(sin(theta)*phiDt-sin(phi)*  ...
cos(theta)*thetaDt)))+(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)*(CIXY*sin(theta)*phiDt-RXIXX*qXDt-CIXX*cos(theta)*phiDt-CIXZ*  ...
cos(phi)*thetaDt-RXIXX*cos(theta)*phiDt-CIXX*sin(phi)*sin(theta)*thetaDt-CIXY*sin(phi)*cos(theta)*thetaDt-RXIXX*sin(phi)*sin(  ...
theta)*thetaDt-mR*RCMY*(RCMX*cos(phi)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMX*(RCMX*(cos(phi)*  ...
thetaDt+3*cos(theta)*phiDt)+RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*(RCMY*RCMZ*cos(phi)*thetaDt+RCMX*(3*RCMX*sin(  ...
phi)*sin(theta)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))))+(cos(qZ+theta)*phiDt+sin(phi)*sin(qZ+theta)*  ...
thetaDt)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*  ...
thetaDt-RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)+(sin(qZ+theta)*phiDt-sin(phi)*cos(qZ+theta)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(  ...
cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(  ...
phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(  ...
theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(  ...
cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-CIXZ*sin(phi)*cos(theta)*thetaDt^2-CIXZ*sin(theta)*cos(phi)*phiDt*thetaDt-CIYZ*cos(phi)*  ...
cos(theta)*phiDt*thetaDt-RZIZZ*qZDDt)))/((2*mR*RCMY^2+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))^2+RYIXX*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))^2+(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(  ...
theta))+2*RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta)))+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(RYIZZ*(cos(phi)*cos(  ...
qY)+sin(phi)*sin(qY)*sin(theta))-2*RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))+cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+2*  ...
CIXZ*sin(phi)*sin(theta)+2*CIYZ*sin(phi)*cos(theta)+2*mR*RCMX^2*(cos(phi)+sin(phi)*sin(theta))+2*mR*RCMY*sin(phi)*(RCMZ*sin(  ...
theta)+2*RCMX*cos(theta))+2*mR*(RCMX*RCMY*sin(phi)*sin(theta)+RCMZ*(RCMZ*cos(phi)+RCMX*sin(phi)*cos(theta))))+sin(phi)^2*(mR*RCMZ^2+  ...
3*mR*RCMX^2+RZIYY*cos(qZ+theta)^2+sin(qZ+theta)*(RZIXX*sin(qZ+theta)+2*RZIXY*cos(qZ+theta))+cos(theta)*(CIYY*cos(theta)+RYIYY*cos(  ...
theta)-2*mR*RCMX*RCMZ*sin(theta))+sin(theta)*(CIXX*sin(theta)+RXIXX*sin(theta)+2*CIXY*cos(theta)-2*mR*RCMX*RCMY*cos(theta)-2*mR*RCMY*  ...
RCMZ*cos(theta))))*(cos(theta)*(2*CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-2*mR*RCMX*RCMY*sin(theta)-2*mR*RCMX*RCMZ*sin(  ...
theta)-2*mR*RCMY*RCMZ*sin(theta))+sin(theta)^2*(RYIXX*cos(qY)^2+sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-CIYY-RYIYY-RXIZZ*sin(qX)^2-  ...
cos(qX)*(RXIYY*cos(qX)-2*RXIYZ*sin(qX)))-3*mR*RCMX^2-2*mR*RCMY^2-mR*RCMZ^2-RYIXX*cos(qY)^2-sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-  ...
RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))^2-(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(  ...
phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(  ...
theta)^2*(1-cos(phi)))))*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+  ...
cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-2*RZIXY*(sin(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-  ...
cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))-(sin(theta)*cos(qX)*(RXIYZ*cos(phi)*cos(qX)+RXIYY*(sin(qX)*cos(phi)+sin(  ...
phi)*cos(qX)*cos(theta)))+sin(phi)*(RZIXY*sin(qZ+theta)+RZIYY*cos(qZ+theta))*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+  ...
cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))-cos(qY)*cos(theta)*(RYIXZ*cos(phi)*cos(qY)-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))-sin(qX)*sin(  ...
theta)*(RXIYZ*(sin(qX)*cos(phi)+2*sin(phi)*cos(qX)*cos(theta))+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta)))-sin(qY)*cos(  ...
theta)*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-RYIXZ*(sin(qY)*cos(phi)-2*sin(phi)*sin(theta)*cos(qY)))-cos(theta)*(  ...
CIXZ*cos(phi)+CIXX*sin(phi)*sin(theta)+CIXY*sin(phi)*cos(theta)+RXIXX*sin(phi)*sin(theta)+mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi)*cos(  ...
theta))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))+mR*RCMZ*(RCMY*cos(phi)-RCMX*sin(phi)*cos(theta)))-sin(theta)*(mR*RCMX*RCMZ*  ...
sin(phi)*sin(theta)-CIYZ*cos(phi)-CIXY*sin(phi)*sin(theta)-CIYY*sin(phi)*cos(theta)-RYIYY*sin(phi)*cos(theta)-mR*RCMX*RCMY*(2*cos(  ...
phi)-sin(phi)*sin(theta))-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta)))-sin(phi)*(RZIXX*sin(qZ+theta)+RZIXY*cos(qZ+theta))*(sin(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(  ...
theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))*(cos(theta)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(cos(phi)*cos(qY)+sin(  ...
phi)*sin(qY)*sin(theta))+sin(phi)*cos(theta)*(CIXY*cos(theta)-CIYY*sin(theta)-RYIYY*sin(theta)-mR*RCMX*RCMY*cos(theta)-mR*RCMX*RCMZ*  ...
cos(theta)-mR*RCMY*RCMZ*cos(theta))+cos(phi)*(CIXZ*cos(theta)+mR*RCMX^2*cos(theta)+mR*RCMX*(RCMY*cos(theta)-RCMZ*sin(theta))-CIYZ*  ...
sin(theta)-mR*RCMY*(2*RCMX*sin(theta)-RCMZ*cos(theta)))-sin(theta)*(RXIYY*cos(qX)-RXIYZ*sin(qX))*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*  ...
cos(theta))-cos(theta)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))-sin(theta)*(RXIYZ*cos(qX)-  ...
RXIZZ*sin(qX))*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))-sin(phi)*sin(theta)*(CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(  ...
theta)-mR*RCMX*RCMY*sin(theta)-mR*RCMX*RCMZ*sin(theta)-mR*RCMY*RCMZ*sin(theta))-sin(phi)*sin(qZ+theta)*(RZIXY*(sin(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(  ...
phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))-  ...
sin(phi)*cos(qZ+theta)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+  ...
cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXY*(sin(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-  ...
cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))));
phiDDt = ((2*mR*RCMY^2+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))^2+RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))^2+(  ...
sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))+2*RXIYZ*(cos(phi)*cos(qX)-sin(  ...
phi)*sin(qX)*cos(theta)))+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-2*  ...
RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))+cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+2*CIXZ*sin(phi)*sin(theta)+2*CIYZ*sin(  ...
phi)*cos(theta)+2*mR*RCMX^2*(cos(phi)+sin(phi)*sin(theta))+2*mR*RCMY*sin(phi)*(RCMZ*sin(theta)+2*RCMX*cos(theta))+2*mR*(RCMX*RCMY*  ...
sin(phi)*sin(theta)+RCMZ*(RCMZ*cos(phi)+RCMX*sin(phi)*cos(theta))))+sin(phi)^2*(mR*RCMZ^2+3*mR*RCMX^2+RZIYY*cos(qZ+theta)^2+sin(qZ+  ...
theta)*(RZIXX*sin(qZ+theta)+2*RZIXY*cos(qZ+theta))+cos(theta)*(CIYY*cos(theta)+RYIYY*cos(theta)-2*mR*RCMX*RCMZ*sin(theta))+sin(  ...
theta)*(CIXX*sin(theta)+RXIXX*sin(theta)+2*CIXY*cos(theta)-2*mR*RCMX*RCMY*cos(theta)-2*mR*RCMY*RCMZ*cos(theta))))*(g*((mC*CCMY+mR*  ...
RCMY+2*mR*RCMX)*cos(phi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi)*cos(theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi)*sin(  ...
theta))+sin(qX)*sin(theta)*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(theta)*cos(qX)*  ...
phiDt*qXDt+RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(  ...
theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*  ...
sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-(qXDt+cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+  ...
sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+sin(theta)*cos(qX)*(RXIYY*cos(  ...
qX)*cos(theta)*phiDt*thetaDt+RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*  ...
thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(theta)*  ...
phiDt*thetaDt-RXIYZ*sin(theta)*cos(qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*  ...
cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*  ...
thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+cos(qY)*cos(theta)*(RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-  ...
RYIXX*sin(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(theta)*phiDt*thetaDt-RYIXX*thetaDt*(  ...
cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(  ...
phi)*cos(qY)*phiDt)-RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(  ...
theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXZ*cos(qY)*cos(  ...
theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))*thetaDt))+(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-  ...
cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*sin(phi)*  ...
sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(  ...
phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+  ...
cos(phi)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+  ...
theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))+sin(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*thetaDt+CIYZ*  ...
sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+mR*RCMX*  ...
thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(  ...
qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*  ...
thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*cos(theta)*  ...
phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-RCMZ*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+sin(phi)*sin(  ...
qY)*sin(theta))*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*  ...
sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*cos(theta)*  ...
phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+RXIXX*sin(phi)*  ...
sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(3*RCMX*sin(  ...
theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(  ...
phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*thetaDt+sin(  ...
phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*phiDt-  ...
sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(qY)*cos(theta)*(RYIXZ*sin(qY)*cos(theta)*phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*  ...
phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*  ...
sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)+RYIZZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*  ...
cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*  ...
cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(  ...
theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*  ...
thetaDt))-(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIXY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+  ...
thetaDt)+RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*  ...
qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(  ...
phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-RZIXX*cos(phi)*sin(qZ+theta)*phiDt*  ...
thetaDt-RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-(qZDt+cos(phi)*thetaDt)*(  ...
RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*thetaDt-  ...
RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(  ...
1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*  ...
phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(  ...
theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))))-cos(theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+  ...
RXIXX*sin(theta)*phiDt*thetaDt+CIXY*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*phiDt-RCMX*(3*RCMX*sin(phi)*cos(  ...
theta)*thetaDt+RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*phiDt-RCMZ*(RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(sin(phi)+3*sin(  ...
theta))*phiDt-RCMY*(RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(  ...
theta)*cos(phi)*phiDt)))-CIXX*sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*cos(theta)*thetaDt^2-  ...
RXIXX*sin(theta)*cos(phi)*phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)*(RXIYY*  ...
sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*  ...
cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt)*(  ...
RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(  ...
cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(  ...
phi)*(RCMX*sin(theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(  ...
theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*  ...
thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*  ...
sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-RXIXX*qXDDt))+(sin(theta)*cos(qX)*(RXIYZ*cos(phi)*  ...
cos(qX)+RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta)))+sin(phi)*(RZIXY*sin(qZ+theta)+RZIYY*cos(qZ+theta))*(sin(theta)*(sin(  ...
qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-  ...
cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-cos(qY)*cos(theta)*(RYIXZ*cos(phi)*cos(qY)-RYIXX*(sin(qY)*cos(phi)-sin(phi)*  ...
sin(theta)*cos(qY)))-sin(qX)*sin(theta)*(RXIYZ*(sin(qX)*cos(phi)+2*sin(phi)*cos(qX)*cos(theta))+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*  ...
sin(qX)*cos(theta)))-sin(qY)*cos(theta)*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-RYIXZ*(sin(qY)*cos(phi)-2*sin(phi)*  ...
sin(theta)*cos(qY)))-cos(theta)*(CIXZ*cos(phi)+CIXX*sin(phi)*sin(theta)+CIXY*sin(phi)*cos(theta)+RXIXX*sin(phi)*sin(theta)+mR*RCMX*(  ...
RCMX*cos(phi)-RCMY*sin(phi)*cos(theta))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))+mR*RCMZ*(RCMY*cos(phi)-RCMX*sin(phi)*cos(  ...
theta)))-sin(theta)*(mR*RCMX*RCMZ*sin(phi)*sin(theta)-CIYZ*cos(phi)-CIXY*sin(phi)*sin(theta)-CIYY*sin(phi)*cos(theta)-RYIYY*sin(phi)*  ...
cos(theta)-mR*RCMX*RCMY*(2*cos(phi)-sin(phi)*sin(theta))-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta)))-sin(phi)*(RZIXX*sin(qZ+  ...
theta)+RZIXY*cos(qZ+theta))*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-  ...
cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))*((cos(phi)*cos(qX)-sin(phi)*  ...
sin(qX)*cos(theta))*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(theta)*cos(qX)*phiDt*qXDt+  ...
RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-  ...
sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*  ...
cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-(qXDt+cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*  ...
cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))-g*((mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(  ...
theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*cos(theta))-(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(RYIXZ*sin(qY)*cos(theta)*  ...
phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(  ...
phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)+RYIZZ*  ...
thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*  ...
sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXX*cos(qY)*  ...
cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))*thetaDt))-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*cos(qX)*cos(theta)*phiDt*thetaDt+  ...
RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-  ...
cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*sin(theta)*cos(  ...
qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(  ...
theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYZ*sin(theta)*cos(qX)*  ...
phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*  ...
sin(qX)*cos(theta))*thetaDt))-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*(RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(qY)*cos(  ...
theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(theta)*phiDt*thetaDt-RYIXX*thetaDt*(cos(phi)*cos(qY)*qYDt+  ...
sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)-  ...
RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-  ...
sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(  ...
qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(  ...
qY))*thetaDt))-sin(phi)*cos(qZ+theta)*(RZIYY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(  ...
qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(  ...
qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(  ...
theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+cos(phi)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+  ...
cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(  ...
qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-  ...
cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*  ...
phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*  ...
thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(  ...
phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*  ...
thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-  ...
cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-sin(phi)*sin(qZ+theta)*(RZIXY*sin(phi)*  ...
sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(  ...
phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-  ...
RZIXX*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+  ...
thetaDt)-(qZDt+cos(phi)*thetaDt)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-  ...
cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(  ...
phi)*sin(qZ+theta)*thetaDt-RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))*phiDt)-RZIXY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-sin(phi)*cos(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*  ...
thetaDt+CIYZ*sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+  ...
mR*RCMX*thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(  ...
theta)*cos(qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*  ...
sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*  ...
cos(theta)*phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt)-RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+  ...
sin(phi)*sin(qY)*sin(theta))*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(  ...
phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*  ...
cos(theta)*phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+  ...
RXIXX*sin(phi)*sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(  ...
3*RCMX*sin(theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-  ...
RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*  ...
thetaDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*  ...
cos(theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*  ...
phiDt-sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(phi)*sin(theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*  ...
thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+RXIXX*sin(theta)*phiDt*thetaDt+CIXY*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*  ...
phiDt-RCMX*(3*RCMX*sin(phi)*cos(theta)*thetaDt+RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*  ...
phiDt-RCMZ*(RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(  ...
sin(phi)+3*sin(theta))*phiDt-RCMY*(RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt-sin(theta)*cos(phi)*phiDt)))-CIXX*sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*  ...
cos(theta)*thetaDt^2-RXIXX*sin(theta)*cos(phi)*phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(  ...
theta))*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(  ...
theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*  ...
cos(qX)*cos(theta))*thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(  ...
qX)*cos(theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+  ...
RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(phi)*(RCMX*sin(theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*  ...
sin(theta)*thetaDt-CIYY*sin(phi)*cos(theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(  ...
theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*  ...
thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-  ...
RXIXX*qXDDt)-cos(phi)*(CIXZ*sin(theta)*phiDt*thetaDt+CIYZ*cos(theta)*phiDt*thetaDt+CIZZ*sin(phi)*phiDt*thetaDt+RZIZZ*sin(phi)*  ...
phiDt*thetaDt+CIYZ*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(2*RCMY^2*sin(phi)*phiDt+RCMX^2*(sin(theta)*phiDt+2*sin(phi)*phiDt-sin(  ...
phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt))+mR*RCMY*thetaDt*(2*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*  ...
cos(theta)*phiDt)+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt))+mR*thetaDt*(RCMX*RCMY*(sin(  ...
theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt)+RCMZ*(2*RCMZ*sin(phi)*phiDt+RCMX*(cos(theta)*phiDt+sin(phi)*sin(  ...
theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYY*sin(theta)*phiDt+RYIYY*sin(  ...
theta)*phiDt+mR*RCMX*RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RYIYY*qYDt-CIXY*cos(theta)*phiDt-CIYZ*cos(phi)*thetaDt-CIXY*  ...
sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)*thetaDt-RCMY*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt))-mR*RCMX*(2*RCMY*cos(phi)*thetaDt-RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)-3*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)*(CIXY*sin(theta)*  ...
phiDt-RXIXX*qXDt-CIXX*cos(theta)*phiDt-CIXZ*cos(phi)*thetaDt-RXIXX*cos(theta)*phiDt-CIXX*sin(phi)*sin(theta)*thetaDt-CIXY*sin(phi)*  ...
cos(theta)*thetaDt-RXIXX*sin(phi)*sin(theta)*thetaDt-mR*RCMY*(RCMX*cos(phi)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))-mR*RCMX*(RCMX*(cos(phi)*thetaDt+3*cos(theta)*phiDt)+RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*(RCMY*RCMZ*  ...
cos(phi)*thetaDt+RCMX*(3*RCMX*sin(phi)*sin(theta)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))))+(cos(qZ+theta)*  ...
phiDt+sin(phi)*sin(qZ+theta)*thetaDt)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(  ...
1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(  ...
phi)*sin(qZ+theta)*thetaDt-RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))*phiDt)+(sin(qZ+theta)*phiDt-sin(phi)*cos(qZ+theta)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(  ...
phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(  ...
theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-  ...
cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-CIXZ*sin(phi)*cos(theta)*thetaDt^2-CIXZ*sin(theta)*cos(phi)*  ...
phiDt*thetaDt-CIYZ*cos(phi)*cos(theta)*phiDt*thetaDt-RZIZZ*qZDDt)))/((2*mR*RCMY^2+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(  ...
theta))^2+RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))^2+(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*(sin(qX)*cos(  ...
phi)+sin(phi)*cos(qX)*cos(theta))+2*RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta)))+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(  ...
theta))*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-2*RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))+cos(phi)*(CIZZ*  ...
cos(phi)+RZIZZ*cos(phi)+2*CIXZ*sin(phi)*sin(theta)+2*CIYZ*sin(phi)*cos(theta)+2*mR*RCMX^2*(cos(phi)+sin(phi)*sin(theta))+2*mR*RCMY*  ...
sin(phi)*(RCMZ*sin(theta)+2*RCMX*cos(theta))+2*mR*(RCMX*RCMY*sin(phi)*sin(theta)+RCMZ*(RCMZ*cos(phi)+RCMX*sin(phi)*cos(theta))))+  ...
sin(phi)^2*(mR*RCMZ^2+3*mR*RCMX^2+RZIYY*cos(qZ+theta)^2+sin(qZ+theta)*(RZIXX*sin(qZ+theta)+2*RZIXY*cos(qZ+theta))+cos(theta)*(CIYY*  ...
cos(theta)+RYIYY*cos(theta)-2*mR*RCMX*RCMZ*sin(theta))+sin(theta)*(CIXX*sin(theta)+RXIXX*sin(theta)+2*CIXY*cos(theta)-2*mR*RCMX*RCMY*  ...
cos(theta)-2*mR*RCMY*RCMZ*cos(theta))))*(cos(theta)*(2*CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-2*mR*RCMX*RCMY*sin(theta)-  ...
2*mR*RCMX*RCMZ*sin(theta)-2*mR*RCMY*RCMZ*sin(theta))+sin(theta)^2*(RYIXX*cos(qY)^2+sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-CIYY-  ...
RYIYY-RXIZZ*sin(qX)^2-cos(qX)*(RXIYY*cos(qX)-2*RXIYZ*sin(qX)))-3*mR*RCMX^2-2*mR*RCMY^2-mR*RCMZ^2-RYIXX*cos(qY)^2-sin(qY)*(RYIZZ*sin(  ...
qY)+2*RYIXZ*cos(qY))-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-  ...
cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))^2-(sin(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+  ...
sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-2*  ...
RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))-(sin(theta)*cos(qX)*(RXIYZ*cos(phi)*cos(qX)+  ...
RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta)))+sin(phi)*(RZIXY*sin(qZ+theta)+RZIYY*cos(qZ+theta))*(sin(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+  ...
sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-cos(qY)*cos(theta)*(RYIXZ*cos(phi)*cos(qY)-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(  ...
theta)*cos(qY)))-sin(qX)*sin(theta)*(RXIYZ*(sin(qX)*cos(phi)+2*sin(phi)*cos(qX)*cos(theta))+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(  ...
qX)*cos(theta)))-sin(qY)*cos(theta)*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-RYIXZ*(sin(qY)*cos(phi)-2*sin(phi)*sin(  ...
theta)*cos(qY)))-cos(theta)*(CIXZ*cos(phi)+CIXX*sin(phi)*sin(theta)+CIXY*sin(phi)*cos(theta)+RXIXX*sin(phi)*sin(theta)+mR*RCMX*(RCMX*  ...
cos(phi)-RCMY*sin(phi)*cos(theta))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))+mR*RCMZ*(RCMY*cos(phi)-RCMX*sin(phi)*cos(  ...
theta)))-sin(theta)*(mR*RCMX*RCMZ*sin(phi)*sin(theta)-CIYZ*cos(phi)-CIXY*sin(phi)*sin(theta)-CIYY*sin(phi)*cos(theta)-RYIYY*sin(phi)*  ...
cos(theta)-mR*RCMX*RCMY*(2*cos(phi)-sin(phi)*sin(theta))-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta)))-sin(phi)*(RZIXX*sin(qZ+  ...
theta)+RZIXY*cos(qZ+theta))*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-  ...
cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))*(cos(theta)*(RYIXZ*cos(qY)+  ...
RYIZZ*sin(qY))*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))+sin(phi)*cos(theta)*(CIXY*cos(theta)-CIYY*sin(theta)-RYIYY*sin(  ...
theta)-mR*RCMX*RCMY*cos(theta)-mR*RCMX*RCMZ*cos(theta)-mR*RCMY*RCMZ*cos(theta))+cos(phi)*(CIXZ*cos(theta)+mR*RCMX^2*cos(theta)+mR*  ...
RCMX*(RCMY*cos(theta)-RCMZ*sin(theta))-CIYZ*sin(theta)-mR*RCMY*(2*RCMX*sin(theta)-RCMZ*cos(theta)))-sin(theta)*(RXIYY*cos(qX)-  ...
RXIYZ*sin(qX))*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))-cos(theta)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(sin(qY)*cos(phi)-sin(phi)*  ...
sin(theta)*cos(qY))-sin(theta)*(RXIYZ*cos(qX)-RXIZZ*sin(qX))*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))-sin(phi)*sin(theta)*(  ...
CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-mR*RCMX*RCMY*sin(theta)-mR*RCMX*RCMZ*sin(theta)-mR*RCMY*RCMZ*sin(theta))-sin(phi)*  ...
sin(qZ+theta)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXX*(sin(theta)*(sin(theta)*cos(  ...
qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-  ...
cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))-sin(phi)*cos(qZ+theta)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+  ...
cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(  ...
theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))));

sys = transpose( SetMatrixOfDerivativesPriorToIntegrationStep );
end



%===========================================================================
function VAR = SetMatrixFromNamedQuantities
%===========================================================================
VAR = zeros( 1, 4 );
VAR(1) = phi;
VAR(2) = theta;
VAR(3) = phiDt;
VAR(4) = thetaDt;
end


%===========================================================================
function SetNamedQuantitiesFromMatrix( VAR )
%===========================================================================
phi = VAR(1);
theta = VAR(2);
phiDt = VAR(3);
thetaDt = VAR(4);
end


%===========================================================================
function VARp = SetMatrixOfDerivativesPriorToIntegrationStep
%===========================================================================
VARp = zeros( 1, 4 );
VARp(1) = phiDt;
VARp(2) = thetaDt;
VARp(3) = phiDDt;
VARp(4) = thetaDDt;
end



%===========================================================================
function Output = mdlOutputs( t, VAR, uSimulink )
%===========================================================================
Output = zeros( 1, 5 );
Output(1) = t;
Output(2) = phi;
Output(3) = theta;
Output(4) = phiDt;
Output(5) = thetaDt;
end


%===========================================================================
function OutputToScreenOrFile( Output, shouldPrintToScreen, shouldPrintToFile )
%===========================================================================
persistent FileIdentifier hasHeaderInformationBeenWritten;

if( isempty(Output) ),
   if( ~isempty(FileIdentifier) ),
      fclose( FileIdentifier(1) );
      clear FileIdentifier;
      fprintf( 1, '\n Output is in the file cube.1\n' );
      fprintf( 1, '\n Note: To automate plotting, issue the command OutputPlot in MotionGenesis.\n' );
      fprintf( 1, '\n To load and plot columns 1 and 2 with a solid line and columns 1 and 3 with a dashed line, enter:\n' );
      fprintf( 1, '    someName = load( ''cube.1'' );\n' );
      fprintf( 1, '    plot( someName(:,1), someName(:,2), ''-'', someName(:,1), someName(:,3), ''--'' )\n\n' );
   end
   clear hasHeaderInformationBeenWritten;
   return;
end

if( isempty(hasHeaderInformationBeenWritten) ),
   if( shouldPrintToScreen ),
      fprintf( 1,                '%%       t             phi           theta          phi''          theta''\n' );
      fprintf( 1,                '%%   (second)        (UNITS)        (UNITS)        (UNITS)        (UNITS)\n\n' );
   end
   if( shouldPrintToFile && isempty(FileIdentifier) ),
      FileIdentifier(1) = fopen('cube.1', 'wt');   if( FileIdentifier(1) == -1 ), error('Error: unable to open file cube.1'); end
      fprintf(FileIdentifier(1), '%% FILE: cube.1\n%%\n' );
      fprintf(FileIdentifier(1), '%%       t             phi           theta          phi''          theta''\n' );
      fprintf(FileIdentifier(1), '%%   (second)        (UNITS)        (UNITS)        (UNITS)        (UNITS)\n\n' );
   end
   hasHeaderInformationBeenWritten = 1;
end

if( shouldPrintToScreen ), WriteNumericalData( 1,                 Output(1:5) );  end
if( shouldPrintToFile ),   WriteNumericalData( FileIdentifier(1), Output(1:5) );  end
end


%===========================================================================
function WriteNumericalData( fileIdentifier, Output )
%===========================================================================
numberOfOutputQuantities = length( Output );
if( numberOfOutputQuantities > 0 ),
   for( i = 1 : numberOfOutputQuantities ),
      fprintf( fileIdentifier, ' %- 14.6E', Output(i) );
   end
   fprintf( fileIdentifier, '\n' );
end
end



%===========================================================================
function [functionsToEvaluateForEvent, eventTerminatesIntegration1Otherwise0ToContinue, eventDirection_AscendingIs1_CrossingIs0_DescendingIsNegative1] = EventDetection( t, VAR, uSimulink )
%===========================================================================
% Detects when designated functions are zero or cross zero with positive or negative slope.
% Step 1: Uncomment call to mdlDerivatives and mdlOutputs.
% Step 2: Change functionsToEvaluateForEvent,                      e.g., change  []  to  [t - 5.67]  to stop at t = 5.67.
% Step 3: Change eventTerminatesIntegration1Otherwise0ToContinue,  e.g., change  []  to  [1]  to stop integrating.
% Step 4: Change eventDirection_AscendingIs1_CrossingIs0_DescendingIsNegative1,  e.g., change  []  to  [1].
% Step 5: Possibly modify function EventDetectedByIntegrator (if eventTerminatesIntegration1Otherwise0ToContinue is 0).
%---------------------------------------------------------------------------
% mdlDerivatives( t, VAR, uSimulink );        % UNCOMMENT FOR EVENT HANDLING
% mdlOutputs(     t, VAR, uSimulink );        % UNCOMMENT FOR EVENT HANDLING
functionsToEvaluateForEvent = [];
eventTerminatesIntegration1Otherwise0ToContinue = [];
eventDirection_AscendingIs1_CrossingIs0_DescendingIsNegative1 = [];
eventDetectedByIntegratorTerminate1OrContinue0 = eventTerminatesIntegration1Otherwise0ToContinue;
end


%===========================================================================
function [isIntegrationFinished, VAR] = EventDetectedByIntegrator( t, VAR, nIndexOfEvents )
%===========================================================================
isIntegrationFinished = eventDetectedByIntegratorTerminate1OrContinue0( nIndexOfEvents );
if( ~isIntegrationFinished ),
   SetNamedQuantitiesFromMatrix( VAR );
%  Put code here to modify how integration continues.
   VAR = SetMatrixFromNamedQuantities;
end
end



%===========================================================================
function [t,VAR,Output] = IntegrateForwardOrBackward( tInitial, tFinal, tStep, absError, relError, VAR, printIntScreen, printIntFile )
%===========================================================================
OdeMatlabOptions = odeset( 'RelTol',relError, 'AbsTol',absError, 'MaxStep',tStep, 'Events',@EventDetection );
t = tInitial;                 epsilonT = 0.001*tStep;                   tFinalMinusEpsilonT = tFinal - epsilonT;
printCounterScreen = 0;       integrateForward = tFinal >= tInitial;    tAtEndOfIntegrationStep = t + tStep;
printCounterFile   = 0;       isIntegrationFinished = 0;
mdlDerivatives( t, VAR, 0 );
while 1,
   if( (integrateForward && t >= tFinalMinusEpsilonT) || (~integrateForward && t <= tFinalMinusEpsilonT) ), isIntegrationFinished = 1;  end
   shouldPrintToScreen = printIntScreen && ( isIntegrationFinished || printCounterScreen <= 0.01 );
   shouldPrintToFile   = printIntFile   && ( isIntegrationFinished || printCounterFile   <= 0.01 );
   if( isIntegrationFinished || shouldPrintToScreen || shouldPrintToFile ),
      Output = mdlOutputs( t, VAR, 0 );
      OutputToScreenOrFile( Output, shouldPrintToScreen, shouldPrintToFile );
      if( isIntegrationFinished ), break;  end
      if( shouldPrintToScreen ), printCounterScreen = printIntScreen;  end
      if( shouldPrintToFile ),   printCounterFile   = printIntFile;    end
   end
   [TimeOdeArray, VarOdeArray, timeEventOccurredInIntegrationStep, nStatesArraysAtEvent, nIndexOfEvents] = ode45( @mdlDerivatives, [t tAtEndOfIntegrationStep], VAR, OdeMatlabOptions, 0 );
   if( isempty(timeEventOccurredInIntegrationStep) ),
      lastIndex = length( TimeOdeArray );
      t = TimeOdeArray( lastIndex );
      VAR = VarOdeArray( lastIndex, : );
      printCounterScreen = printCounterScreen - 1;
      printCounterFile   = printCounterFile   - 1;
      if( abs(tAtEndOfIntegrationStep - t) >= abs(epsilonT) ), warning('numerical integration failed'); break;  end
      tAtEndOfIntegrationStep = t + tStep;
      if( (integrateForward && tAtEndOfIntegrationStep > tFinal) || (~integrateForward && tAtEndOfIntegrationStep < tFinal) ) tAtEndOfIntegrationStep = tFinal;  end
   else
      t = timeEventOccurredInIntegrationStep( 1 );    % time  at firstEvent = 1 during this integration step.
      VAR = nStatesArraysAtEvent( 1, : );             % state at firstEvent = 1 during this integration step.
      printCounterScreen = 0;
      printCounterFile   = 0;
      [isIntegrationFinished, VAR] = EventDetectedByIntegrator( t, VAR, nIndexOfEvents(1) );
   end
end
end


%=============================
end    % End of function cube
%=============================
