% %-------------------------------+--------------------------+-------------------+-----------------
% % Quantity                      | Value                    | Units             | Description
% %-------------------------------|--------------------------|-------------------|-----------------
CCMX                            =  0.072113;               % m                   Constant
CCMY                            =  0.071399;               % m                   Constant
CCMZ                            =  0.071467;               % m                   Constant
CIXX                            =  0.011496398;            % kg*m^2              Constant
CIXY                            = -0.004360713;            % kg*m^2              Constant
CIXZ                            =  0.004366281;            % kg*m^2              Constant
CIYY                            =  0.011603443;            % kg*m^2              Constant
CIYZ                            =  0.004314224;            % kg*m^2              Constant
CIZZ                            =  0.011600232;            % kg*m^2              Constant
g                               =  9.81;                   % m/s^2               Constant
mC                              =  0.84392696;             % kg                  Constant
mR                              =  0.04711499;             % kg                  Constant
RCMX                            =  0.076;                  % m                   Constant
RCMY                            =  0.076;                  % m                   Constant
RCMZ                            =  0.007789;               % m                   Constant
RXIXX                           =  0.000173232;            % kg*m^2              Constant
RXIXY                           =  8.33e-14;               % kg*m^2              Constant
RXIXZ                           = -3.587e-14;              % kg*m^2              Constant
RXIYY                           =  0.000086943;            % kg*m^2              Constant
RXIYZ                           = -0.000000127;            % kg*m^2              Constant
RXIZZ                           =  0.000087197;            % kg*m^2              Constant
RYIXX                           =  0.000087197;            % kg*m^2              Constant
RYIXY                           =  3.587e-14;              % kg*m^2              Constant
RYIXZ                           = -0.000000127;            % kg*m^2              Constant
RYIYY                           =  0.000173232;            % kg*m^2              Constant
RYIYZ                           = -8.33e-14;               % kg*m^2              Constant
RYIZZ                           =  0.000086943;            % kg*m^2              Constant
RZIXX                           =  0.000087197;            % kg*m^2              Constant
RZIXY                           =  0.000000127;            % kg*m^2              Constant
RZIXZ                           =  3.587e-14;              % kg*m^2              Constant
RZIYY                           =  0.000086943;            % kg*m^2              Constant
RZIYZ                           =  8.33e-14;               % kg*m^2              Constant
RZIZZ                           =  0.000173232;            % kg*m^2              Constant

% phi                             =  0.0;                    % UNITS               Initial Value
% theta                           =  0.0;                    % UNITS               Initial Value
% phiDt                           =  0.0;                    % UNITS               Initial Value
% thetaDt                         =  0.0;                    % UNITS               Initial Value

% tInitial                        =  0.0;                    % second              Initial Time
% tFinal                          =  10.0;                   % second              Final Time
% tStep                           =  0.05;                   % second              Integration Step
% printIntScreen                  =  1;                      % 0 or +integer       0 is NO screen output
% printIntFile                    =  1;                      % 0 or +integer       0 is NO file   output
% absError                        =  1.0E-05;                %                     Absolute Error
% relError                        =  1.0E-08;                %                     Relative Error

% function xdot = cube_dynamics(t, x, u)
%     theta   = x(1);
%     phi     = x(2);
%     thetaDt = x(3);
%     phiDt   = x(4);

%     qXDt = u(1);
%     qYDt = u(2);
%     qZDt = u(3);



%     xdot = [thetaDt; phiDt; thetaDDt; phiDDt];
% end

syms theta phi thetaDt phiDt qX qXDt qXDDt qY qYDt qYDDt qZ qZDt qZDDt psi psiDt psiDDt real 
thetaDDt = ((RXIXY*sin(theta)*cos(phi+psi+qX)+(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(sin(qZ)*cos(theta)+sin(theta)*cos(qZ)*cos(phi+psi))-  ...
RXIXZ*sin(theta)*sin(phi+psi+qX)-(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(sin(qY)*cos(theta)+sin(theta)*cos(qY)*sin(phi+psi))-(CIXX+RXIXX+2*  ...
mR*RCMY^2+2*mR*(RCMX-RCMY)^2+mR*(RCMZ^2+3*RCMX^2))*cos(theta)-(RYIXX*cos(qY)+RYIXZ*sin(qY))*(cos(qY)*cos(theta)-sin(qY)*sin(  ...
theta)*sin(phi+psi))-(RZIXX*cos(qZ)-RZIXY*sin(qZ))*(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi+psi))-sin(theta)*sin(phi+psi)*(  ...
CIXZ+mR*RCMX*RCMY+mR*RCMY*RCMZ+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(theta)*cos(phi+psi)*(mR*RCMX*  ...
RCMZ+mR*RCMY*RCMZ+mR*(RCMX*RCMY-(RCMX-RCMY)*(RCMX-RCMZ))-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(sin(phi+psi+qX)*(2*RXIYZ*sin(phi+psi+  ...
qX)*thetaDt*(phiDt+psiDt+qXDt)+(phiDt+psiDt+qXDt)*(RXIXZ*qXDt+RXIXZ*(phiDt+psiDt)+2*RXIZZ*cos(phi+psi+qX)*thetaDt)-2*RXIYY*cos(phi+  ...
psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-RXIXY*psiDDt-RXIXY*qXDDt)+cos(qY)*cos(phi+psi)*(4*RYIXZ*sin(qY)*qYDt*(phiDt+psiDt)+2*RYIXZ*cos(  ...
qY)*cos(phi+psi)*qYDt*thetaDt+2*RYIZZ*sin(qY)*cos(phi+psi)*qYDt*thetaDt+2*RYIZZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+qYDt*(  ...
RYIXY*qYDt+2*RYIXY*sin(phi+psi)*thetaDt+RYIXX*cos(qY)*(phiDt+psiDt)-2*RYIXX*sin(qY)*cos(phi+psi)*thetaDt)-RYIZZ*cos(qY)*qYDt*(  ...
phiDt+psiDt)-2*RYIYZ*cos(phi+psi)*thetaDt*(phiDt+psiDt)-4*RYIXZ*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIYZ*qYDDt-RYIXZ*cos(  ...
qY)*psiDDt-RYIZZ*sin(qY)*psiDDt)-g*((mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*cos(theta)-(mC*CCMY+mR*RCMY+2*mR*RCMX)*sin(theta)*sin(phi+psi)-(  ...
mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(theta)*cos(phi+psi))-cos(phi+psi+qX)*(RXIXY*(phiDt+psiDt+qXDt)^2+2*RXIYZ*cos(phi+psi+qX)*  ...
thetaDt*(phiDt+psiDt+qXDt)+RXIXZ*psiDDt+RXIXZ*qXDDt)-sin(qY)*cos(phi+psi)*(RYIXX*sin(qY)*qYDt*(phiDt+psiDt)+2*RYIXZ*sin(qY)*cos(phi+  ...
psi)*qYDt*thetaDt-2*RYIXY*cos(phi+psi)*thetaDt*(phiDt+psiDt)-2*RYIXX*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-qYDt*(RYIYZ*qYDt+  ...
2*RYIYZ*sin(phi+psi)*thetaDt+RYIZZ*sin(qY)*(phiDt+psiDt))-RYIXY*qYDDt-RYIXX*cos(qY)*psiDDt-RYIXZ*sin(qY)*psiDDt)-cos(qZ)*sin(phi+  ...
psi)*(2*RZIXY*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+2*RZIYY*cos(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIYZ*qZDDt+RZIXY*cos(qZ)*  ...
psiDDt-RZIYY*cos(qZ)*qZDt*(phiDt+psiDt)-2*RZIYZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-qZDt*(4*RZIXY*sin(qZ)*(phiDt+psiDt)-RZIXZ*qZDt-  ...
2*RZIXZ*cos(phi+psi)*thetaDt-RZIXX*cos(qZ)*(phiDt+psiDt)-2*RZIXX*sin(qZ)*sin(phi+psi)*thetaDt)-RZIYY*sin(qZ)*psiDDt)-sin(qZ)*sin(  ...
phi+psi)*(2*RZIXX*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+4*RZIXY*cos(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+qZDt*(RZIYY*sin(qZ)*(  ...
phiDt+psiDt)-RZIYZ*qZDt-2*RZIYZ*cos(phi+psi)*thetaDt-2*RZIXY*sin(qZ)*sin(phi+psi)*thetaDt-2*RZIYY*cos(qZ)*sin(phi+psi)*thetaDt)+  ...
RZIXZ*qZDDt+RZIXX*cos(qZ)*psiDDt-RZIXX*sin(qZ)*qZDt*(phiDt+psiDt)-2*RZIXZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RZIXY*sin(qZ)*  ...
psiDDt)-sin(phi+psi)*(2*CIYY*cos(phi+psi)*thetaDt*(phiDt+psiDt)+2*RYIXY*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+sin(qY)*(  ...
RYIXX*cos(qY)+RYIXZ*sin(qY))*(phiDt+psiDt)^2+CIXY*psiDDt+RYIYY*qYDDt+RYIXY*cos(qY)*psiDDt+RYIYZ*sin(qY)*psiDDt-2*CIYZ*sin(phi+psi)*  ...
thetaDt*(phiDt+psiDt)-cos(qY)*(phiDt+psiDt)*(2*RYIYZ*sin(phi+psi)*thetaDt+RYIXZ*cos(qY)*(phiDt+psiDt)+RYIZZ*sin(qY)*(phiDt+psiDt))-(  ...
phiDt+psiDt)*(RZIZZ*qZDt+CIXZ*(phiDt+psiDt)+2*CIZZ*cos(phi+psi)*thetaDt+2*RZIZZ*cos(phi+psi)*thetaDt+RZIXZ*cos(qZ)*(phiDt+psiDt)+  ...
mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDt+mR*RCMX*(RCMY*(phiDt+psiDt)+2*RCMZ*sin(phi+psi)*thetaDt)+mR*RCMY*(RCMZ*(phiDt+psiDt)+4*RCMX*  ...
sin(phi+psi)*thetaDt)-RZIYZ*sin(qZ)*(phiDt+psiDt)-mR*(2*(RCMX-RCMY)^2*sin(phi+psi)*thetaDt-RCMX^2*(phiDt+psiDt)-(RCMX-RCMY)*(RCMX-  ...
RCMZ)*(phiDt+psiDt)))-mR*RCMX*RCMZ*psiDDt-mR*RCMY*RCMZ*psiDDt-mR*(RCMX*RCMY*psiDDt+(RCMX-RCMY)^2*qZDDt-(RCMX-RCMY)*(RCMX-RCMZ)*  ...
psiDDt))-cos(phi+psi)*(2*CIYZ*cos(phi+psi)*thetaDt*(phiDt+psiDt)+2*RZIXZ*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+2*RZIYZ*cos(qZ)*  ...
cos(phi+psi)*thetaDt*(phiDt+psiDt)+sin(qZ)*(RZIXX*cos(qZ)-RZIXY*sin(qZ))*(phiDt+psiDt)^2+cos(qZ)*(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(  ...
phiDt+psiDt)^2+(phiDt+psiDt)*(RYIYY*qYDt+CIXY*(phiDt+psiDt)+2*RYIYY*sin(phi+psi)*thetaDt+RYIXY*cos(qY)*(phiDt+psiDt)+RYIYZ*sin(qY)*(  ...
phiDt+psiDt)-mR*RCMX*(RCMZ*(phiDt+psiDt)-4*RCMY*cos(phi+psi)*thetaDt)-mR*(RCMY*RCMZ*(phiDt+psiDt)-2*RCMX*(RCMX*sin(phi+psi)+RCMZ*  ...
cos(phi+psi))*thetaDt)-mR*(RCMX*RCMY*(phiDt+psiDt)+(RCMX-RCMY)^2*qZDt+2*(RCMX-RCMY)^2*cos(phi+psi)*thetaDt-(RCMX-RCMY)*(RCMX-RCMZ)*(  ...
phiDt+psiDt)))+CIXZ*psiDDt+RZIZZ*qZDDt+mR*RCMY*RCMZ*psiDDt+RZIXZ*cos(qZ)*psiDDt+mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDDt+mR*(RCMX^2+(  ...
RCMX-RCMY)*(RCMX-RCMZ))*psiDDt-RZIYZ*sin(qZ)*psiDDt-mR*(2*RCMZ^2*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RCMX*RCMY*psiDDt)))+(RXIXY*sin(  ...
phi+psi+qX)+RXIXZ*cos(phi+psi+qX)+cos(qY)*cos(phi+psi)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))+sin(qZ)*sin(phi+psi)*(RZIXX*cos(qZ)-RZIXY*sin(  ...
qZ))+cos(qZ)*sin(phi+psi)*(RZIXY*cos(qZ)-RZIYY*sin(qZ))+cos(phi+psi)*(CIXZ+mR*RCMX*RCMY+mR*RCMY*RCMZ+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-  ...
RCMZ))+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(qY)*cos(phi+psi)*(RYIXX*cos(qY)+RYIXZ*sin(qY))-sin(phi+psi)*(mR*RCMX*RCMZ+mR*RCMY*RCMZ+mR*(  ...
RCMX*RCMY-(RCMX-RCMY)*(RCMX-RCMZ))-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(mR*cos(theta)*(RCMY*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))+  ...
RCMZ*(RCMX*cos(phi+psi)+RCMY*sin(phi+psi)))*thetaDt*(phiDt+psiDt)+sin(theta)*thetaDt*(RXIXX*qXDt+CIXX*(phiDt+psiDt)+RXIXX*(phiDt+  ...
psiDt)+CIXY*sin(phi+psi)*thetaDt+CIXZ*cos(phi+psi)*thetaDt+RXIXY*sin(phi+psi+qX)*thetaDt+RXIXZ*cos(phi+psi+qX)*thetaDt+2*mR*RCMY^2*(  ...
phiDt+psiDt)+mR*(RCMZ^2+3*RCMX^2)*(phiDt+psiDt)+mR*(RCMY*(RCMX*cos(phi+psi)-RCMZ*sin(phi+psi))-RCMZ*(RCMX*sin(phi+psi)-RCMY*cos(phi+  ...
psi)))*thetaDt-mR*(RCMX*RCMY*sin(phi+psi)*thetaDt-RCMX^2*cos(phi+psi)*thetaDt-2*(RCMX-RCMY)^2*(phiDt+psiDt)-(RCMX-RCMY)*(RCMX-RCMZ)*  ...
qZDt-(RCMX-RCMY)*(RCMX-RCMZ)*sin(phi+psi)*thetaDt-(RCMX-RCMY)*(RCMX-RCMZ)*cos(phi+psi)*thetaDt))+sin(theta)*sin(phi+psi+qX)*(  ...
RXIZZ*sin(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-2*RXIYZ*cos(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-(phiDt+psiDt+qXDt)*(RXIXY*qXDt+  ...
RXIXY*(phiDt+psiDt)+RXIYY*sin(phi+psi+qX)*thetaDt)-RXIXZ*psiDDt-RXIXZ*qXDDt)+(sin(qZ)*cos(theta)+sin(theta)*cos(qZ)*cos(phi+psi))*(  ...
RZIXY*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+RZIXY*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIYY*cos(qZ)*cos(phi+psi)*thetaDt*(  ...
phiDt+psiDt)+RZIYZ*qZDDt+RZIXY*cos(qZ)*psiDDt-RZIXY*sin(qZ)*qZDt*(phiDt+psiDt)-RZIYY*cos(qZ)*qZDt*(phiDt+psiDt)-RZIYZ*sin(phi+psi)*  ...
thetaDt*(phiDt+psiDt)-RZIYY*sin(qZ)*sin(phi+psi)*qZDt*thetaDt-(qZDt+cos(phi+psi)*thetaDt)*(RZIXY*sin(qZ)*(phiDt+psiDt)-RZIXZ*qZDt-  ...
RZIXZ*cos(phi+psi)*thetaDt-RZIXX*cos(qZ)*(phiDt+psiDt)-RZIXX*sin(qZ)*sin(phi+psi)*thetaDt-RZIXY*cos(qZ)*sin(phi+psi)*thetaDt)-  ...
RZIYY*sin(qZ)*psiDDt)+(sin(qY)*cos(theta)+sin(theta)*cos(qY)*sin(phi+psi))*(RYIXZ*sin(qY)*qYDt*(phiDt+psiDt)+RYIXZ*cos(qY)*cos(phi+  ...
psi)*qYDt*thetaDt+RYIZZ*sin(qY)*cos(phi+psi)*qYDt*thetaDt+RYIZZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIZZ*cos(qY)*qYDt*(  ...
phiDt+psiDt)-RYIYZ*cos(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXZ*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-(qYDt+sin(phi+psi)*  ...
thetaDt)*(RYIXX*sin(qY)*cos(phi+psi)*thetaDt-RYIXY*qYDt-RYIXY*sin(phi+psi)*thetaDt-RYIXX*cos(qY)*(phiDt+psiDt)-RYIXZ*sin(qY)*(  ...
phiDt+psiDt)-RYIXZ*cos(qY)*cos(phi+psi)*thetaDt)-RYIYZ*qYDDt-RYIXZ*cos(qY)*psiDDt-RYIZZ*sin(qY)*psiDDt)+(cos(qY)*cos(theta)-sin(qY)*  ...
sin(theta)*sin(phi+psi))*(RYIXX*sin(qY)*qYDt*(phiDt+psiDt)+RYIXX*cos(qY)*cos(phi+psi)*qYDt*thetaDt+RYIXZ*sin(qY)*cos(phi+psi)*qYDt*  ...
thetaDt+RYIXZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+(qYDt+sin(phi+psi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi+psi)*thetaDt-RYIYZ*qYDt-  ...
RYIYZ*sin(phi+psi)*thetaDt-RYIXZ*cos(qY)*(phiDt+psiDt)-RYIZZ*sin(qY)*(phiDt+psiDt)-RYIZZ*cos(qY)*cos(phi+psi)*thetaDt)-RYIXZ*cos(  ...
qY)*qYDt*(phiDt+psiDt)-RYIXY*cos(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXX*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXY*qYDDt-  ...
RYIXX*cos(qY)*psiDDt-RYIXZ*sin(qY)*psiDDt)+cos(theta)*(cos(phi+psi)*thetaDt*(RYIYY*qYDt+CIYY*sin(phi+psi)*thetaDt+CIYZ*cos(phi+psi)*  ...
thetaDt+RYIYY*sin(phi+psi)*thetaDt+RYIXY*cos(qY)*(phiDt+psiDt)+RYIYZ*sin(qY)*(phiDt+psiDt)+RYIYZ*cos(qY)*cos(phi+psi)*thetaDt-  ...
RYIXY*sin(qY)*cos(phi+psi)*thetaDt-mR*(RCMX-RCMY)^2*(qZDt+cos(phi+psi)*thetaDt)-mR*RCMX*(RCMZ*(phiDt+psiDt)-2*RCMY*cos(phi+psi)*  ...
thetaDt)-mR*RCMZ*(RCMY*(phiDt+psiDt)-RCMX*cos(phi+psi)*thetaDt))+sin(phi+psi)*thetaDt*(RZIYZ*sin(qZ)*(phiDt+psiDt)+mR*(RCMX-RCMY)^2*  ...
sin(phi+psi)*thetaDt-RZIZZ*qZDt-CIYZ*sin(phi+psi)*thetaDt-CIZZ*cos(phi+psi)*thetaDt-RZIZZ*cos(phi+psi)*thetaDt-RZIXZ*cos(qZ)*(  ...
phiDt+psiDt)-RZIXZ*sin(qZ)*sin(phi+psi)*thetaDt-RZIYZ*cos(qZ)*sin(phi+psi)*thetaDt-mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDt-mR*(RCMX*  ...
RCMY*(phiDt+psiDt)+RCMZ*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))*thetaDt)-mR*(RCMY*RCMZ*(phiDt+psiDt)-RCMX*(RCMX*cos(phi+psi)-2*RCMY*  ...
sin(phi+psi))*thetaDt))-(sin(phi+psi+qX)*(RXIYZ*sin(phi+psi+qX)+RXIZZ*cos(phi+psi+qX))-cos(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+  ...
RXIYZ*cos(phi+psi+qX)))*thetaDt^2-CIXX*psiDDt-RXIXX*psiDDt-RXIXX*qXDDt-2*mR*RCMY^2*psiDDt-mR*(RCMZ^2+3*RCMX^2)*psiDDt-mR*(RCMX-RCMY)*((  ...
RCMX-RCMZ)*qZDDt+2*(RCMX-RCMY)*psiDDt))+sin(theta)*cos(phi+psi)*(RYIYZ*cos(qY)*qYDt*(phiDt+psiDt)+CIYY*cos(phi+psi)*thetaDt*(  ...
phiDt+psiDt)+RYIYY*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RYIXY*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+(cos(qY)*(phiDt+psiDt)-sin(  ...
qY)*cos(phi+psi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi+psi)*thetaDt-RYIYZ*qYDt-RYIYZ*sin(phi+psi)*thetaDt-RYIXZ*cos(qY)*(phiDt+psiDt)-  ...
RYIZZ*sin(qY)*(phiDt+psiDt)-RYIZZ*cos(qY)*cos(phi+psi)*thetaDt)+CIXY*psiDDt+RYIYY*qYDDt+RYIXY*cos(qY)*psiDDt+RYIYZ*sin(qY)*  ...
psiDDt-RYIXY*sin(qY)*qYDt*(phiDt+psiDt)-2*CIYZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXY*cos(qY)*cos(phi+psi)*qYDt*thetaDt-RYIYZ*sin(  ...
qY)*cos(phi+psi)*qYDt*thetaDt-RYIYZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-(sin(qY)*(phiDt+psiDt)+cos(qY)*cos(phi+psi)*  ...
thetaDt)*(RYIXX*sin(qY)*cos(phi+psi)*thetaDt-RYIXY*qYDt-RYIXY*sin(phi+psi)*thetaDt-RYIXX*cos(qY)*(phiDt+psiDt)-RYIXZ*sin(qY)*(  ...
phiDt+psiDt)-RYIXZ*cos(qY)*cos(phi+psi)*thetaDt)-(phiDt+psiDt)*(RZIZZ*qZDt+CIXZ*(phiDt+psiDt)+CIZZ*cos(phi+psi)*thetaDt+RZIZZ*cos(  ...
phi+psi)*thetaDt+RZIXZ*cos(qZ)*(phiDt+psiDt)+RZIXZ*sin(qZ)*sin(phi+psi)*thetaDt+RZIYZ*cos(qZ)*sin(phi+psi)*thetaDt+mR*((RCMX-RCMY)^2+(  ...
RCMX-RCMZ)^2)*qZDt+mR*(RCMX*RCMY*(phiDt+psiDt)+RCMZ*(RCMZ*cos(phi+psi)+2*RCMX*sin(phi+psi))*thetaDt)+mR*(RCMY*RCMZ*(phiDt+psiDt)-  ...
RCMX*(RCMX*cos(phi+psi)-4*RCMY*sin(phi+psi))*thetaDt)-RZIYZ*sin(qZ)*(phiDt+psiDt)-mR*(2*(RCMX-RCMY)^2*sin(phi+psi)*thetaDt-RCMX^2*(  ...
phiDt+psiDt)-(RCMX-RCMY)*(RCMX-RCMZ)*(phiDt+psiDt)))-mR*RCMX*RCMZ*psiDDt-mR*RCMY*RCMZ*psiDDt-mR*(RCMX*RCMY*psiDDt+(RCMX-RCMY)^2*  ...
qZDDt-(RCMX-RCMY)*(RCMX-RCMZ)*psiDDt))-g*((mC*CCMY+mR*RCMY+2*mR*RCMX)*cos(phi+psi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi+psi))-  ...
sin(theta)*cos(phi+psi+qX)*(2*RXIYZ*sin(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)+(phiDt+psiDt+qXDt)*(RXIXZ*qXDt+RXIXZ*(phiDt+psiDt)+  ...
RXIZZ*cos(phi+psi+qX)*thetaDt)-RXIYY*cos(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-RXIXY*psiDDt-RXIXY*qXDDt)-(cos(qZ)*cos(theta)-sin(  ...
qZ)*sin(theta)*cos(phi+psi))*(RZIXX*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+RZIXX*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIXY*cos(  ...
qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+(qZDt+cos(phi+psi)*thetaDt)*(RZIYY*sin(qZ)*(phiDt+psiDt)-RZIYZ*qZDt-RZIYZ*cos(phi+psi)*  ...
thetaDt-RZIXY*cos(qZ)*(phiDt+psiDt)-RZIXY*sin(qZ)*sin(phi+psi)*thetaDt-RZIYY*cos(qZ)*sin(phi+psi)*thetaDt)+RZIXZ*qZDDt+RZIXX*cos(  ...
qZ)*psiDDt-RZIXX*sin(qZ)*qZDt*(phiDt+psiDt)-RZIXY*cos(qZ)*qZDt*(phiDt+psiDt)-RZIXZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RZIXY*sin(qZ)*  ...
sin(phi+psi)*qZDt*thetaDt-RZIXY*sin(qZ)*psiDDt)-sin(theta)*sin(phi+psi)*(RZIXZ*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+2*CIYZ*cos(phi+psi)*  ...
thetaDt*(phiDt+psiDt)+RZIXZ*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIYZ*cos(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+(phiDt+  ...
psiDt)*(RYIYY*qYDt+CIXY*(phiDt+psiDt)+CIYY*sin(phi+psi)*thetaDt+RYIYY*sin(phi+psi)*thetaDt+RYIXY*cos(qY)*(phiDt+psiDt)+RYIYZ*sin(  ...
qY)*(phiDt+psiDt)+RYIYZ*cos(qY)*cos(phi+psi)*thetaDt-RYIXY*sin(qY)*cos(phi+psi)*thetaDt-mR*RCMX*(RCMZ*(phiDt+psiDt)-4*RCMY*cos(phi+  ...
psi)*thetaDt)-mR*(RCMY*RCMZ*(phiDt+psiDt)-RCMX*(RCMX*sin(phi+psi)+2*RCMZ*cos(phi+psi))*thetaDt)-mR*(RCMX*RCMY*(phiDt+psiDt)+(RCMX-  ...
RCMY)^2*qZDt+2*(RCMX-RCMY)^2*cos(phi+psi)*thetaDt-(RCMX-RCMY)*(RCMX-RCMZ)*(phiDt+psiDt)))+CIXZ*psiDDt+RZIZZ*qZDDt+mR*RCMY*RCMZ*  ...
psiDDt+RZIXZ*cos(qZ)*psiDDt+mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDDt+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))*psiDDt-RZIXZ*sin(qZ)*qZDt*(  ...
phiDt+psiDt)-RZIYZ*cos(qZ)*qZDt*(phiDt+psiDt)-CIZZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RZIZZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-  ...
RZIYZ*sin(qZ)*sin(phi+psi)*qZDt*thetaDt-(cos(qZ)*(phiDt+psiDt)+sin(qZ)*sin(phi+psi)*thetaDt)*(RZIYY*sin(qZ)*(phiDt+psiDt)-RZIYZ*qZDt-  ...
RZIYZ*cos(phi+psi)*thetaDt-RZIXY*cos(qZ)*(phiDt+psiDt)-RZIXY*sin(qZ)*sin(phi+psi)*thetaDt-RZIYY*cos(qZ)*sin(phi+psi)*thetaDt)-(sin(  ...
qZ)*(phiDt+psiDt)-cos(qZ)*sin(phi+psi)*thetaDt)*(RZIXY*sin(qZ)*(phiDt+psiDt)-RZIXZ*qZDt-RZIXZ*cos(phi+psi)*thetaDt-RZIXX*cos(qZ)*(  ...
phiDt+psiDt)-RZIXX*sin(qZ)*sin(phi+psi)*thetaDt-RZIXY*cos(qZ)*sin(phi+psi)*thetaDt)-RZIYZ*sin(qZ)*psiDDt-mR*(RCMZ^2*sin(phi+psi)*  ...
thetaDt*(phiDt+psiDt)-RCMX*RCMY*psiDDt))))/((RXIXY*sin(theta)*cos(phi+psi+qX)+(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(sin(qZ)*cos(theta)+sin(  ...
theta)*cos(qZ)*cos(phi+psi))-RXIXZ*sin(theta)*sin(phi+psi+qX)-(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(sin(qY)*cos(theta)+sin(theta)*cos(qY)*  ...
sin(phi+psi))-(CIXX+RXIXX+2*mR*RCMY^2+2*mR*(RCMX-RCMY)^2+mR*(RCMZ^2+3*RCMX^2))*cos(theta)-(RYIXX*cos(qY)+RYIXZ*sin(qY))*(cos(qY)*  ...
cos(theta)-sin(qY)*sin(theta)*sin(phi+psi))-(RZIXX*cos(qZ)-RZIXY*sin(qZ))*(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi+psi))-sin(  ...
theta)*sin(phi+psi)*(CIXZ+mR*RCMX*RCMY+mR*RCMY*RCMZ+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(theta)*cos(  ...
phi+psi)*(mR*RCMX*RCMZ+mR*RCMY*RCMZ+mR*(RCMX*RCMY-(RCMX-RCMY)*(RCMX-RCMZ))-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(2*mR*RCMY^2+mR*(RCMX^2+RCMZ^2+(  ...
RCMX-RCMY)^2+(RCMX-RCMZ)^2)+RXIZZ*cos(phi+psi+qX)^2+sin(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+2*RXIYZ*cos(phi+psi+qX))+cos(qY)*cos(phi+  ...
psi)*(2*RYIYZ*sin(phi+psi)+RYIZZ*cos(qY)*cos(phi+psi))+cos(qZ)*sin(phi+psi)*(2*RZIYZ*cos(phi+psi)+RZIYY*cos(qZ)*sin(phi+psi))+sin(  ...
qY)*cos(phi+psi)*(RYIXX*sin(qY)*cos(phi+psi)-2*RYIXY*sin(phi+psi)-2*RYIXZ*cos(qY)*cos(phi+psi))+sin(qZ)*sin(phi+psi)*(2*RZIXZ*cos(  ...
phi+psi)+RZIXX*sin(qZ)*sin(phi+psi)+2*RZIXY*cos(qZ)*sin(phi+psi))+cos(phi+psi)*(CIZZ*cos(phi+psi)+RZIZZ*cos(phi+psi)+mR*RCMZ^2*cos(  ...
phi+psi)+mR*RCMX*(RCMX*cos(phi+psi)+4*RCMY*sin(phi+psi)))-sin(phi+psi)*(2*mR*(RCMX-RCMY)^2*cos(phi+psi)-2*CIYZ*cos(phi+psi)-CIYY*  ...
sin(phi+psi)-RYIYY*sin(phi+psi)-2*mR*RCMX*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))))-(RXIXY*sin(phi+psi+qX)+RXIXZ*cos(phi+psi+qX)+cos(  ...
qY)*cos(phi+psi)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))+sin(qZ)*sin(phi+psi)*(RZIXX*cos(qZ)-RZIXY*sin(qZ))+cos(qZ)*sin(phi+psi)*(RZIXY*cos(  ...
qZ)-RZIYY*sin(qZ))+cos(phi+psi)*(CIXZ+mR*RCMX*RCMY+mR*RCMY*RCMZ+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-  ...
sin(qY)*cos(phi+psi)*(RYIXX*cos(qY)+RYIXZ*sin(qY))-sin(phi+psi)*(mR*RCMX*RCMZ+mR*RCMY*RCMZ+mR*(RCMX*RCMY-(RCMX-RCMY)*(RCMX-RCMZ))-  ...
CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(sin(theta)*cos(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+RXIYZ*cos(phi+psi+qX))+(sin(qZ)*cos(theta)+  ...
sin(theta)*cos(qZ)*cos(phi+psi))*(RZIYZ*cos(phi+psi)+RZIXY*sin(qZ)*sin(phi+psi)+RZIYY*cos(qZ)*sin(phi+psi))+(sin(qY)*cos(theta)+sin(  ...
theta)*cos(qY)*sin(phi+psi))*(RYIXZ*sin(qY)*cos(phi+psi)-RYIYZ*sin(phi+psi)-RYIZZ*cos(qY)*cos(phi+psi))+(cos(qY)*cos(theta)-sin(qY)*  ...
sin(theta)*sin(phi+psi))*(RYIXX*sin(qY)*cos(phi+psi)-RYIXY*sin(phi+psi)-RYIXZ*cos(qY)*cos(phi+psi))+sin(theta)*cos(phi+psi)*(CIYY*  ...
sin(phi+psi)+CIYZ*cos(phi+psi)+RYIYY*sin(phi+psi)+mR*RCMX*RCMZ*cos(phi+psi)+RYIYZ*cos(qY)*cos(phi+psi)+2*mR*RCMX*RCMY*cos(phi+psi)-  ...
RYIXY*sin(qY)*cos(phi+psi)-mR*(RCMX-RCMY)^2*cos(phi+psi))-sin(theta)*sin(phi+psi+qX)*(RXIYZ*sin(phi+psi+qX)+RXIZZ*cos(phi+psi+qX))-  ...
mR*cos(theta)*(RCMY*(RCMX*cos(phi+psi)-RCMZ*sin(phi+psi))-RCMZ*(RCMX*sin(phi+psi)-RCMY*cos(phi+psi)))-(cos(qZ)*cos(theta)-sin(qZ)*  ...
sin(theta)*cos(phi+psi))*(RZIXZ*cos(phi+psi)+RZIXX*sin(qZ)*sin(phi+psi)+RZIXY*cos(qZ)*sin(phi+psi))-cos(theta)*(CIXY*sin(phi+psi)+  ...
CIXZ*cos(phi+psi)+RXIXY*sin(phi+psi+qX)+RXIXZ*cos(phi+psi+qX)-mR*(RCMX*RCMY*sin(phi+psi)-RCMX^2*cos(phi+psi)-(RCMX-RCMY)*(RCMX-RCMZ)*  ...
sin(phi+psi)-(RCMX-RCMY)*(RCMX-RCMZ)*cos(phi+psi)))-sin(theta)*sin(phi+psi)*(CIYZ*sin(phi+psi)+CIZZ*cos(phi+psi)+RZIZZ*cos(phi+psi)+  ...
RZIXZ*sin(qZ)*sin(phi+psi)+RZIYZ*cos(qZ)*sin(phi+psi)+mR*RCMZ*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))-mR*(RCMX-RCMY)^2*sin(phi+psi)-  ...
mR*RCMX*(RCMX*cos(phi+psi)-2*RCMY*sin(phi+psi)))));

phiDDt   = -((sin(theta)*cos(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+RXIYZ*cos(phi+psi+qX))+(sin(qZ)*cos(theta)+sin(theta)*cos(qZ)*cos(phi+  ...
psi))*(RZIYZ*cos(phi+psi)+RZIXY*sin(qZ)*sin(phi+psi)+RZIYY*cos(qZ)*sin(phi+psi))+(sin(qY)*cos(theta)+sin(theta)*cos(qY)*sin(phi+psi))*(  ...
RYIXZ*sin(qY)*cos(phi+psi)-RYIYZ*sin(phi+psi)-RYIZZ*cos(qY)*cos(phi+psi))+(cos(qY)*cos(theta)-sin(qY)*sin(theta)*sin(phi+psi))*(  ...
RYIXX*sin(qY)*cos(phi+psi)-RYIXY*sin(phi+psi)-RYIXZ*cos(qY)*cos(phi+psi))+sin(theta)*cos(phi+psi)*(CIYY*sin(phi+psi)+CIYZ*cos(phi+  ...
psi)+RYIYY*sin(phi+psi)+mR*RCMX*RCMZ*cos(phi+psi)+RYIYZ*cos(qY)*cos(phi+psi)+2*mR*RCMX*RCMY*cos(phi+psi)-RYIXY*sin(qY)*cos(phi+psi)-  ...
mR*(RCMX-RCMY)^2*cos(phi+psi))-sin(theta)*sin(phi+psi+qX)*(RXIYZ*sin(phi+psi+qX)+RXIZZ*cos(phi+psi+qX))-mR*cos(theta)*(RCMY*(RCMX*  ...
cos(phi+psi)-RCMZ*sin(phi+psi))-RCMZ*(RCMX*sin(phi+psi)-RCMY*cos(phi+psi)))-(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi+psi))*(  ...
RZIXZ*cos(phi+psi)+RZIXX*sin(qZ)*sin(phi+psi)+RZIXY*cos(qZ)*sin(phi+psi))-cos(theta)*(CIXY*sin(phi+psi)+CIXZ*cos(phi+psi)+RXIXY*sin(  ...
phi+psi+qX)+RXIXZ*cos(phi+psi+qX)-mR*(RCMX*RCMY*sin(phi+psi)-RCMX^2*cos(phi+psi)-(RCMX-RCMY)*(RCMX-RCMZ)*sin(phi+psi)-(RCMX-RCMY)*(  ...
RCMX-RCMZ)*cos(phi+psi)))-sin(theta)*sin(phi+psi)*(CIYZ*sin(phi+psi)+CIZZ*cos(phi+psi)+RZIZZ*cos(phi+psi)+RZIXZ*sin(qZ)*sin(phi+psi)+  ...
RZIYZ*cos(qZ)*sin(phi+psi)+mR*RCMZ*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))-mR*(RCMX-RCMY)^2*sin(phi+psi)-mR*RCMX*(RCMX*cos(phi+psi)-  ...
2*RCMY*sin(phi+psi))))*(sin(phi+psi+qX)*(2*RXIYZ*sin(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)+(phiDt+psiDt+qXDt)*(RXIXZ*qXDt+RXIXZ*(  ...
phiDt+psiDt)+2*RXIZZ*cos(phi+psi+qX)*thetaDt)-2*RXIYY*cos(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-RXIXY*psiDDt-RXIXY*qXDDt)+cos(qY)*  ...
cos(phi+psi)*(4*RYIXZ*sin(qY)*qYDt*(phiDt+psiDt)+2*RYIXZ*cos(qY)*cos(phi+psi)*qYDt*thetaDt+2*RYIZZ*sin(qY)*cos(phi+psi)*qYDt*  ...
thetaDt+2*RYIZZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+qYDt*(RYIXY*qYDt+2*RYIXY*sin(phi+psi)*thetaDt+RYIXX*cos(qY)*(phiDt+  ...
psiDt)-2*RYIXX*sin(qY)*cos(phi+psi)*thetaDt)-RYIZZ*cos(qY)*qYDt*(phiDt+psiDt)-2*RYIYZ*cos(phi+psi)*thetaDt*(phiDt+psiDt)-4*RYIXZ*  ...
sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIYZ*qYDDt-RYIXZ*cos(qY)*psiDDt-RYIZZ*sin(qY)*psiDDt)-g*((mC*CCMZ+mR*RCMX+mR*RCMY+mR*  ...
RCMZ)*cos(theta)-(mC*CCMY+mR*RCMY+2*mR*RCMX)*sin(theta)*sin(phi+psi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(theta)*cos(phi+psi))-cos(  ...
phi+psi+qX)*(RXIXY*(phiDt+psiDt+qXDt)^2+2*RXIYZ*cos(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)+RXIXZ*psiDDt+RXIXZ*qXDDt)-sin(qY)*cos(  ...
phi+psi)*(RYIXX*sin(qY)*qYDt*(phiDt+psiDt)+2*RYIXZ*sin(qY)*cos(phi+psi)*qYDt*thetaDt-2*RYIXY*cos(phi+psi)*thetaDt*(phiDt+psiDt)-2*  ...
RYIXX*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-qYDt*(RYIYZ*qYDt+2*RYIYZ*sin(phi+psi)*thetaDt+RYIZZ*sin(qY)*(phiDt+psiDt))-  ...
RYIXY*qYDDt-RYIXX*cos(qY)*psiDDt-RYIXZ*sin(qY)*psiDDt)-cos(qZ)*sin(phi+psi)*(2*RZIXY*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+2*RZIYY*cos(  ...
qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIYZ*qZDDt+RZIXY*cos(qZ)*psiDDt-RZIYY*cos(qZ)*qZDt*(phiDt+psiDt)-2*RZIYZ*sin(phi+psi)*  ...
thetaDt*(phiDt+psiDt)-qZDt*(4*RZIXY*sin(qZ)*(phiDt+psiDt)-RZIXZ*qZDt-2*RZIXZ*cos(phi+psi)*thetaDt-RZIXX*cos(qZ)*(phiDt+psiDt)-2*  ...
RZIXX*sin(qZ)*sin(phi+psi)*thetaDt)-RZIYY*sin(qZ)*psiDDt)-sin(qZ)*sin(phi+psi)*(2*RZIXX*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+  ...
psiDt)+4*RZIXY*cos(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+qZDt*(RZIYY*sin(qZ)*(phiDt+psiDt)-RZIYZ*qZDt-2*RZIYZ*cos(phi+psi)*  ...
thetaDt-2*RZIXY*sin(qZ)*sin(phi+psi)*thetaDt-2*RZIYY*cos(qZ)*sin(phi+psi)*thetaDt)+RZIXZ*qZDDt+RZIXX*cos(qZ)*psiDDt-RZIXX*sin(qZ)*  ...
qZDt*(phiDt+psiDt)-2*RZIXZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RZIXY*sin(qZ)*psiDDt)-sin(phi+psi)*(2*CIYY*cos(phi+psi)*thetaDt*(  ...
phiDt+psiDt)+2*RYIXY*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+sin(qY)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(phiDt+psiDt)^2+CIXY*  ...
psiDDt+RYIYY*qYDDt+RYIXY*cos(qY)*psiDDt+RYIYZ*sin(qY)*psiDDt-2*CIYZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-cos(qY)*(phiDt+psiDt)*(2*  ...
RYIYZ*sin(phi+psi)*thetaDt+RYIXZ*cos(qY)*(phiDt+psiDt)+RYIZZ*sin(qY)*(phiDt+psiDt))-(phiDt+psiDt)*(RZIZZ*qZDt+CIXZ*(phiDt+psiDt)+  ...
2*CIZZ*cos(phi+psi)*thetaDt+2*RZIZZ*cos(phi+psi)*thetaDt+RZIXZ*cos(qZ)*(phiDt+psiDt)+mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDt+mR*RCMX*(  ...
RCMY*(phiDt+psiDt)+2*RCMZ*sin(phi+psi)*thetaDt)+mR*RCMY*(RCMZ*(phiDt+psiDt)+4*RCMX*sin(phi+psi)*thetaDt)-RZIYZ*sin(qZ)*(phiDt+  ...
psiDt)-mR*(2*(RCMX-RCMY)^2*sin(phi+psi)*thetaDt-RCMX^2*(phiDt+psiDt)-(RCMX-RCMY)*(RCMX-RCMZ)*(phiDt+psiDt)))-mR*RCMX*RCMZ*psiDDt-  ...
mR*RCMY*RCMZ*psiDDt-mR*(RCMX*RCMY*psiDDt+(RCMX-RCMY)^2*qZDDt-(RCMX-RCMY)*(RCMX-RCMZ)*psiDDt))-cos(phi+psi)*(2*CIYZ*cos(phi+psi)*  ...
thetaDt*(phiDt+psiDt)+2*RZIXZ*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+2*RZIYZ*cos(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+sin(qZ)*(  ...
RZIXX*cos(qZ)-RZIXY*sin(qZ))*(phiDt+psiDt)^2+cos(qZ)*(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(phiDt+psiDt)^2+(phiDt+psiDt)*(RYIYY*qYDt+CIXY*(  ...
phiDt+psiDt)+2*RYIYY*sin(phi+psi)*thetaDt+RYIXY*cos(qY)*(phiDt+psiDt)+RYIYZ*sin(qY)*(phiDt+psiDt)-mR*RCMX*(RCMZ*(phiDt+psiDt)-4*RCMY*  ...
cos(phi+psi)*thetaDt)-mR*(RCMY*RCMZ*(phiDt+psiDt)-2*RCMX*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))*thetaDt)-mR*(RCMX*RCMY*(phiDt+  ...
psiDt)+(RCMX-RCMY)^2*qZDt+2*(RCMX-RCMY)^2*cos(phi+psi)*thetaDt-(RCMX-RCMY)*(RCMX-RCMZ)*(phiDt+psiDt)))+CIXZ*psiDDt+RZIZZ*qZDDt+mR*  ...
RCMY*RCMZ*psiDDt+RZIXZ*cos(qZ)*psiDDt+mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDDt+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))*psiDDt-RZIYZ*sin(  ...
qZ)*psiDDt-mR*(2*RCMZ^2*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RCMX*RCMY*psiDDt)))+(2*mR*RCMY^2+mR*(RCMX^2+RCMZ^2+(RCMX-RCMY)^2+(RCMX-  ...
RCMZ)^2)+RXIZZ*cos(phi+psi+qX)^2+sin(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+2*RXIYZ*cos(phi+psi+qX))+cos(qY)*cos(phi+psi)*(2*RYIYZ*sin(  ...
phi+psi)+RYIZZ*cos(qY)*cos(phi+psi))+cos(qZ)*sin(phi+psi)*(2*RZIYZ*cos(phi+psi)+RZIYY*cos(qZ)*sin(phi+psi))+sin(qY)*cos(phi+psi)*(  ...
RYIXX*sin(qY)*cos(phi+psi)-2*RYIXY*sin(phi+psi)-2*RYIXZ*cos(qY)*cos(phi+psi))+sin(qZ)*sin(phi+psi)*(2*RZIXZ*cos(phi+psi)+RZIXX*sin(  ...
qZ)*sin(phi+psi)+2*RZIXY*cos(qZ)*sin(phi+psi))+cos(phi+psi)*(CIZZ*cos(phi+psi)+RZIZZ*cos(phi+psi)+mR*RCMZ^2*cos(phi+psi)+mR*RCMX*(  ...
RCMX*cos(phi+psi)+4*RCMY*sin(phi+psi)))-sin(phi+psi)*(2*mR*(RCMX-RCMY)^2*cos(phi+psi)-2*CIYZ*cos(phi+psi)-CIYY*sin(phi+psi)-  ...
RYIYY*sin(phi+psi)-2*mR*RCMX*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))))*(mR*cos(theta)*(RCMY*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))+RCMZ*(  ...
RCMX*cos(phi+psi)+RCMY*sin(phi+psi)))*thetaDt*(phiDt+psiDt)+sin(theta)*thetaDt*(RXIXX*qXDt+CIXX*(phiDt+psiDt)+RXIXX*(phiDt+psiDt)+  ...
CIXY*sin(phi+psi)*thetaDt+CIXZ*cos(phi+psi)*thetaDt+RXIXY*sin(phi+psi+qX)*thetaDt+RXIXZ*cos(phi+psi+qX)*thetaDt+2*mR*RCMY^2*(  ...
phiDt+psiDt)+mR*(RCMZ^2+3*RCMX^2)*(phiDt+psiDt)+mR*(RCMY*(RCMX*cos(phi+psi)-RCMZ*sin(phi+psi))-RCMZ*(RCMX*sin(phi+psi)-RCMY*cos(phi+  ...
psi)))*thetaDt-mR*(RCMX*RCMY*sin(phi+psi)*thetaDt-RCMX^2*cos(phi+psi)*thetaDt-2*(RCMX-RCMY)^2*(phiDt+psiDt)-(RCMX-RCMY)*(RCMX-RCMZ)*  ...
qZDt-(RCMX-RCMY)*(RCMX-RCMZ)*sin(phi+psi)*thetaDt-(RCMX-RCMY)*(RCMX-RCMZ)*cos(phi+psi)*thetaDt))+sin(theta)*sin(phi+psi+qX)*(  ...
RXIZZ*sin(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-2*RXIYZ*cos(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-(phiDt+psiDt+qXDt)*(RXIXY*qXDt+  ...
RXIXY*(phiDt+psiDt)+RXIYY*sin(phi+psi+qX)*thetaDt)-RXIXZ*psiDDt-RXIXZ*qXDDt)+(sin(qZ)*cos(theta)+sin(theta)*cos(qZ)*cos(phi+psi))*(  ...
RZIXY*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+RZIXY*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIYY*cos(qZ)*cos(phi+psi)*thetaDt*(  ...
phiDt+psiDt)+RZIYZ*qZDDt+RZIXY*cos(qZ)*psiDDt-RZIXY*sin(qZ)*qZDt*(phiDt+psiDt)-RZIYY*cos(qZ)*qZDt*(phiDt+psiDt)-RZIYZ*sin(phi+psi)*  ...
thetaDt*(phiDt+psiDt)-RZIYY*sin(qZ)*sin(phi+psi)*qZDt*thetaDt-(qZDt+cos(phi+psi)*thetaDt)*(RZIXY*sin(qZ)*(phiDt+psiDt)-RZIXZ*qZDt-  ...
RZIXZ*cos(phi+psi)*thetaDt-RZIXX*cos(qZ)*(phiDt+psiDt)-RZIXX*sin(qZ)*sin(phi+psi)*thetaDt-RZIXY*cos(qZ)*sin(phi+psi)*thetaDt)-  ...
RZIYY*sin(qZ)*psiDDt)+(sin(qY)*cos(theta)+sin(theta)*cos(qY)*sin(phi+psi))*(RYIXZ*sin(qY)*qYDt*(phiDt+psiDt)+RYIXZ*cos(qY)*cos(phi+  ...
psi)*qYDt*thetaDt+RYIZZ*sin(qY)*cos(phi+psi)*qYDt*thetaDt+RYIZZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIZZ*cos(qY)*qYDt*(  ...
phiDt+psiDt)-RYIYZ*cos(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXZ*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-(qYDt+sin(phi+psi)*  ...
thetaDt)*(RYIXX*sin(qY)*cos(phi+psi)*thetaDt-RYIXY*qYDt-RYIXY*sin(phi+psi)*thetaDt-RYIXX*cos(qY)*(phiDt+psiDt)-RYIXZ*sin(qY)*(  ...
phiDt+psiDt)-RYIXZ*cos(qY)*cos(phi+psi)*thetaDt)-RYIYZ*qYDDt-RYIXZ*cos(qY)*psiDDt-RYIZZ*sin(qY)*psiDDt)+(cos(qY)*cos(theta)-sin(qY)*  ...
sin(theta)*sin(phi+psi))*(RYIXX*sin(qY)*qYDt*(phiDt+psiDt)+RYIXX*cos(qY)*cos(phi+psi)*qYDt*thetaDt+RYIXZ*sin(qY)*cos(phi+psi)*qYDt*  ...
thetaDt+RYIXZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+(qYDt+sin(phi+psi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi+psi)*thetaDt-RYIYZ*qYDt-  ...
RYIYZ*sin(phi+psi)*thetaDt-RYIXZ*cos(qY)*(phiDt+psiDt)-RYIZZ*sin(qY)*(phiDt+psiDt)-RYIZZ*cos(qY)*cos(phi+psi)*thetaDt)-RYIXZ*cos(  ...
qY)*qYDt*(phiDt+psiDt)-RYIXY*cos(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXX*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXY*qYDDt-  ...
RYIXX*cos(qY)*psiDDt-RYIXZ*sin(qY)*psiDDt)+cos(theta)*(cos(phi+psi)*thetaDt*(RYIYY*qYDt+CIYY*sin(phi+psi)*thetaDt+CIYZ*cos(phi+psi)*  ...
thetaDt+RYIYY*sin(phi+psi)*thetaDt+RYIXY*cos(qY)*(phiDt+psiDt)+RYIYZ*sin(qY)*(phiDt+psiDt)+RYIYZ*cos(qY)*cos(phi+psi)*thetaDt-  ...
RYIXY*sin(qY)*cos(phi+psi)*thetaDt-mR*(RCMX-RCMY)^2*(qZDt+cos(phi+psi)*thetaDt)-mR*RCMX*(RCMZ*(phiDt+psiDt)-2*RCMY*cos(phi+psi)*  ...
thetaDt)-mR*RCMZ*(RCMY*(phiDt+psiDt)-RCMX*cos(phi+psi)*thetaDt))+sin(phi+psi)*thetaDt*(RZIYZ*sin(qZ)*(phiDt+psiDt)+mR*(RCMX-RCMY)^2*  ...
sin(phi+psi)*thetaDt-RZIZZ*qZDt-CIYZ*sin(phi+psi)*thetaDt-CIZZ*cos(phi+psi)*thetaDt-RZIZZ*cos(phi+psi)*thetaDt-RZIXZ*cos(qZ)*(  ...
phiDt+psiDt)-RZIXZ*sin(qZ)*sin(phi+psi)*thetaDt-RZIYZ*cos(qZ)*sin(phi+psi)*thetaDt-mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDt-mR*(RCMX*  ...
RCMY*(phiDt+psiDt)+RCMZ*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))*thetaDt)-mR*(RCMY*RCMZ*(phiDt+psiDt)-RCMX*(RCMX*cos(phi+psi)-2*RCMY*  ...
sin(phi+psi))*thetaDt))-(sin(phi+psi+qX)*(RXIYZ*sin(phi+psi+qX)+RXIZZ*cos(phi+psi+qX))-cos(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+  ...
RXIYZ*cos(phi+psi+qX)))*thetaDt^2-CIXX*psiDDt-RXIXX*psiDDt-RXIXX*qXDDt-2*mR*RCMY^2*psiDDt-mR*(RCMZ^2+3*RCMX^2)*psiDDt-mR*(RCMX-RCMY)*((  ...
RCMX-RCMZ)*qZDDt+2*(RCMX-RCMY)*psiDDt))+sin(theta)*cos(phi+psi)*(RYIYZ*cos(qY)*qYDt*(phiDt+psiDt)+CIYY*cos(phi+psi)*thetaDt*(  ...
phiDt+psiDt)+RYIYY*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RYIXY*sin(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)+(cos(qY)*(phiDt+psiDt)-sin(  ...
qY)*cos(phi+psi)*thetaDt)*(RYIXZ*sin(qY)*cos(phi+psi)*thetaDt-RYIYZ*qYDt-RYIYZ*sin(phi+psi)*thetaDt-RYIXZ*cos(qY)*(phiDt+psiDt)-  ...
RYIZZ*sin(qY)*(phiDt+psiDt)-RYIZZ*cos(qY)*cos(phi+psi)*thetaDt)+CIXY*psiDDt+RYIYY*qYDDt+RYIXY*cos(qY)*psiDDt+RYIYZ*sin(qY)*  ...
psiDDt-RYIXY*sin(qY)*qYDt*(phiDt+psiDt)-2*CIYZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RYIXY*cos(qY)*cos(phi+psi)*qYDt*thetaDt-RYIYZ*sin(  ...
qY)*cos(phi+psi)*qYDt*thetaDt-RYIYZ*cos(qY)*sin(phi+psi)*thetaDt*(phiDt+psiDt)-(sin(qY)*(phiDt+psiDt)+cos(qY)*cos(phi+psi)*  ...
thetaDt)*(RYIXX*sin(qY)*cos(phi+psi)*thetaDt-RYIXY*qYDt-RYIXY*sin(phi+psi)*thetaDt-RYIXX*cos(qY)*(phiDt+psiDt)-RYIXZ*sin(qY)*(  ...
phiDt+psiDt)-RYIXZ*cos(qY)*cos(phi+psi)*thetaDt)-(phiDt+psiDt)*(RZIZZ*qZDt+CIXZ*(phiDt+psiDt)+CIZZ*cos(phi+psi)*thetaDt+RZIZZ*cos(  ...
phi+psi)*thetaDt+RZIXZ*cos(qZ)*(phiDt+psiDt)+RZIXZ*sin(qZ)*sin(phi+psi)*thetaDt+RZIYZ*cos(qZ)*sin(phi+psi)*thetaDt+mR*((RCMX-RCMY)^2+(  ...
RCMX-RCMZ)^2)*qZDt+mR*(RCMX*RCMY*(phiDt+psiDt)+RCMZ*(RCMZ*cos(phi+psi)+2*RCMX*sin(phi+psi))*thetaDt)+mR*(RCMY*RCMZ*(phiDt+psiDt)-  ...
RCMX*(RCMX*cos(phi+psi)-4*RCMY*sin(phi+psi))*thetaDt)-RZIYZ*sin(qZ)*(phiDt+psiDt)-mR*(2*(RCMX-RCMY)^2*sin(phi+psi)*thetaDt-RCMX^2*(  ...
phiDt+psiDt)-(RCMX-RCMY)*(RCMX-RCMZ)*(phiDt+psiDt)))-mR*RCMX*RCMZ*psiDDt-mR*RCMY*RCMZ*psiDDt-mR*(RCMX*RCMY*psiDDt+(RCMX-RCMY)^2*  ...
qZDDt-(RCMX-RCMY)*(RCMX-RCMZ)*psiDDt))-g*((mC*CCMY+mR*RCMY+2*mR*RCMX)*cos(phi+psi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi+psi))-  ...
sin(theta)*cos(phi+psi+qX)*(2*RXIYZ*sin(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)+(phiDt+psiDt+qXDt)*(RXIXZ*qXDt+RXIXZ*(phiDt+psiDt)+  ...
RXIZZ*cos(phi+psi+qX)*thetaDt)-RXIYY*cos(phi+psi+qX)*thetaDt*(phiDt+psiDt+qXDt)-RXIXY*psiDDt-RXIXY*qXDDt)-(cos(qZ)*cos(theta)-sin(  ...
qZ)*sin(theta)*cos(phi+psi))*(RZIXX*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+RZIXX*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIXY*cos(  ...
qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+(qZDt+cos(phi+psi)*thetaDt)*(RZIYY*sin(qZ)*(phiDt+psiDt)-RZIYZ*qZDt-RZIYZ*cos(phi+psi)*  ...
thetaDt-RZIXY*cos(qZ)*(phiDt+psiDt)-RZIXY*sin(qZ)*sin(phi+psi)*thetaDt-RZIYY*cos(qZ)*sin(phi+psi)*thetaDt)+RZIXZ*qZDDt+RZIXX*cos(  ...
qZ)*psiDDt-RZIXX*sin(qZ)*qZDt*(phiDt+psiDt)-RZIXY*cos(qZ)*qZDt*(phiDt+psiDt)-RZIXZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RZIXY*sin(qZ)*  ...
sin(phi+psi)*qZDt*thetaDt-RZIXY*sin(qZ)*psiDDt)-sin(theta)*sin(phi+psi)*(RZIXZ*cos(qZ)*sin(phi+psi)*qZDt*thetaDt+2*CIYZ*cos(phi+psi)*  ...
thetaDt*(phiDt+psiDt)+RZIXZ*sin(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+RZIYZ*cos(qZ)*cos(phi+psi)*thetaDt*(phiDt+psiDt)+(phiDt+  ...
psiDt)*(RYIYY*qYDt+CIXY*(phiDt+psiDt)+CIYY*sin(phi+psi)*thetaDt+RYIYY*sin(phi+psi)*thetaDt+RYIXY*cos(qY)*(phiDt+psiDt)+RYIYZ*sin(  ...
qY)*(phiDt+psiDt)+RYIYZ*cos(qY)*cos(phi+psi)*thetaDt-RYIXY*sin(qY)*cos(phi+psi)*thetaDt-mR*RCMX*(RCMZ*(phiDt+psiDt)-4*RCMY*cos(phi+  ...
psi)*thetaDt)-mR*(RCMY*RCMZ*(phiDt+psiDt)-RCMX*(RCMX*sin(phi+psi)+2*RCMZ*cos(phi+psi))*thetaDt)-mR*(RCMX*RCMY*(phiDt+psiDt)+(RCMX-  ...
RCMY)^2*qZDt+2*(RCMX-RCMY)^2*cos(phi+psi)*thetaDt-(RCMX-RCMY)*(RCMX-RCMZ)*(phiDt+psiDt)))+CIXZ*psiDDt+RZIZZ*qZDDt+mR*RCMY*RCMZ*  ...
psiDDt+RZIXZ*cos(qZ)*psiDDt+mR*((RCMX-RCMY)^2+(RCMX-RCMZ)^2)*qZDDt+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))*psiDDt-RZIXZ*sin(qZ)*qZDt*(  ...
phiDt+psiDt)-RZIYZ*cos(qZ)*qZDt*(phiDt+psiDt)-CIZZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-RZIZZ*sin(phi+psi)*thetaDt*(phiDt+psiDt)-  ...
RZIYZ*sin(qZ)*sin(phi+psi)*qZDt*thetaDt-(cos(qZ)*(phiDt+psiDt)+sin(qZ)*sin(phi+psi)*thetaDt)*(RZIYY*sin(qZ)*(phiDt+psiDt)-RZIYZ*qZDt-  ...
RZIYZ*cos(phi+psi)*thetaDt-RZIXY*cos(qZ)*(phiDt+psiDt)-RZIXY*sin(qZ)*sin(phi+psi)*thetaDt-RZIYY*cos(qZ)*sin(phi+psi)*thetaDt)-(sin(  ...
qZ)*(phiDt+psiDt)-cos(qZ)*sin(phi+psi)*thetaDt)*(RZIXY*sin(qZ)*(phiDt+psiDt)-RZIXZ*qZDt-RZIXZ*cos(phi+psi)*thetaDt-RZIXX*cos(qZ)*(  ...
phiDt+psiDt)-RZIXX*sin(qZ)*sin(phi+psi)*thetaDt-RZIXY*cos(qZ)*sin(phi+psi)*thetaDt)-RZIYZ*sin(qZ)*psiDDt-mR*(RCMZ^2*sin(phi+psi)*  ...
thetaDt*(phiDt+psiDt)-RCMX*RCMY*psiDDt))))/((RXIXY*sin(theta)*cos(phi+psi+qX)+(RZIXY*cos(qZ)-RZIYY*sin(qZ))*(sin(qZ)*cos(theta)+sin(  ...
theta)*cos(qZ)*cos(phi+psi))-RXIXZ*sin(theta)*sin(phi+psi+qX)-(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(sin(qY)*cos(theta)+sin(theta)*cos(qY)*  ...
sin(phi+psi))-(CIXX+RXIXX+2*mR*RCMY^2+2*mR*(RCMX-RCMY)^2+mR*(RCMZ^2+3*RCMX^2))*cos(theta)-(RYIXX*cos(qY)+RYIXZ*sin(qY))*(cos(qY)*  ...
cos(theta)-sin(qY)*sin(theta)*sin(phi+psi))-(RZIXX*cos(qZ)-RZIXY*sin(qZ))*(cos(qZ)*cos(theta)-sin(qZ)*sin(theta)*cos(phi+psi))-sin(  ...
theta)*sin(phi+psi)*(CIXZ+mR*RCMX*RCMY+mR*RCMY*RCMZ+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-sin(theta)*cos(  ...
phi+psi)*(mR*RCMX*RCMZ+mR*RCMY*RCMZ+mR*(RCMX*RCMY-(RCMX-RCMY)*(RCMX-RCMZ))-CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(2*mR*RCMY^2+mR*(RCMX^2+RCMZ^2+(  ...
RCMX-RCMY)^2+(RCMX-RCMZ)^2)+RXIZZ*cos(phi+psi+qX)^2+sin(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+2*RXIYZ*cos(phi+psi+qX))+cos(qY)*cos(phi+  ...
psi)*(2*RYIYZ*sin(phi+psi)+RYIZZ*cos(qY)*cos(phi+psi))+cos(qZ)*sin(phi+psi)*(2*RZIYZ*cos(phi+psi)+RZIYY*cos(qZ)*sin(phi+psi))+sin(  ...
qY)*cos(phi+psi)*(RYIXX*sin(qY)*cos(phi+psi)-2*RYIXY*sin(phi+psi)-2*RYIXZ*cos(qY)*cos(phi+psi))+sin(qZ)*sin(phi+psi)*(2*RZIXZ*cos(  ...
phi+psi)+RZIXX*sin(qZ)*sin(phi+psi)+2*RZIXY*cos(qZ)*sin(phi+psi))+cos(phi+psi)*(CIZZ*cos(phi+psi)+RZIZZ*cos(phi+psi)+mR*RCMZ^2*cos(  ...
phi+psi)+mR*RCMX*(RCMX*cos(phi+psi)+4*RCMY*sin(phi+psi)))-sin(phi+psi)*(2*mR*(RCMX-RCMY)^2*cos(phi+psi)-2*CIYZ*cos(phi+psi)-CIYY*  ...
sin(phi+psi)-RYIYY*sin(phi+psi)-2*mR*RCMX*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))))-(RXIXY*sin(phi+psi+qX)+RXIXZ*cos(phi+psi+qX)+cos(  ...
qY)*cos(phi+psi)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))+sin(qZ)*sin(phi+psi)*(RZIXX*cos(qZ)-RZIXY*sin(qZ))+cos(qZ)*sin(phi+psi)*(RZIXY*cos(  ...
qZ)-RZIYY*sin(qZ))+cos(phi+psi)*(CIXZ+mR*RCMX*RCMY+mR*RCMY*RCMZ+mR*(RCMX^2+(RCMX-RCMY)*(RCMX-RCMZ))+RZIXZ*cos(qZ)-RZIYZ*sin(qZ))-  ...
sin(qY)*cos(phi+psi)*(RYIXX*cos(qY)+RYIXZ*sin(qY))-sin(phi+psi)*(mR*RCMX*RCMZ+mR*RCMY*RCMZ+mR*(RCMX*RCMY-(RCMX-RCMY)*(RCMX-RCMZ))-  ...
CIXY-RYIXY*cos(qY)-RYIYZ*sin(qY)))*(sin(theta)*cos(phi+psi+qX)*(RXIYY*sin(phi+psi+qX)+RXIYZ*cos(phi+psi+qX))+(sin(qZ)*cos(theta)+  ...
sin(theta)*cos(qZ)*cos(phi+psi))*(RZIYZ*cos(phi+psi)+RZIXY*sin(qZ)*sin(phi+psi)+RZIYY*cos(qZ)*sin(phi+psi))+(sin(qY)*cos(theta)+sin(  ...
theta)*cos(qY)*sin(phi+psi))*(RYIXZ*sin(qY)*cos(phi+psi)-RYIYZ*sin(phi+psi)-RYIZZ*cos(qY)*cos(phi+psi))+(cos(qY)*cos(theta)-sin(qY)*  ...
sin(theta)*sin(phi+psi))*(RYIXX*sin(qY)*cos(phi+psi)-RYIXY*sin(phi+psi)-RYIXZ*cos(qY)*cos(phi+psi))+sin(theta)*cos(phi+psi)*(CIYY*  ...
sin(phi+psi)+CIYZ*cos(phi+psi)+RYIYY*sin(phi+psi)+mR*RCMX*RCMZ*cos(phi+psi)+RYIYZ*cos(qY)*cos(phi+psi)+2*mR*RCMX*RCMY*cos(phi+psi)-  ...
RYIXY*sin(qY)*cos(phi+psi)-mR*(RCMX-RCMY)^2*cos(phi+psi))-sin(theta)*sin(phi+psi+qX)*(RXIYZ*sin(phi+psi+qX)+RXIZZ*cos(phi+psi+qX))-  ...
mR*cos(theta)*(RCMY*(RCMX*cos(phi+psi)-RCMZ*sin(phi+psi))-RCMZ*(RCMX*sin(phi+psi)-RCMY*cos(phi+psi)))-(cos(qZ)*cos(theta)-sin(qZ)*  ...
sin(theta)*cos(phi+psi))*(RZIXZ*cos(phi+psi)+RZIXX*sin(qZ)*sin(phi+psi)+RZIXY*cos(qZ)*sin(phi+psi))-cos(theta)*(CIXY*sin(phi+psi)+  ...
CIXZ*cos(phi+psi)+RXIXY*sin(phi+psi+qX)+RXIXZ*cos(phi+psi+qX)-mR*(RCMX*RCMY*sin(phi+psi)-RCMX^2*cos(phi+psi)-(RCMX-RCMY)*(RCMX-RCMZ)*  ...
sin(phi+psi)-(RCMX-RCMY)*(RCMX-RCMZ)*cos(phi+psi)))-sin(theta)*sin(phi+psi)*(CIYZ*sin(phi+psi)+CIZZ*cos(phi+psi)+RZIZZ*cos(phi+psi)+  ...
RZIXZ*sin(qZ)*sin(phi+psi)+RZIYZ*cos(qZ)*sin(phi+psi)+mR*RCMZ*(RCMX*sin(phi+psi)+RCMZ*cos(phi+psi))-mR*(RCMX-RCMY)^2*sin(phi+psi)-  ...
mR*RCMX*(RCMX*cos(phi+psi)-2*RCMY*sin(phi+psi)))));

x  = [theta; phi; thetaDt; phiDt];
u  = [qXDt; qYDt; qZDt];
f  = [thetaDt; phiDt; thetaDDt; phiDDt];

A = jacobian(f, x);
B = jacobian(f, u)

% --- Full substitution to remove all symbolic variables ---
A_lin = subs(A, {theta, phi, psi, ...
                 thetaDt, phiDt, psiDt, ...
                 psiDDt, ...
                 qX, qY, qZ, ...
                 qXDt, qYDt, qZDt, ...
                 qXDDt, qYDDt, qZDDt}, ...
                {pi/2, pi/2, 0, ...   % angles
                 0, 0, 0, ...          % angular rates
                 0, ...
                 0, 0, 0, ...          % positions
                 0, 0, 0, ...          % linear rates
                 0, 0, 0});            % linear accelerations

B_lin = subs(B, {theta, phi, psi, ...
                 thetaDt, phiDt, psiDt, ...
                 psiDDt, ...
                 qX, qY, qZ, ...
                 qXDt, qYDt, qZDt, ...
                 qXDDt, qYDDt, qZDDt}, ...
                {pi/2, pi/2, 0, ...   % angles
                 0, 0, 0, ...          % angular rates
                 0, ...
                 0, 0, 0, ...          % positions
                 0, 0, 0, ...          % linear rates
                 0, 0, 0});            % linear accelerations

% --- Now safely convert to numeric ---
A_num = double(A_lin)
B_num = double(B_lin)

