% Constants from MG
% %-------------------------------+--------------------------+-------------------+-----------------
% % Quantity                      | Value                    | Units             | Description
% %-------------------------------|--------------------------|-------------------|-----------------
CCMX                            =  0.072113;               % m                   Constant
CCMY                            =  0.071399;               % m                   Constant
CCMZ                            =  0.071467;               % m                   Constant
CIXX                            =  0.011496398;            % kg*m^2              Constant
CIXY                            = -0.004360713;            % kg*m^2              Constant
CIXZ                            =  0.004366281;            % kg*m^2              Constant
CIYY                            =  0.011603443;            % kg*m^2              Constant
CIYZ                            =  0.004314224;            % kg*m^2              Constant
CIZZ                            =  0.011600232;            % kg*m^2              Constant
g                               =  9.81;                   % m/s^2               Constant
mC                              =  0.84392696;             % kg                  Constant
mR                              =  0.04711499;             % kg                  Constant
RCMX                            =  0.076;                  % m                   Constant
RCMY                            =  0.076;                  % m                   Constant
RCMZ                            =  0.007789;               % m                   Constant
RXIXX                           =  0.000173232;            % kg*m^2              Constant
RXIXY                           =  8.33e-14;               % kg*m^2              Constant
RXIXZ                           = -3.587e-14;              % kg*m^2              Constant
RXIYY                           =  0.000086943;            % kg*m^2              Constant
RXIYZ                           = -0.000000127;            % kg*m^2              Constant
RXIZZ                           =  0.000087197;            % kg*m^2              Constant
RYIXX                           =  0.000087197;            % kg*m^2              Constant
RYIXY                           =  3.587e-14;              % kg*m^2              Constant
RYIXZ                           = -0.000000127;            % kg*m^2              Constant
RYIYY                           =  0.000173232;            % kg*m^2              Constant
RYIYZ                           = -8.33e-14;               % kg*m^2              Constant
RYIZZ                           =  0.000086943;            % kg*m^2              Constant
RZIXX                           =  0.000087197;            % kg*m^2              Constant
RZIXY                           =  0.000000127;            % kg*m^2              Constant
RZIXZ                           =  3.587e-14;              % kg*m^2              Constant
RZIYY                           =  0.000086943;            % kg*m^2              Constant
RZIYZ                           =  8.33e-14;               % kg*m^2              Constant
RZIZZ                           =  0.000173232;            % kg*m^2              Constant

% Governing Equations for Theta and Phi
syms theta phi thetaDt phiDt qX qXDt qXDDt qY qYDt qYDDt qZ qZDt qZDDt real 
thetaDDt = -((cos(theta)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))+sin(phi)*cos(theta)*(CIXY*cos(  ...
theta)-CIYY*sin(theta)-RYIYY*sin(theta)-mR*RCMX*RCMY*cos(theta)-mR*RCMX*RCMZ*cos(theta)-mR*RCMY*RCMZ*cos(theta))+cos(phi)*(CIXZ*cos(  ...
theta)+mR*RCMX^2*cos(theta)+mR*RCMX*(RCMY*cos(theta)-RCMZ*sin(theta))-CIYZ*sin(theta)-mR*RCMY*(2*RCMX*sin(theta)-RCMZ*cos(theta)))-  ...
sin(theta)*(RXIYY*cos(qX)-RXIYZ*sin(qX))*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))-cos(theta)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(  ...
sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))-sin(theta)*(RXIYZ*cos(qX)-RXIZZ*sin(qX))*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(  ...
theta))-sin(phi)*sin(theta)*(CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-mR*RCMX*RCMY*sin(theta)-mR*RCMX*RCMZ*sin(theta)-mR*  ...
RCMY*RCMZ*sin(theta))-sin(phi)*sin(qZ+theta)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-  ...
RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))-sin(phi)*cos(qZ+theta)*(RZIYY*(sin(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(  ...
phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))*(  ...
g*((mC*CCMY+mR*RCMY+2*mR*RCMX)*cos(phi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi)*cos(theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(  ...
phi)*sin(theta))+sin(qX)*sin(theta)*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(theta)*  ...
cos(qX)*phiDt*qXDt+RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*  ...
cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(  ...
phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-(qXDt+cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+  ...
sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+sin(theta)*cos(qX)*(RXIYY*cos(  ...
qX)*cos(theta)*phiDt*thetaDt+RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*  ...
thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(theta)*  ...
phiDt*thetaDt-RXIYZ*sin(theta)*cos(qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*  ...
cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*  ...
thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+cos(qY)*cos(theta)*(RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-  ...
RYIXX*sin(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(theta)*phiDt*thetaDt-RYIXX*thetaDt*(  ...
cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(  ...
phi)*cos(qY)*phiDt)-RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(  ...
theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXZ*cos(qY)*cos(  ...
theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))*thetaDt))+(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-  ...
cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*sin(phi)*  ...
sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(  ...
phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+  ...
cos(phi)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+  ...
theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))+sin(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*thetaDt+CIYZ*  ...
sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+mR*RCMX*  ...
thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(  ...
qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*  ...
thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*cos(theta)*  ...
phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-RCMZ*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+sin(phi)*sin(  ...
qY)*sin(theta))*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*  ...
sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*cos(theta)*  ...
phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+RXIXX*sin(phi)*  ...
sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(3*RCMX*sin(  ...
theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(  ...
phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*thetaDt+sin(  ...
phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*phiDt-  ...
sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(qY)*cos(theta)*(RYIXZ*sin(qY)*cos(theta)*phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*  ...
phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*  ...
sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)+RYIZZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*  ...
cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*  ...
cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(  ...
theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*  ...
thetaDt))-(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIXY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+  ...
thetaDt)+RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*  ...
qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(  ...
phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-RZIXX*cos(phi)*sin(qZ+theta)*phiDt*  ...
thetaDt-RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-(qZDt+cos(phi)*thetaDt)*(  ...
RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*thetaDt-  ...
RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(  ...
1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*  ...
phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(  ...
theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))))-cos(theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+  ...
RXIXX*sin(theta)*phiDt*thetaDt+CIXY*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*phiDt-RCMX*(3*RCMX*sin(phi)*cos(  ...
theta)*thetaDt+RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*phiDt-RCMZ*(RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(sin(phi)+3*sin(  ...
theta))*phiDt-RCMY*(RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(  ...
theta)*cos(phi)*phiDt)))-CIXX*sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*cos(theta)*thetaDt^2-  ...
RXIXX*sin(theta)*cos(phi)*phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)*(RXIYY*  ...
sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*  ...
cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt)*(  ...
RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(  ...
cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(  ...
phi)*(RCMX*sin(theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(  ...
theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*  ...
thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*  ...
sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-RXIXX*qXDDt))+(cos(theta)*(2*CIXY*sin(theta)-CIXX*  ...
cos(theta)-RXIXX*cos(theta)-2*mR*RCMX*RCMY*sin(theta)-2*mR*RCMX*RCMZ*sin(theta)-2*mR*RCMY*RCMZ*sin(theta))+sin(theta)^2*(RYIXX*cos(  ...
qY)^2+sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-CIYY-RYIYY-RXIZZ*sin(qX)^2-cos(qX)*(RXIYY*cos(qX)-2*RXIYZ*sin(qX)))-3*mR*RCMX^2-2*mR*RCMY^2-  ...
mR*RCMZ^2-RYIXX*cos(qY)^2-sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))^2-(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*  ...
cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(  ...
qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-2*RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))*((  ...
cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(  ...
theta)*cos(qX)*phiDt*qXDt+RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*  ...
cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*  ...
phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*  ...
phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(  ...
sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))-g*((mC*CCMX+  ...
mR*RCMX+mR*RCMY+mR*RCMZ)*sin(theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*cos(theta))-(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(  ...
RYIXZ*sin(qY)*cos(theta)*phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(  ...
cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(  ...
phi)*cos(qY)*phiDt)+RYIZZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(  ...
theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(  ...
theta)*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(  ...
theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt))-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(  ...
RXIYY*cos(qX)*cos(theta)*phiDt*thetaDt+RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*  ...
cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(  ...
theta)*phiDt*thetaDt-RXIYZ*sin(theta)*cos(qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*  ...
phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(  ...
theta)*thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(  ...
theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*(  ...
RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(  ...
theta)*phiDt*thetaDt-RYIXX*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*  ...
cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)-RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*  ...
cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*  ...
thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*  ...
thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt))-sin(phi)*cos(qZ+theta)*(RZIYY*sin(phi)*sin(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(  ...
theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(  ...
phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+cos(phi)*  ...
thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*  ...
thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-sin(phi)*sin(qZ+theta)*(RZIXY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+  ...
RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*  ...
qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-RZIXX*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-  ...
RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-(qZDt+cos(phi)*thetaDt)*(RZIYY*(sin(  ...
theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(  ...
theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*thetaDt-RZIYY*sin(phi)*cos(  ...
qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(  ...
theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*phiDt*(sin(theta)*  ...
cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*  ...
thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*  ...
qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*  ...
qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-  ...
sin(phi)*cos(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*thetaDt+CIYZ*sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*  ...
phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+mR*RCMX*thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*  ...
phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(  ...
theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*  ...
phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*  ...
sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*cos(theta)*phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*  ...
phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt)*(RYIXX*cos(  ...
qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(  ...
phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*cos(theta)*phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(  ...
theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+RXIXX*sin(phi)*sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(  ...
phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(3*RCMX*sin(theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(  ...
RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*  ...
sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*  ...
sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*thetaDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*  ...
sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(phi)*sin(  ...
theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+RXIXX*sin(theta)*phiDt*thetaDt+CIXY*  ...
sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*phiDt-RCMX*(3*RCMX*sin(phi)*cos(theta)*thetaDt+RCMZ*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*phiDt-RCMZ*(RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(sin(phi)+3*sin(theta))*phiDt-RCMY*(RCMX*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt)))-CIXX*  ...
sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*cos(theta)*thetaDt^2-RXIXX*sin(theta)*cos(phi)*  ...
phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-  ...
RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(  ...
qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt)*(RXIYZ*sin(theta)*cos(  ...
qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(  ...
phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(phi)*(RCMX*sin(  ...
theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(theta)*  ...
thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*  ...
thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*  ...
sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-RXIXX*qXDDt)-cos(phi)*(CIXZ*sin(theta)*phiDt*  ...
thetaDt+CIYZ*cos(theta)*phiDt*thetaDt+CIZZ*sin(phi)*phiDt*thetaDt+RZIZZ*sin(phi)*phiDt*thetaDt+CIYZ*sin(phi)*sin(theta)*thetaDt^2+  ...
mR*thetaDt*(2*RCMY^2*sin(phi)*phiDt+RCMX^2*(sin(theta)*phiDt+2*sin(phi)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*  ...
phiDt))+mR*RCMY*thetaDt*(2*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)+RCMZ*(sin(theta)*phiDt-sin(  ...
phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt))+mR*thetaDt*(RCMX*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(  ...
theta)*cos(phi)*phiDt)+RCMZ*(2*RCMZ*sin(phi)*phiDt+RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMX*RCMZ*(cos(theta)*phiDt+sin(phi)*  ...
sin(theta)*thetaDt)-RYIYY*qYDt-CIXY*cos(theta)*phiDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(  ...
theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)*thetaDt-RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt))-mR*RCMX*(2*RCMY*cos(phi)*thetaDt-RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-3*RCMX*(sin(theta)*phiDt-sin(phi)*  ...
cos(theta)*thetaDt)))+(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)*(CIXY*sin(theta)*phiDt-RXIXX*qXDt-CIXX*cos(theta)*phiDt-CIXZ*  ...
cos(phi)*thetaDt-RXIXX*cos(theta)*phiDt-CIXX*sin(phi)*sin(theta)*thetaDt-CIXY*sin(phi)*cos(theta)*thetaDt-RXIXX*sin(phi)*sin(  ...
theta)*thetaDt-mR*RCMY*(RCMX*cos(phi)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMX*(RCMX*(cos(phi)*  ...
thetaDt+3*cos(theta)*phiDt)+RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*(RCMY*RCMZ*cos(phi)*thetaDt+RCMX*(3*RCMX*sin(  ...
phi)*sin(theta)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))))+(cos(qZ+theta)*phiDt+sin(phi)*sin(qZ+theta)*  ...
thetaDt)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(  ...
sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*  ...
thetaDt-RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)+(sin(qZ+theta)*phiDt-sin(phi)*cos(qZ+theta)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(  ...
cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(  ...
phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(  ...
theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(  ...
cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-CIXZ*sin(phi)*cos(theta)*thetaDt^2-CIXZ*sin(theta)*cos(phi)*phiDt*thetaDt-CIYZ*cos(phi)*  ...
cos(theta)*phiDt*thetaDt-RZIZZ*qZDDt)))/((2*mR*RCMY^2+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))^2+RYIXX*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))^2+(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(  ...
theta))+2*RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta)))+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(RYIZZ*(cos(phi)*cos(  ...
qY)+sin(phi)*sin(qY)*sin(theta))-2*RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))+cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+2*  ...
CIXZ*sin(phi)*sin(theta)+2*CIYZ*sin(phi)*cos(theta)+2*mR*RCMX^2*(cos(phi)+sin(phi)*sin(theta))+2*mR*RCMY*sin(phi)*(RCMZ*sin(  ...
theta)+2*RCMX*cos(theta))+2*mR*(RCMX*RCMY*sin(phi)*sin(theta)+RCMZ*(RCMZ*cos(phi)+RCMX*sin(phi)*cos(theta))))+sin(phi)^2*(mR*RCMZ^2+  ...
3*mR*RCMX^2+RZIYY*cos(qZ+theta)^2+sin(qZ+theta)*(RZIXX*sin(qZ+theta)+2*RZIXY*cos(qZ+theta))+cos(theta)*(CIYY*cos(theta)+RYIYY*cos(  ...
theta)-2*mR*RCMX*RCMZ*sin(theta))+sin(theta)*(CIXX*sin(theta)+RXIXX*sin(theta)+2*CIXY*cos(theta)-2*mR*RCMX*RCMY*cos(theta)-2*mR*RCMY*  ...
RCMZ*cos(theta))))*(cos(theta)*(2*CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-2*mR*RCMX*RCMY*sin(theta)-2*mR*RCMX*RCMZ*sin(  ...
theta)-2*mR*RCMY*RCMZ*sin(theta))+sin(theta)^2*(RYIXX*cos(qY)^2+sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-CIYY-RYIYY-RXIZZ*sin(qX)^2-  ...
cos(qX)*(RXIYY*cos(qX)-2*RXIYZ*sin(qX)))-3*mR*RCMX^2-2*mR*RCMY^2-mR*RCMZ^2-RYIXX*cos(qY)^2-sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-  ...
RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))^2-(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(  ...
phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(  ...
theta)^2*(1-cos(phi)))))*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+  ...
cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-2*RZIXY*(sin(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-  ...
cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))-(sin(theta)*cos(qX)*(RXIYZ*cos(phi)*cos(qX)+RXIYY*(sin(qX)*cos(phi)+sin(  ...
phi)*cos(qX)*cos(theta)))+sin(phi)*(RZIXY*sin(qZ+theta)+RZIYY*cos(qZ+theta))*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+  ...
cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))-cos(qY)*cos(theta)*(RYIXZ*cos(phi)*cos(qY)-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))-sin(qX)*sin(  ...
theta)*(RXIYZ*(sin(qX)*cos(phi)+2*sin(phi)*cos(qX)*cos(theta))+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta)))-sin(qY)*cos(  ...
theta)*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-RYIXZ*(sin(qY)*cos(phi)-2*sin(phi)*sin(theta)*cos(qY)))-cos(theta)*(  ...
CIXZ*cos(phi)+CIXX*sin(phi)*sin(theta)+CIXY*sin(phi)*cos(theta)+RXIXX*sin(phi)*sin(theta)+mR*RCMX*(RCMX*cos(phi)-RCMY*sin(phi)*cos(  ...
theta))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))+mR*RCMZ*(RCMY*cos(phi)-RCMX*sin(phi)*cos(theta)))-sin(theta)*(mR*RCMX*RCMZ*  ...
sin(phi)*sin(theta)-CIYZ*cos(phi)-CIXY*sin(phi)*sin(theta)-CIYY*sin(phi)*cos(theta)-RYIYY*sin(phi)*cos(theta)-mR*RCMX*RCMY*(2*cos(  ...
phi)-sin(phi)*sin(theta))-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta)))-sin(phi)*(RZIXX*sin(qZ+theta)+RZIXY*cos(qZ+theta))*(sin(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(  ...
theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))*(cos(theta)*(RYIXZ*cos(qY)+RYIZZ*sin(qY))*(cos(phi)*cos(qY)+sin(  ...
phi)*sin(qY)*sin(theta))+sin(phi)*cos(theta)*(CIXY*cos(theta)-CIYY*sin(theta)-RYIYY*sin(theta)-mR*RCMX*RCMY*cos(theta)-mR*RCMX*RCMZ*  ...
cos(theta)-mR*RCMY*RCMZ*cos(theta))+cos(phi)*(CIXZ*cos(theta)+mR*RCMX^2*cos(theta)+mR*RCMX*(RCMY*cos(theta)-RCMZ*sin(theta))-CIYZ*  ...
sin(theta)-mR*RCMY*(2*RCMX*sin(theta)-RCMZ*cos(theta)))-sin(theta)*(RXIYY*cos(qX)-RXIYZ*sin(qX))*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*  ...
cos(theta))-cos(theta)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))-sin(theta)*(RXIYZ*cos(qX)-  ...
RXIZZ*sin(qX))*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))-sin(phi)*sin(theta)*(CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(  ...
theta)-mR*RCMX*RCMY*sin(theta)-mR*RCMX*RCMZ*sin(theta)-mR*RCMY*RCMZ*sin(theta))-sin(phi)*sin(qZ+theta)*(RZIXY*(sin(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(  ...
phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))-  ...
sin(phi)*cos(qZ+theta)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+  ...
cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXY*(sin(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-  ...
cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))));
phiDDt = ((2*mR*RCMY^2+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))^2+RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))^2+(  ...
sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))+2*RXIYZ*(cos(phi)*cos(qX)-sin(  ...
phi)*sin(qX)*cos(theta)))+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-2*  ...
RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))+cos(phi)*(CIZZ*cos(phi)+RZIZZ*cos(phi)+2*CIXZ*sin(phi)*sin(theta)+2*CIYZ*sin(  ...
phi)*cos(theta)+2*mR*RCMX^2*(cos(phi)+sin(phi)*sin(theta))+2*mR*RCMY*sin(phi)*(RCMZ*sin(theta)+2*RCMX*cos(theta))+2*mR*(RCMX*RCMY*  ...
sin(phi)*sin(theta)+RCMZ*(RCMZ*cos(phi)+RCMX*sin(phi)*cos(theta))))+sin(phi)^2*(mR*RCMZ^2+3*mR*RCMX^2+RZIYY*cos(qZ+theta)^2+sin(qZ+  ...
theta)*(RZIXX*sin(qZ+theta)+2*RZIXY*cos(qZ+theta))+cos(theta)*(CIYY*cos(theta)+RYIYY*cos(theta)-2*mR*RCMX*RCMZ*sin(theta))+sin(  ...
theta)*(CIXX*sin(theta)+RXIXX*sin(theta)+2*CIXY*cos(theta)-2*mR*RCMX*RCMY*cos(theta)-2*mR*RCMY*RCMZ*cos(theta))))*(g*((mC*CCMY+mR*  ...
RCMY+2*mR*RCMX)*cos(phi)-(mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi)*cos(theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(phi)*sin(  ...
theta))+sin(qX)*sin(theta)*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(theta)*cos(qX)*  ...
phiDt*qXDt+RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(  ...
theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*  ...
sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-(qXDt+cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+  ...
sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+sin(theta)*cos(qX)*(RXIYY*cos(  ...
qX)*cos(theta)*phiDt*thetaDt+RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*  ...
thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(theta)*  ...
phiDt*thetaDt-RXIYZ*sin(theta)*cos(qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*  ...
cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*  ...
thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))+cos(qY)*cos(theta)*(RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-  ...
RYIXX*sin(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(theta)*phiDt*thetaDt-RYIXX*thetaDt*(  ...
cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(  ...
phi)*cos(qY)*phiDt)-RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(  ...
theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXZ*cos(qY)*cos(  ...
theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))*thetaDt))+(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-  ...
cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*sin(phi)*  ...
sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(  ...
phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+  ...
cos(phi)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+  ...
theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+  ...
sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*  ...
phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*  ...
thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))+sin(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*thetaDt+CIYZ*  ...
sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+mR*RCMX*  ...
thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(  ...
qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*  ...
thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*cos(theta)*  ...
phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-RCMZ*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+sin(phi)*sin(  ...
qY)*sin(theta))*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*  ...
sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*cos(theta)*  ...
phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+RXIXX*sin(phi)*  ...
sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(3*RCMX*sin(  ...
theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(  ...
phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*thetaDt+sin(  ...
phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*phiDt-  ...
sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(qY)*cos(theta)*(RYIXZ*sin(qY)*cos(theta)*phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*  ...
phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*  ...
sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)+RYIZZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*  ...
cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*  ...
cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(  ...
theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*  ...
thetaDt))-(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*  ...
sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIXY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+  ...
thetaDt)+RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*  ...
qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(  ...
phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-RZIXX*cos(phi)*sin(qZ+theta)*phiDt*  ...
thetaDt-RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-(qZDt+cos(phi)*thetaDt)*(  ...
RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(phi)*sin(qZ+theta)*thetaDt-  ...
RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(  ...
1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*  ...
phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(  ...
theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(  ...
theta)*(1-cos(phi))*qZDt))))-cos(theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+  ...
RXIXX*sin(theta)*phiDt*thetaDt+CIXY*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*phiDt-RCMX*(3*RCMX*sin(phi)*cos(  ...
theta)*thetaDt+RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*phiDt-RCMZ*(RCMY*(cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(sin(phi)+3*sin(  ...
theta))*phiDt-RCMY*(RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(  ...
theta)*cos(phi)*phiDt)))-CIXX*sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*cos(theta)*thetaDt^2-  ...
RXIXX*sin(theta)*cos(phi)*phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)*(RXIYY*  ...
sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*  ...
cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt)*(  ...
RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(  ...
cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(  ...
phi)*(RCMX*sin(theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(  ...
theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*  ...
thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*  ...
sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-RXIXX*qXDDt))+(sin(theta)*cos(qX)*(RXIYZ*cos(phi)*  ...
cos(qX)+RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta)))+sin(phi)*(RZIXY*sin(qZ+theta)+RZIYY*cos(qZ+theta))*(sin(theta)*(sin(  ...
qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-  ...
cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-cos(qY)*cos(theta)*(RYIXZ*cos(phi)*cos(qY)-RYIXX*(sin(qY)*cos(phi)-sin(phi)*  ...
sin(theta)*cos(qY)))-sin(qX)*sin(theta)*(RXIYZ*(sin(qX)*cos(phi)+2*sin(phi)*cos(qX)*cos(theta))+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*  ...
sin(qX)*cos(theta)))-sin(qY)*cos(theta)*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-RYIXZ*(sin(qY)*cos(phi)-2*sin(phi)*  ...
sin(theta)*cos(qY)))-cos(theta)*(CIXZ*cos(phi)+CIXX*sin(phi)*sin(theta)+CIXY*sin(phi)*cos(theta)+RXIXX*sin(phi)*sin(theta)+mR*RCMX*(  ...
RCMX*cos(phi)-RCMY*sin(phi)*cos(theta))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))+mR*RCMZ*(RCMY*cos(phi)-RCMX*sin(phi)*cos(  ...
theta)))-sin(theta)*(mR*RCMX*RCMZ*sin(phi)*sin(theta)-CIYZ*cos(phi)-CIXY*sin(phi)*sin(theta)-CIYY*sin(phi)*cos(theta)-RYIYY*sin(phi)*  ...
cos(theta)-mR*RCMX*RCMY*(2*cos(phi)-sin(phi)*sin(theta))-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta)))-sin(phi)*(RZIXX*sin(qZ+  ...
theta)+RZIXY*cos(qZ+theta))*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-  ...
cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))*((cos(phi)*cos(qX)-sin(phi)*  ...
sin(qX)*cos(theta))*(RXIYZ*sin(qX)*sin(theta)*phiDt*qXDt+RXIZZ*sin(qX)*cos(theta)*phiDt*thetaDt+RXIZZ*sin(theta)*cos(qX)*phiDt*qXDt+  ...
RXIZZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(theta)*qXDt-  ...
sin(qX)*cos(phi)*cos(theta)*phiDt)-RXIYZ*cos(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*  ...
cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-cos(phi)*cos(qX)*cos(theta)*phiDt)-(qXDt+cos(theta)*  ...
phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*  ...
cos(qX)*cos(theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt))-g*((mC*CCMX+mR*RCMX+mR*RCMY+mR*RCMZ)*sin(  ...
theta)-(mC*CCMZ+mR*RCMX+mR*RCMY+mR*RCMZ)*cos(theta))-(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*(RYIXZ*sin(qY)*cos(theta)*  ...
phiDt*qYDt+RYIXZ*sin(theta)*cos(qY)*phiDt*thetaDt+RYIZZ*sin(qY)*sin(theta)*phiDt*thetaDt+RYIXZ*thetaDt*(cos(phi)*cos(qY)*qYDt+sin(  ...
phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)+RYIZZ*  ...
thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-sin(qY)*  ...
sin(theta)*cos(phi)*phiDt)-RYIZZ*cos(qY)*cos(theta)*phiDt*qYDt-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXX*cos(qY)*  ...
cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-  ...
sin(phi)*sin(theta)*cos(qY))*thetaDt))-(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*cos(qX)*cos(theta)*phiDt*thetaDt+  ...
RXIYY*thetaDt*(sin(phi)*sin(qX)*phiDt+sin(phi)*sin(qX)*cos(theta)*qXDt+sin(phi)*sin(theta)*cos(qX)*thetaDt-cos(phi)*cos(qX)*qXDt-  ...
cos(phi)*cos(qX)*cos(theta)*phiDt)-RXIYY*sin(qX)*sin(theta)*phiDt*qXDt-RXIYZ*sin(qX)*cos(theta)*phiDt*thetaDt-RXIYZ*sin(theta)*cos(  ...
qX)*phiDt*qXDt-RXIYZ*thetaDt*(sin(phi)*sin(qX)*sin(theta)*thetaDt-sin(phi)*cos(qX)*phiDt-sin(qX)*cos(phi)*qXDt-sin(phi)*cos(qX)*cos(  ...
theta)*qXDt-sin(qX)*cos(phi)*cos(theta)*phiDt)-(qXDt+cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(RXIYZ*sin(theta)*cos(qX)*  ...
phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*  ...
sin(qX)*cos(theta))*thetaDt))-(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*(RYIXZ*cos(qY)*cos(theta)*phiDt*qYDt-RYIXX*sin(qY)*cos(  ...
theta)*phiDt*qYDt-RYIXX*sin(theta)*cos(qY)*phiDt*thetaDt-RYIXZ*sin(qY)*sin(theta)*phiDt*thetaDt-RYIXX*thetaDt*(cos(phi)*cos(qY)*qYDt+  ...
sin(phi)*sin(qY)*sin(theta)*qYDt-sin(phi)*sin(qY)*phiDt-sin(phi)*cos(qY)*cos(theta)*thetaDt-sin(theta)*cos(phi)*cos(qY)*phiDt)-  ...
RYIXZ*thetaDt*(sin(phi)*cos(qY)*phiDt+sin(qY)*cos(phi)*qYDt-sin(phi)*sin(qY)*cos(theta)*thetaDt-sin(phi)*sin(theta)*cos(qY)*qYDt-  ...
sin(qY)*sin(theta)*cos(phi)*phiDt)-(sin(theta)*phiDt-qYDt-sin(phi)*cos(theta)*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(  ...
qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(  ...
qY))*thetaDt))-sin(phi)*cos(qZ+theta)*(RZIYY*sin(phi)*sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXY*phiDt*(2*sin(theta)*cos(phi)*cos(  ...
qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(  ...
qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(  ...
theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))+(qZDt+cos(phi)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+  ...
cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(theta)*cos(  ...
qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-  ...
cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-RZIXY*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIYY*cos(phi)*cos(qZ+theta)*  ...
phiDt*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+thetaDt)-RZIYY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*  ...
thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(  ...
phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*  ...
thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-  ...
cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-sin(phi)*sin(qZ+theta)*(RZIXY*sin(phi)*  ...
sin(qZ+theta)*thetaDt*(qZDt+thetaDt)+RZIXX*phiDt*(2*sin(theta)*cos(phi)*cos(qZ)*thetaDt+cos(theta)*(sin(qZ)*thetaDt+sin(qZ)*(cos(  ...
phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))*(qZDt+2*thetaDt))-sin(theta)*(cos(qZ)*thetaDt-cos(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(1-cos(phi))*(sin(qZ)*cos(theta)*qZDt+2*sin(theta)*cos(qZ)*thetaDt)))-  ...
RZIXX*cos(phi)*sin(qZ+theta)*phiDt*thetaDt-RZIXY*cos(phi)*cos(qZ+theta)*phiDt*thetaDt-RZIXX*sin(phi)*cos(qZ+theta)*thetaDt*(qZDt+  ...
thetaDt)-(qZDt+cos(phi)*thetaDt)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-  ...
cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(  ...
phi)*sin(qZ+theta)*thetaDt-RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))*phiDt)-RZIXY*phiDt*(sin(theta)*cos(theta)*sin(qZ+theta)*(1-cos(phi))*thetaDt+sin(theta)*cos(theta)*sin(qZ-theta)*(  ...
1-cos(phi))*thetaDt-cos(theta)*(cos(qZ)*thetaDt+cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))*qZDt+sin(theta)*(sin(phi)*cos(qZ+  ...
theta)*phiDt-sin(qZ)*cos(theta)*(1-cos(phi))*qZDt))-sin(theta)*(sin(qZ)*(1-2*cos(phi))*thetaDt-sin(phi)*cos(qZ)*cos(theta)^2*  ...
phiDt-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi)))*qZDt-sin(theta)*(2*sin(qZ)*sin(theta)*(1-cos(phi))*thetaDt-sin(phi)*sin(qZ)*cos(  ...
theta)*phiDt-cos(qZ)*cos(theta)*(1-cos(phi))*qZDt))))-sin(phi)*cos(theta)*(CIXY*sin(theta)*phiDt*thetaDt+CIYY*cos(theta)*phiDt*  ...
thetaDt+CIYZ*sin(phi)*phiDt*thetaDt+RYIYY*cos(theta)*phiDt*thetaDt+CIYY*sin(phi)*sin(theta)*thetaDt^2+RYIYY*sin(phi)*sin(theta)*thetaDt^2+  ...
mR*RCMX*thetaDt*(2*RCMY*sin(phi)*phiDt+3*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMY*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt))+mR*thetaDt*(RCMX*RCMZ*sin(phi)*phiDt-RCMY*(RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)-2*RCMY*(cos(  ...
theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(qY)*cos(theta)*phiDt-(sin(qY)*cos(phi)-sin(phi)*sin(  ...
theta)*cos(qY))*thetaDt)*(RYIXZ*cos(qY)*cos(theta)*phiDt+RYIZZ*sin(qY)*cos(theta)*phiDt+RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*  ...
sin(theta))*thetaDt-RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-CIXY*sin(phi)*cos(theta)*thetaDt^2-CIYY*cos(phi)*  ...
cos(theta)*phiDt*thetaDt-RYIYY*cos(phi)*cos(theta)*phiDt*thetaDt-mR*RCMZ*thetaDt*(RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt)-RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*cos(theta)*phiDt))-(sin(qY)*cos(theta)*phiDt+(cos(phi)*cos(qY)+  ...
sin(phi)*sin(qY)*sin(theta))*thetaDt)*(RYIXX*cos(qY)*cos(theta)*phiDt+RYIXZ*sin(qY)*cos(theta)*phiDt+RYIXZ*(cos(phi)*cos(qY)+sin(  ...
phi)*sin(qY)*sin(theta))*thetaDt-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))*thetaDt)-cos(phi)*thetaDt*(RXIXX*qXDt+CIXX*  ...
cos(theta)*phiDt+CIXZ*cos(phi)*thetaDt+RXIXX*cos(theta)*phiDt+CIXX*sin(phi)*sin(theta)*thetaDt+CIXY*sin(phi)*cos(theta)*thetaDt+  ...
RXIXX*sin(phi)*sin(theta)*thetaDt+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))*thetaDt+mR*(RCMY*RCMZ*cos(phi)+RCMX*sin(phi)*(  ...
3*RCMX*sin(theta)-RCMZ*cos(theta)))*thetaDt-mR*RCMX*(RCMY*sin(phi)*cos(theta)*thetaDt-RCMX*(cos(phi)*thetaDt+6*cos(theta)*phiDt)))-(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*thetaDt-  ...
RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+2*cos(phi)*  ...
thetaDt+sin(phi)*sin(theta)*thetaDt)-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*  ...
cos(theta)*thetaDt))-mR*(RCMX*RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)+RCMZ*(RCMZ*cos(phi)*thetaDt-RCMX*(sin(theta)*  ...
phiDt-sin(phi)*cos(theta)*thetaDt))))-RYIYY*qYDDt)-sin(phi)*sin(theta)*(CIXX*sin(theta)*phiDt*thetaDt+CIXY*cos(theta)*phiDt*  ...
thetaDt+CIXZ*sin(phi)*phiDt*thetaDt+RXIXX*sin(theta)*phiDt*thetaDt+CIXY*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(RCMY*RCMZ*sin(phi)*  ...
phiDt-RCMX*(3*RCMX*sin(phi)*cos(theta)*thetaDt+RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)))+mR*thetaDt*(RCMX*RCMY*sin(phi)*  ...
phiDt-RCMZ*(RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+mR*thetaDt*(RCMX^2*(  ...
sin(phi)+3*sin(theta))*phiDt-RCMY*(RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMY*(sin(theta)*phiDt-sin(phi)*cos(  ...
theta)*thetaDt-sin(theta)*cos(phi)*phiDt)))-CIXX*sin(phi)*cos(theta)*thetaDt^2-CIXX*sin(theta)*cos(phi)*phiDt*thetaDt-RXIXX*sin(phi)*  ...
cos(theta)*thetaDt^2-RXIXX*sin(theta)*cos(phi)*phiDt*thetaDt-(sin(qX)*sin(theta)*phiDt+(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(  ...
theta))*thetaDt)*(RXIYY*sin(theta)*cos(qX)*phiDt-RXIYZ*sin(qX)*sin(theta)*phiDt-RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(  ...
theta))*thetaDt-RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-(sin(theta)*cos(qX)*phiDt-(sin(qX)*cos(phi)+sin(phi)*  ...
cos(qX)*cos(theta))*thetaDt)*(RXIYZ*sin(theta)*cos(qX)*phiDt-RXIZZ*sin(qX)*sin(theta)*phiDt-RXIYZ*(sin(qX)*cos(phi)+sin(phi)*cos(  ...
qX)*cos(theta))*thetaDt-RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))*thetaDt)-cos(phi)*thetaDt*(CIYY*sin(theta)*phiDt+  ...
RYIYY*sin(theta)*phiDt+mR*RCMZ*sin(phi)*(RCMX*sin(theta)+RCMZ*cos(theta))*thetaDt-RYIYY*qYDt-CIYZ*cos(phi)*thetaDt-CIXY*sin(phi)*  ...
sin(theta)*thetaDt-CIYY*sin(phi)*cos(theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(  ...
theta))*thetaDt-mR*RCMX*(2*RCMY*cos(phi)*thetaDt-RCMY*sin(phi)*sin(theta)*thetaDt-RCMX*(4*sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt)))-(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)*(CIYZ*sin(theta)*phiDt-RZIZZ*qZDt-CIXZ*cos(theta)*phiDt-CIZZ*cos(phi)*  ...
thetaDt-RZIZZ*cos(phi)*thetaDt-CIXZ*sin(phi)*sin(theta)*thetaDt-CIYZ*sin(phi)*cos(theta)*thetaDt-mR*RCMX^2*(cos(theta)*phiDt+sin(  ...
phi)*sin(theta)*thetaDt)-mR*RCMX*(RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))-mR*RCMY*(RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-2*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))-  ...
RXIXX*qXDDt)-cos(phi)*(CIXZ*sin(theta)*phiDt*thetaDt+CIYZ*cos(theta)*phiDt*thetaDt+CIZZ*sin(phi)*phiDt*thetaDt+RZIZZ*sin(phi)*  ...
phiDt*thetaDt+CIYZ*sin(phi)*sin(theta)*thetaDt^2+mR*thetaDt*(2*RCMY^2*sin(phi)*phiDt+RCMX^2*(sin(theta)*phiDt+2*sin(phi)*phiDt-sin(  ...
phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt))+mR*RCMY*thetaDt*(2*RCMX*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt-cos(phi)*  ...
cos(theta)*phiDt)+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt))+mR*thetaDt*(RCMX*RCMY*(sin(  ...
theta)*phiDt-sin(phi)*cos(theta)*thetaDt-sin(theta)*cos(phi)*phiDt)+RCMZ*(2*RCMZ*sin(phi)*phiDt+RCMX*(cos(theta)*phiDt+sin(phi)*sin(  ...
theta)*thetaDt-cos(phi)*cos(theta)*phiDt)))+(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)*(CIYY*sin(theta)*phiDt+RYIYY*sin(  ...
theta)*phiDt+mR*RCMX*RCMZ*(cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt)-RYIYY*qYDt-CIXY*cos(theta)*phiDt-CIYZ*cos(phi)*thetaDt-CIXY*  ...
sin(phi)*sin(theta)*thetaDt-CIYY*sin(phi)*cos(theta)*thetaDt-RYIYY*sin(phi)*cos(theta)*thetaDt-mR*RCMZ*(RCMX*cos(phi)*thetaDt-RCMY*(  ...
cos(theta)*phiDt+sin(phi)*sin(theta)*thetaDt))-mR*RCMX*(2*RCMY*cos(phi)*thetaDt-RCMY*(cos(theta)*phiDt+sin(phi)*sin(theta)*  ...
thetaDt)-3*RCMX*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)))+(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt)*(CIXY*sin(theta)*  ...
phiDt-RXIXX*qXDt-CIXX*cos(theta)*phiDt-CIXZ*cos(phi)*thetaDt-RXIXX*cos(theta)*phiDt-CIXX*sin(phi)*sin(theta)*thetaDt-CIXY*sin(phi)*  ...
cos(theta)*thetaDt-RXIXX*sin(phi)*sin(theta)*thetaDt-mR*RCMY*(RCMX*cos(phi)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*  ...
thetaDt))-mR*RCMX*(RCMX*(cos(phi)*thetaDt+3*cos(theta)*phiDt)+RCMY*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))-mR*(RCMY*RCMZ*  ...
cos(phi)*thetaDt+RCMX*(3*RCMX*sin(phi)*sin(theta)*thetaDt+RCMZ*(sin(theta)*phiDt-sin(phi)*cos(theta)*thetaDt))))+(cos(qZ+theta)*  ...
phiDt+sin(phi)*sin(qZ+theta)*thetaDt)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(  ...
1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt-RZIXY*sin(  ...
phi)*sin(qZ+theta)*thetaDt-RZIYY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(  ...
qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))*phiDt)+(sin(qZ+theta)*phiDt-sin(phi)*cos(qZ+theta)*thetaDt)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(  ...
phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(  ...
theta)^2*(1-cos(phi)))))*phiDt-RZIXX*sin(phi)*sin(qZ+theta)*thetaDt-RZIXY*sin(phi)*cos(qZ+theta)*thetaDt-RZIXX*(sin(theta)*(sin(  ...
theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-  ...
cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*phiDt)-CIXZ*sin(phi)*cos(theta)*thetaDt^2-CIXZ*sin(theta)*cos(phi)*  ...
phiDt*thetaDt-CIYZ*cos(phi)*cos(theta)*phiDt*thetaDt-RZIZZ*qZDDt)))/((2*mR*RCMY^2+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(  ...
theta))^2+RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY))^2+(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))*(RXIYY*(sin(qX)*cos(  ...
phi)+sin(phi)*cos(qX)*cos(theta))+2*RXIYZ*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta)))+(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(  ...
theta))*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-2*RYIXZ*(sin(qY)*cos(phi)-sin(phi)*sin(theta)*cos(qY)))+cos(phi)*(CIZZ*  ...
cos(phi)+RZIZZ*cos(phi)+2*CIXZ*sin(phi)*sin(theta)+2*CIYZ*sin(phi)*cos(theta)+2*mR*RCMX^2*(cos(phi)+sin(phi)*sin(theta))+2*mR*RCMY*  ...
sin(phi)*(RCMZ*sin(theta)+2*RCMX*cos(theta))+2*mR*(RCMX*RCMY*sin(phi)*sin(theta)+RCMZ*(RCMZ*cos(phi)+RCMX*sin(phi)*cos(theta))))+  ...
sin(phi)^2*(mR*RCMZ^2+3*mR*RCMX^2+RZIYY*cos(qZ+theta)^2+sin(qZ+theta)*(RZIXX*sin(qZ+theta)+2*RZIXY*cos(qZ+theta))+cos(theta)*(CIYY*  ...
cos(theta)+RYIYY*cos(theta)-2*mR*RCMX*RCMZ*sin(theta))+sin(theta)*(CIXX*sin(theta)+RXIXX*sin(theta)+2*CIXY*cos(theta)-2*mR*RCMX*RCMY*  ...
cos(theta)-2*mR*RCMY*RCMZ*cos(theta))))*(cos(theta)*(2*CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-2*mR*RCMX*RCMY*sin(theta)-  ...
2*mR*RCMX*RCMZ*sin(theta)-2*mR*RCMY*RCMZ*sin(theta))+sin(theta)^2*(RYIXX*cos(qY)^2+sin(qY)*(RYIZZ*sin(qY)+2*RYIXZ*cos(qY))-CIYY-  ...
RYIYY-RXIZZ*sin(qX)^2-cos(qX)*(RXIYY*cos(qX)-2*RXIYZ*sin(qX)))-3*mR*RCMX^2-2*mR*RCMY^2-mR*RCMZ^2-RYIXX*cos(qY)^2-sin(qY)*(RYIZZ*sin(  ...
qY)+2*RYIXZ*cos(qY))-RZIXX*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-  ...
cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))^2-(sin(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+  ...
sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(  ...
theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-2*  ...
RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))))-(sin(theta)*cos(qX)*(RXIYZ*cos(phi)*cos(qX)+  ...
RXIYY*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta)))+sin(phi)*(RZIXY*sin(qZ+theta)+RZIYY*cos(qZ+theta))*(sin(theta)*(sin(qZ)*sin(  ...
theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+  ...
sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-cos(qY)*cos(theta)*(RYIXZ*cos(phi)*cos(qY)-RYIXX*(sin(qY)*cos(phi)-sin(phi)*sin(  ...
theta)*cos(qY)))-sin(qX)*sin(theta)*(RXIYZ*(sin(qX)*cos(phi)+2*sin(phi)*cos(qX)*cos(theta))+RXIZZ*(cos(phi)*cos(qX)-sin(phi)*sin(  ...
qX)*cos(theta)))-sin(qY)*cos(theta)*(RYIZZ*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))-RYIXZ*(sin(qY)*cos(phi)-2*sin(phi)*sin(  ...
theta)*cos(qY)))-cos(theta)*(CIXZ*cos(phi)+CIXX*sin(phi)*sin(theta)+CIXY*sin(phi)*cos(theta)+RXIXX*sin(phi)*sin(theta)+mR*RCMX*(RCMX*  ...
cos(phi)-RCMY*sin(phi)*cos(theta))+mR*RCMY*(RCMX*cos(phi)-RCMZ*sin(phi)*cos(theta))+mR*RCMZ*(RCMY*cos(phi)-RCMX*sin(phi)*cos(  ...
theta)))-sin(theta)*(mR*RCMX*RCMZ*sin(phi)*sin(theta)-CIYZ*cos(phi)-CIXY*sin(phi)*sin(theta)-CIYY*sin(phi)*cos(theta)-RYIYY*sin(phi)*  ...
cos(theta)-mR*RCMX*RCMY*(2*cos(phi)-sin(phi)*sin(theta))-mR*RCMZ*(RCMX*cos(phi)-RCMY*sin(phi)*sin(theta)))-sin(phi)*(RZIXX*sin(qZ+  ...
theta)+RZIXY*cos(qZ+theta))*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-  ...
cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))*(cos(theta)*(RYIXZ*cos(qY)+  ...
RYIZZ*sin(qY))*(cos(phi)*cos(qY)+sin(phi)*sin(qY)*sin(theta))+sin(phi)*cos(theta)*(CIXY*cos(theta)-CIYY*sin(theta)-RYIYY*sin(  ...
theta)-mR*RCMX*RCMY*cos(theta)-mR*RCMX*RCMZ*cos(theta)-mR*RCMY*RCMZ*cos(theta))+cos(phi)*(CIXZ*cos(theta)+mR*RCMX^2*cos(theta)+mR*  ...
RCMX*(RCMY*cos(theta)-RCMZ*sin(theta))-CIYZ*sin(theta)-mR*RCMY*(2*RCMX*sin(theta)-RCMZ*cos(theta)))-sin(theta)*(RXIYY*cos(qX)-  ...
RXIYZ*sin(qX))*(sin(qX)*cos(phi)+sin(phi)*cos(qX)*cos(theta))-cos(theta)*(RYIXX*cos(qY)+RYIXZ*sin(qY))*(sin(qY)*cos(phi)-sin(phi)*  ...
sin(theta)*cos(qY))-sin(theta)*(RXIYZ*cos(qX)-RXIZZ*sin(qX))*(cos(phi)*cos(qX)-sin(phi)*sin(qX)*cos(theta))-sin(phi)*sin(theta)*(  ...
CIXY*sin(theta)-CIXX*cos(theta)-RXIXX*cos(theta)-mR*RCMX*RCMY*sin(theta)-mR*RCMX*RCMZ*sin(theta)-mR*RCMY*RCMZ*sin(theta))-sin(phi)*  ...
sin(qZ+theta)*(RZIXY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(  ...
theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi)))))-RZIXX*(sin(theta)*(sin(theta)*cos(  ...
qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-  ...
cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))-sin(phi)*cos(qZ+theta)*(RZIYY*(sin(theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))+  ...
cos(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))+cos(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))+sin(qZ)*(cos(phi)+cos(theta)^2*(  ...
1-cos(phi)))))-RZIXY*(sin(theta)*(sin(theta)*cos(qZ)*cos(theta)*(1-cos(phi))-sin(qZ)*(cos(phi)+sin(theta)^2*(1-cos(phi))))-cos(  ...
theta)*(sin(qZ)*sin(theta)*cos(theta)*(1-cos(phi))-cos(qZ)*(cos(phi)+cos(theta)^2*(1-cos(phi))))))));

% Given State and Control vectors create a linearized state matrix
x  = [theta; phi; qX; qY; qX; thetaDt; phiDt; qXDt; qYDt; qZDt];
u  = [qXDDt; qYDDt; qZDDt];
x_dot  = [thetaDt; phiDt; qXDt; qYDt; qZDt; thetaDDt; phiDDt; qXDDt; qYDDt; qZDDt];
A = jacobian(x_dot, x);
B = jacobian(x_dot, u);

% Substitute valves for the points that the system is linearized about
A_lin = subs(A, {theta, phi ...
                 thetaDt, phiDt ...
                 qX, qY, qZ, ...
                 qXDt, qYDt, qZDt, ...
                 qXDDt, qYDDt, qZDDt}, ...
                {pi/2, pi/2, ... 
                 0, 0, ... 
                 0, 0, 0, ...       
                 2*pi, 2*pi, 2*pi, ... 
                 0, 0, 0});

B_lin = subs(B, {theta, phi ...
                 thetaDt, phiDt ...
                 qX, qY, qZ, ...
                 qXDt, qYDt, qZDt, ...
                 qXDDt, qYDDt, qZDDt}, ...
                {pi/2, pi/2, ...
                 0, 0, ...
                 0, 0, 0, ...
                 2*pi, 2*pi, 2*pi, ...
                 0, 0, 0});
A_num = double(A_lin);
B_num = double(B_lin);

% Create C and D matrixes
C = zeros(2,10);
C(1,1) = 1;
C(2,2) = 1;
D = zeros(2,3);

% Display all matrixes
disp(A_num)
disp(B_num)
disp(C)
disp(D)

% Create state space system
sys = ss(A_num,B_num,C,D);

% Check for controllability
Co =ctrb(A_num, B_num);
rank(Co) % Rank should equal 10

% Plot the poles and zeros of the system
pzplot(sys)

function motors = cube_controller(x, params)
% x = state vector:
%   x = [theta; phi; qX; qY; qZ; thetaDt; phiDt; qXDt; qYDt; qZDt]
%
% params contains:
%   K1,K2,K3,K4,zK2,zK3          (gains)
%   alpha                        (gyro filter constant)
%   motors_speed_X, motors_speed_Y, motors_speed_Z   (integrators)
%   speed_X, speed_Y             (velocity terms)
%   gyro_raw = [GyX, GyY, GyZ]   (raw IMU values)
%
% returns motors = [m1; m2; m3]  PWM values for motors
    K1 = 180;
    K2 = 30.00; 
    K3 = 1.6;
    K4 = 0.008;
    zK2 = 8.00;
    zK3 = 0.30;
    % Unpack states
    theta   = x(1);
    phi     = x(2);
    qXDt    = x(8);
    qYDt    = x(9);
    qZDt    = x(10);

    % --- Filter Gyro ------------------------------------------------------
    gyro = params.gyro_raw / 131.0;

    persistent gyroXf gyroYf
    if isempty(gyroXf); gyroXf = 0; gyroYf = 0; end

    gyroXf = params.alpha*gyro(1) + (1-params.alpha)*gyroXf;
    gyroYf = params.alpha*gyro(2) + (1-params.alpha)*gyroYf;

    % --- PID-like control law ---------------------------------------------
    pwm_X = params.K1*theta + params.K2*gyroXf + ...
            params.K3*params.speed_X + params.K4*params.motors_speed_X;

    pwm_Y = params.K1*phi   + params.K2*gyroYf + ...
            params.K3*params.speed_Y + params.K4*params.motors_speed_Y;

    pwm_Z = params.zK2*gyro(3) + params.zK3*params.motors_speed_Z;

    % Saturate
    pwm_X = max(min(pwm_X,255),-255);
    pwm_Y = max(min(pwm_Y,255),-255);
    pwm_Z = max(min(pwm_Z,255),-255);

    % --- Motor integrators (like I-terms) ---------------------------------
    params.motors_speed_X = params.motors_speed_X + params.speed_X/5;
    params.motors_speed_Y = params.motors_speed_Y + params.speed_Y/5;

    % --- Transform XYZ torques → three motor torques ----------------------
    motors = XYZ_to_threeWay(-pwm_X, pwm_Y, -pwm_Z);

end

function motors = XYZ_to_threeWay(pwm_X,pwm_Y,pwm_Z)
    m1 = round((0.5*pwm_X - 0.866*pwm_Y)/1.37 + pwm_Z);
    m2 = round((0.5*pwm_X + 0.866*pwm_Y)/1.37 + pwm_Z);
    m3 = round(-pwm_X/1.37 + pwm_Z);
    motors = [m1; m2; m3];
end


% --- Gains ---


% --- geometry (120-degree triad) ---
T = [ 1,   -0.5,       -0.5;
      0,  sqrt(3)/2, -sqrt(3)/2;
      1,    1,          1    ];
Tinv = inv(T);

% --- Build K_tau : maps x -> [tau_X; tau_Y; tau_Z]  (3 x 10) ---
Ktau = zeros(3,10);

% tau_X (body X torque) comes from phi (x2), phiDt (x7), speed_X (combination of q dot)
% speed_X = T(1,:) * [qXDot; qYDot; qZDot] -> columns 8,9,10 correspond to qXDt,qYDt,qZDt
Ktau(1,2)  = K1;               % phi
Ktau(1,7)  = K2;               % phiDt
Ktau(1,8:10) = K3 * T(1,:);    % contribution from wheel speeds to speed_X

% tau_Y
Ktau(2,1)  = K1;               % theta
Ktau(2,6)  = K2;               % thetaDt
Ktau(2,8:10) = K3 * T(2,:);    % speed_Y

% tau_Z (yaw)
% include gyro (if you have gyro_z as a state) and wheel-speed yaw term:
Ktau(3,10) = zK2;              % if gyro Z is x(10) (otherwise adjust)
Ktau(3,8:10) = Ktau(3,8:10) + zK3 * T(3,:);

% --- Map body-torque gains to wheel gains: K_wheels = Tinv * Ktau ---
K_fw = Tinv * Ktau;   % 3 x 10

% Solve for estimate motor conversions
Vbatt      = 12.0;     % Battery voltage (V)
PWM_max    = 255;      % 8-bit PWM
Kt         = 0.018;    % Torque constant (Nm/A) (estimate)
R_winding  = 1.2;      % Winding resistance (Ohm) (estimate)
I_rotor    = 0.000173232;   % Rotor inertia (kg*m^2) (estimate)
gear_ratio = 1;        % Use 1 if no gearbox. If gearbox present, set, e.g., 30.

tau_perPWM = (Kt * Vbatt) / (R_winding * PWM_max);
G = (tau_perPWM * gear_ratio) / I_rotor;   % rad/s^2 per 1 PWM unit

fprintf('Acceleration per PWM unit: %.6f rad/s^2 per PWM\n', G);

% ----------------------------------------------
% 5. Convert firmware gain matrix to model K
% ----------------------------------------------
K_model = G * K_fw;

% Controller: u = -K_wheels * x
Acl = A_num - B_num * K_model

pcl = eig(Acl);
disp('Closed-loop poles (with geometry):'); disp(pcl);
